### ISSUE TITLE
No more possibility to load/use external xml data

### ISSUE THREAD

**Issue by fopaitry** [SeleniumHQ/selenium-ide#1137] opened 2020-09-17 07:52 UTC
## 🐛 Bug Report

With old versions, we were able to to load  and use external xml data
This was possible with Selenium IDE Options menu. https://www.youtube.com/watch?v=6J714rdtLKw
Now,  it seems there's no  more a way to do that

## To Reproduce

Watch the video : "Selenium IDE Options" required to allow js files configuration! 

## Expected behavior
Have possibility to load and use external data

## Project file reproducing this issue (highly encouraged)
Not possible

## Environment

OS:  Windows 10
Selenium IDE Version:   3.17
Selenium SIDE Runner Version:  
Node version: 
Browser: Chrome
Browser Version:    85.0

**Comment by corevo** [comment] 2020-09-17 07:59
This issue is not a bug but rather a feature request, anything that was available in the old IDE and should be ported into this one is considered a feature request, so for next time pick that template please.

I will need you to improve your issue quite a bit, I'll need you to explain what this feature was, what you used it for, mostly what is the use-case for it, a person who is unfamiliar with the old IDE, would not understand what it means "use external xml data", my intuition is that you are asking about data driver testing, in which case this issue is a duplicate and should be closed.

**Comment by fopaitry** [comment] 2020-09-17 12:08
Hi corevo.
I agree, it is a feature which was available before and not anymore.

Data parameterization and repetition are the most important thing in automation : no way any tester should have the same test saved multiple times  with different data. 
External data file allow :
1 to change data without  opening the test (change the environnement/url, change the password to access  the GUI, and all data to type in the test...)
2 to repeat test as many time as there's data in the external file ( same test cinematic  with different functionnal test/data) in using a loop in the commands

Selenium IDE is a tool  for non developers , so that the external file should be as easier as possible  : excel file would be the best but in first step, if it's easer xml file like before

**Comment by corevo** [comment] 2020-09-17 13:06
In this case it is a duplicate of #183 closing.

**Closed by corevo** 2020-09-17 13:06 UTC
Labels: awaiting answer
