### ISSUE TITLE
Execute Script does not recognize $ variable

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#418] opened 2018-09-26 14:01 UTC
## 🐛 Bug Report

We have a page using jQuery and want to execute the following command: `$('#myid').hide()`. This works fine in the browser (F12 dev tools) but the IDE says "$ is not defined".

![image](https://user-images.githubusercontent.com/498834/46085051-67cc3180-c1a5-11e8-9d07-b544e16e92a7.png)

**Comment by corevo** [comment] 2018-09-26 14:09
Duplicate of #368

**Closed by corevo** 2018-09-26 14:09 UTC
