### ISSUE TITLE
How to use if/else statements in (java)scripts in Selenium Ide

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#268] opened 2018-06-28 06:14 UTC
## Meta - How to use if/else statements in (java)scripts in Selenium Ide (version 3.13.0)? Can you write something like:
**execute script** return ( if(${count1} < ${count2}) return true else return false ) _variable_

I tried to do that, but with no luck.

OS:  Windows 10

Selenium IDE Version: 3.1.1

Selenium SIDE Runner Version:  

Node version:  

Browser:  Chrome (but uses a headless browser)

Browser Version:  

## Expected Behavior -
if/else statements not working

## Actual Behavior -
Want to use **if** command like:
**if** (something true) then do this
**if** (something not true) then jump to x
 
## Steps to reproduce -
**if** (button exist) then execute command **click at**

**Comment by corevo** [comment] 2018-06-28 12:34
Please follow the issue template to it's fullest, fill the current behavior in `Expected behavior` and what you wish happen in the `Actual behavior`.  
It makes handling issues for us easier.  
Also afaik we don't have a version named `3.13.1` the last one published was `3.1.1`.

**Comment by cemol** [comment] 2018-07-02 07:02
Now i have filled in "Expected behavior" and "Actual behavior" @corevo :)

**Comment by corevo** [comment] 2018-07-02 07:15
Control flow is under active development, we are planning on adding `if` `else` `while` and the likes.  
Closing duplicate of #101

**Closed by corevo** 2018-07-02 07:15 UTC
Labels: awaiting answer
