### ISSUE TITLE
Execute Script does not recognize variable from external script in chrome

### ISSUE THREAD

**Issue by redalucard93** [SeleniumHQ/selenium-ide#1167] opened 2020-12-11 11:33 UTC
### JSEncrypt is not defined in Google Chrome

Trying to load script in execute script and call function JSEncrypt. In chrome I have : <code> JSEncrypt  is not defined </code> but in firefoxe it works. I was wandering if Selenium IDE can load and recognize external functions in chrome : 

Here is my code : 

<code> 
       var req = new XMLHttpRequest();
        req.open('GET', 'jsencrypt.js', false);
        req.onreadystatechange = function(){
            if (req1.readyState == 4) {
                script = document.createElement('script');
                script.appendChild(document.createTextNode(req .responseText));
                document.head.appendChild(script);
                if (typeof encrypt == 'undefined') {
                    console.log('encrypt  undefined');
                    encryption(loginValue, passwordValue, login, new JSEncrypt());
                }
                else {
                    encryption(loginValue, passwordValue, login, encrypt);
                }
            }
        };

**Comment by ericvergnaud** [comment] 2020-12-14 16:56
I have the same issue here with pretty much all user defined variables, whether they are created by a downloaded script or inline.
The same snippet works in the Chrome console, and in Firefox.

**Comment by corevo** [comment] 2020-12-15 08:36
Duplicate of #368

**Closed by corevo** 2020-12-15 08:36 UTC
