### ISSUE TITLE
IDE3 wildcard character ignored for verify text comparisons

### ISSUE THREAD

**Issue by dparker-coder** [SeleniumHQ/selenium-ide#164] opened 2018-04-19 19:20 UTC
In the old Selenium IDE verifyText command, you could use the asterisk "*" as a wildcard in the expected value, like this: "Expected text*and more text".
The new IDE3 seems to treat "*" like any other character, so it says the comparison failed.
I also tried using a REGEX style, but that also doesn't work: "Expected text.*and more text"
I'm using the Chrome extension, Selenium IDE (v3.0.1).
Thanks for your work on the new IDE. Love the support for Chrome.

**Comment by corevo** [comment] 2018-04-20 09:49
Duplicate of #141

**Closed by corevo** 2018-04-20 09:49 UTC
