### ISSUE TITLE
Make play from this command use existing window session

### ISSUE THREAD

**Issue by saradhit** [SeleniumHQ/selenium-ide#440] opened 2018-10-04 15:48 UTC
## 🐛 Bug Report

I just got my Selenium IDE updated to v3.4.0. My script starts with "open" command, as expected, it opens up the web browser and logs me in successfully.

My script failed due to an assertion. When i started the execution by right clicking on the command and selecting "Play from here", it is opening a new browser window and by default closes the existing browser.

As it is closing the browser that the script was already running and tries to use the new browser window for execution script is failing as the elements didn't match.

## To Reproduce

1) Open Firefox a browser (62.0.3 (32-bit))
2) Click on selenium IDE icon (V3.4.0)
3) Start execution - My script has a open command as 1st command, So It is opening a new browser window and starting execution. 
It is ignoring the browser using which the IDE is opened for the first time. 
4) Script failed due to an assertion
5) I right clicked on the command failed, selected "Play from here". It opened a new browser window and tried to execute the script, but failed as the new browser window is a blank.
6) Whenever i tried to execute by selecting the "Play from here" command, it repeats the same behavior as mentioned in step 5.

--- It is totally blocking my test execution by opening up a new browser window (not tab) every time i try to execute the script.

## Expected behavior

As we are opening selenium IDE by clicking on selenium icon on the browser toolbar, it  is not required to open a new window when we start execution.

Also, It should not open a new browser window every time when user tries to execute the script from the step where it failed.

## Project file reproducing this issue (highly encouraged)

Sorry...I am not allowed to Share the project details. But this can be easily reproducible.

## Environment

OS: Windows 10 Enterprise, Version - 1703, OS Build - 15063.1324
Selenium IDE Version:  V3.4.0, updated Today.
Selenium SIDE Runner Version:  v3.2.0

Browser: Fire fox
Browser Version:  62.0.3 (32-bit)

**Comment by corevo** [comment] 2018-10-04 16:32
"Play from here" is a feature that has been falling behind, especially for more advanced tests, that use control flow, run and other powerful features.  
We are planning changes to it, for the meantime, what I would suggest you, is that if you're debugging a test case, turn on the pause on exception (the button left to the record).  
It will pause your test case when it errors, and will allow you to retry the command until the test case is fixed.

**Comment by saradhit** [comment] 2018-10-04 16:52
@corevo Before test execution, i turned on Pause on Exception and started execution. At one point, my script failed due to an assertion and script was paused as expected. After fixing the step, i clicked on "Resume Test Execution", execution was stopped automatically. Pause on Exception still shows as enabled.

**Comment by corevo** [comment] 2018-10-04 17:10
It paused when no exception was hit?

**Comment by saradhit** [comment] 2018-10-04 17:12
Yes, it paused the test execution.

**Comment by corevo** [comment] 2018-10-04 17:14
I will make sure to take a look, other than that did that do the work?  
We are going to improve that feature, adding strong debugging tools will eventually become the alternative.

**Comment by saradhit** [comment] 2018-10-04 17:19
Pausing on exception didn't solve my problem. As i mentioned, after the script was paused, i fixed the step and clicked on "Resume Test execution" button (||) which is actually stopping the test execution instead of Resuming the test execution from where it was paused.

**Comment by JavaJeffG** [comment] 2018-10-04 19:42
Would it be possible to add a button next to 'Disable breakpoints' called 'Start with new window' that we could turn off?

We really need the ability to "Play from here" on a test which encounters an error without starting a new browser window.  We use Selenium IDE tests for lots of reasons.  Some developers run one script to log into an app, and then another script to do some updates.   We might have a test that passes running against Production, but for some reason one step fails in Dev.  We really need the ability to continue the test starting on the next step without making changes.

One of many Selenium IDE 1.0 Test Suites we have that we converted over to Selenium IDE TNG had 30 test .html files.  This resulted in a .side file that is 950kb.  There are times when a test may have failed after 10 minutes because of some known error and we just want to finish out the last 50 steps.  Being able to turn off 'Start with new window' would really be helpful.

Lastly... thanks so much to you and the team working on the new Selenium IDE.  We have extensive tests/support scripts defined using the old Selenium IDE format and you have given us a way to migrate forward.

-- Jeff

**Comment by 98gmarquee** [comment] 2018-10-05 00:10
I'm running into a similar issue where it fails because it takes longer than 30sec for an element to become editable. Then when I try to restart/continue, it starts over with a fresh window vs where it stopped. I had the "pause on exception" clicked, but when I continue, it clears the url and starts over.

I didn't have a timeout issue like this previously, it seemed to wait a lot longer.

**Comment by julienb81** [comment] 2018-10-05 09:05
I've the same problem as @saradhit. After an error, when I click on "Play from here", the page is refreshed...
Play From here is an essential function for us.
We downgrade to 3.3.1 waiting correction

**Comment by corevo** [comment] 2018-10-05 09:08
Pause on exceptions doesn't work correctly, I'll ship a hotfix immediately.  
The idea is that it will pause on the first error, and continue from there once the error is fixed.

**Comment by corevo** [comment] 2018-10-05 09:16
@julienb81 "Play from here" can't work with the more advanced features of the IDE, "Pause on exceptions" is the way to go.  
We are planning to change that, but it will no longer work like it used to.

**Comment by julienb81** [comment] 2018-10-05 09:16
After an error, when I correct it, I often need to click on Play from here a few lines before the error.
Will it work after your hotfix?

**Comment by corevo** [comment] 2018-10-05 09:16
The hotfix is for "Pause on exceptions"

**Comment by julienb81** [comment] 2018-10-05 09:19
@corevo Ok. Will it be possible to restart at the line I want after an error without Selenium to refresh the page?

**Comment by corevo** [comment] 2018-10-05 09:29
Attaching example of "Pause on exceptions" in action
![pause-on-exceptions](https://user-images.githubusercontent.com/888886/46527551-4270af00-c89a-11e8-87ed-ecb8dbe9000e.gif)

**Comment by julienb81** [comment] 2018-10-05 09:35
@corevo Thanks for your example. The problem is at line 4. Will it be possible to resume at line 3 by example (without restarting the page)?

**Comment by corevo** [comment] 2018-10-05 09:41
At the moment what you can do, is after fixing line 4, if you want to execute line 3, you can do it by double clicking it, or by pressing "x", to execute it specifically.  
Going back is more complex, but telling the IDE, I want you to stop at line 4, and then manually executing the lines you wish is definitely possible.  
We could try to improve it, by maybe letting you specify a range of lines to execute.

**Comment by julienb81** [comment] 2018-10-05 10:08
@corevo Thanks for your explanation. I don't think I need a fonctionnality to specify a range of lines to execute. If I can double click to execute a line when the script is on pause, and resume the script after, I think it will be a good solution. What I see as an advantage is that it will keep my variables.

**Comment by FunkyAlex** [comment] 2018-10-05 10:36
I am suddenly experiencing the same issue having today updated to 3.4.0, i can't confirm the previous version installed but the same test /test suite was seen working fine earlier today. 
Browser: Firefox 62.0.3 (64-bit)
I can't get any test to run without it opening a new browser instance. This happens still after killing all firefox processes and starting fresh, opening the project, and trying to run the first test.

**Comment by saradhit** [comment] 2018-10-05 14:06
@corevo After the script was Paused On Exception and the error is fixed. As shown in your example, Clicking on either "Run Current Test" or "Resume Test Execution" is actually stopping test execution. Is the Hot fix pushed!!! Thanks for all your help.

**Comment by sagather2** [comment] 2018-10-05 18:33
@corevo - It sure seems that if the 'Execute this command' mouse option fires in the current window, then the 'Play from here' mouse option should do the same.  That way the IDE remains consistent with itself as it did in previous versions.

Also, I do like the idea of giving the option to run either from a new window, or from the existing window when starting test execution.  Thanks

**Comment by luquitia** [comment] 2018-10-08 20:02
This is also affecting me. I had a script working fine on Oct. 4, but with the new IDE version (3.4.0) on Oct. 5, the script failed (due to another problem) and **play from here** is not working.

The workaround to update the failed step while in "pause on exception" mode doesn't work well for my case, where I wanted to skip the offending steps and play the remainder of the script.  This is my preferred method when there's an automation issue, to at least use the IDE for partial automation with some manual steps.  But this doesn't work at all with the new "play from here" functionality (which basically doesn't work unless the current step happens to be an open command).

**Comment by olivierdemey** [comment] 2018-10-12 09:43
> Hi, i'm also having the issue. I'm clicking on "run current test" and an additional chrome tab opens with following text written : "Preparing to run your test". What can i do ?

ok so i have one piece of answer
my test case do NOT start with "open". They start with "click". It used to work ; selenium ide would just pick up the current opened tab. 
Now with the latest version it seems like i'm obliged to open the webpage ; but that i do not want... what is the workaround ??

**Comment by twnew** [comment] 2018-12-08 15:06
> Now with the latest version it seems like i'm obliged to open the webpage ; but that i do not want... what is the workaround ??

the "workaround" I am currently using is to use the _kantu_ selenium ide. In kantu, tests replay starts in [whatever tab is currently open](https://a9t9.com/kantu/docs/selenium-ide/open).

**Comment by darkartswizard** [comment] 2019-05-25 20:06
I see this ticket is marked as the duplicate for Closed Issue #440 - "playback on an existing open page".

I'll join the request to allow Selenium IDE the option to attach to an open browser tab and begin playback, rather than requiring a new browser to launch. This gives Selenium IDE as option to operate as a simple Macro solution tool, in addition to being a superior Object Spy and base JUNIT code generator.

REASONING: I have a current client - a non-programmer team - who could use SE IDE to automate about 50 frequently repeated steps as a Macro solution within an hour, if it allowed to execute after logging in with user credentials manually (See related feature request #707 Encrypt / decrypt recorded Passwords). This would be a quick-win for a client, before we start to spend days or weeks producing the equivalent Selenium / Gherkin / Glue code / Page Object model framework solution.

**Comment by tourdedave** [comment] 2019-08-29 07:43
We're going to change `Play from here` to use the existing window instead of opening a new one. 

But buyer beware, there is no guarantee this will work as you expect depending on a) how you've constructed your test (e.g., you could be running from a control flow command block which is non-deterministic) and b) the state of the application could have changed, which could lead to unintended results in your tests. If you end up in this situation, there's not much support we can offer. We don't recommend this command, but we also see it is useful to our users so we want to offer it in a way they're used to using it.

In the next major version of the IDE we'll also offer this functionality, but track what command you left off from and prompt you to confirm where you want to play from.

**Comment by saradhit** [comment] 2019-08-29 12:18
@tourdedave Hello, I have an update, I am using IDE V3.12.0 with Chrome V76.0.3809.100 (Official Build) (64-bit). When i used Play from here, If i am on the same screen where it failed/stopped, It is running the script in the same browser, it is not opening a new browser window.

**Comment by tourdedave** [comment] 2019-08-29 12:44
Ah, terrific. I've confirmed this as well. Closing.

**Closed by tourdedave** 2019-08-29 12:44 UTC
Labels: enhancement
