### ISSUE TITLE
Command of "verify text" doesn't support regular expression

### ISSUE THREAD

**Issue by JackJiaJJ** [SeleniumHQ/selenium-ide#721] opened 2019-06-17 08:47 UTC
## 🐛 Bug Report

I recorded a script which will verify text with regexp (regular expression), it can't work well

## To Reproduce

record a script, and then add below line:

Command: verify text
Target: id=scpl3
Value: regexp:[A-Za-z]ct

## Expected behavior

This step should be playbacked successfully

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

{
  "id": "2fd365a7-ab52-41cf-8ced-2a6961d3f8dd",
  "version": "2.0",
  "name": "linux-test",
  "url": "https://cn.bing.com",
  "tests": [{
    "id": "6449b7df-3667-4386-a5ae-5639bbeb942e",
    "name": "step-1-login",
    "commands": [{
      "id": "25ef67e3-f676-4174-9aaa-dbf1bf472a1c",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "c94171f4-4ad1-46b6-8651-7297492a4a93",
      "comment": "",
      "command": "verifyText",
      "target": "id=scpl3",
      "targets": [
        ["id=scpl3", "id"],
        ["linkText=Dict", "linkText"],
        ["css=#scpl3", "css:finder"],
        ["xpath=//a[contains(text(),'Dict')]", "xpath:link"],
        ["xpath=//a[@id='scpl3']", "xpath:attributes"],
        ["xpath=//li[@id='scpt3']/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/dict?FORM=Z9LH3')]", "xpath:href"],
        ["xpath=//li[4]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Dict')]", "xpath:innerText"]
      ],
      "value": "regexp:[A-Za-z]ct"
    }, {
      "id": "3ab4e378-1823-4be0-8c8b-4908487f595a",
      "comment": "",
      "command": "type",
      "target": "id=sb_form_q",
      "targets": [
        ["id=sb_form_q", "id"],
        ["name=q", "name"],
        ["css=#sb_form_q", "css:finder"],
        ["xpath=//input[@id='sb_form_q']", "xpath:attributes"],
        ["xpath=//form[@id='sb_form']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "linux"
    }, {
      "id": "34ff5851-8d78-46ef-8fc2-0705f1f564a2",
      "comment": "",
      "command": "sendKeys",
      "target": "id=sb_form_q",
      "targets": [
        ["id=sb_form_q", "id"],
        ["name=q", "name"],
        ["css=#sb_form_q", "css:finder"],
        ["xpath=//input[@id='sb_form_q']", "xpath:attributes"],
        ["xpath=//form[@id='sb_form']/div/input", "xpath:idRelative"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "${KEY_ENTER}"
    }]
  }, {
    "id": "e0a237b5-9661-4353-be07-9945d61ea78c",
    "name": "step-3-images",
    "commands": [{
      "id": "873d8577-51df-4ebd-ad17-af16bcda38fc",
      "comment": "",
      "command": "click",
      "target": "xpath=//a[contains(text(),'Images')]",
      "targets": [
        ["linkText=Images", "linkText"],
        ["css=.b_scopebar li:nth-child(2) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Images')]", "xpath:link"],
        ["xpath=//header[@id='b_header']/nav/ul/li[2]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/images/search?q=linux&FORM=HDRSC2')]", "xpath:href"],
        ["xpath=//li[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Images')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "4f780369-38fb-4166-940a-da47f1225ef3",
      "comment": "",
      "command": "close",
      "target": "",
      "targets": [],
      "value": ""
    }]
  }, {
    "id": "144d1dd2-ccf7-4933-99b3-3d9f20573b03",
    "name": "step-2-video",
    "commands": [{
      "id": "5477eed0-e8e2-433f-8803-009fde7dad59",
      "comment": "",
      "command": "pause",
      "target": "5000",
      "targets": [],
      "value": ""
    }, {
      "id": "b2d36c61-192d-4449-9e3b-1bc618bf29bb",
      "comment": "",
      "command": "click",
      "target": "xpath=//a[contains(text(),'Videos')]",
      "targets": [
        ["linkText=Videos", "linkText"],
        ["css=.b_scopebar li:nth-child(3) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Videos')]", "xpath:link"],
        ["xpath=//header[@id='b_header']/nav/ul/li[3]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/videos/search?q=linux&FORM=HDRSC3')]", "xpath:href"],
        ["xpath=//li[3]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Videos')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "0d1b364d-7c45-471c-9bc5-9a54c8f1ff18",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["6449b7df-3667-4386-a5ae-5639bbeb942e", "144d1dd2-ccf7-4933-99b3-3d9f20573b03", "e0a237b5-9661-4353-be07-9945d61ea78c"]
  }],
  "urls": ["https://cn.bing.com/"],
  "plugins": []
}

Issues without a reproduction project are likely to stall.

## Environment

OS: windows 7
Selenium IDE Version:  3.7.4
Selenium SIDE Runner Version:  not used, I don't know
Node version: not used, I don't know

Browser: firefox
Browser Version: 60.6.1 ESR (64-bit)

**Comment by corevo** [comment] 2019-06-17 08:59
Duplicate of #141

**Closed by corevo** 2019-06-17 08:59 UTC
