### ISSUE TITLE
Wildcards in assert text

### ISSUE THREAD

**Issue by pekko** [SeleniumHQ/selenium-ide#420] opened 2018-09-27 11:31 UTC
## 🚀 Feature Proposal

I'd like to be able to use wildcards (regexes totally fine) in `assert text` check.

## Motivation

Checking against exact values is sometimes difficult, and I might be interested only in partial value.

There seems to already exist https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/content/PatternMatcher.js , but it doesn't seem to be used. https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/neo/IO/playback/webdriver.js#L262 checks for equal match only.

**Comment by corevo** [comment] 2018-09-27 11:32
Duplicate of #141

**Closed by corevo** 2018-09-27 11:32 UTC
