### ISSUE TITLE
Is there a command to load files through a overlay?

### ISSUE THREAD

**Issue by QA1MTG** [SeleniumHQ/selenium-ide#219] opened 2018-05-30 16:38 UTC
Wording may be incorrect on the title of this
In the old selenium IDE, if I wanted to activate the uploading of a file via a web overlay modal, I could find the input field and type the path directly into the field
it would look something like this:
type //input[@class="upload-input"] /users/name/directory/file.xlsx
The command still works on Old IDE, but not in new IDE.  I receive the following error
Failed:
This locator type is unavailable with this command

Is there an easier way to set this up in the new Selenium?

**Comment by corevo** [comment] 2018-05-31 08:12
It is available, just not with `xpath` locators.  
Specifically when you upload files using `type` (not when you use it to normally `type`), you can't use `xpath`, because we are using a different engine than Selenium to execute that command.

**Comment by corevo** [comment] 2018-05-31 08:13
Duplicate of #120

**Closed by corevo** 2018-05-31 08:12 UTC
