### ISSUE TITLE
Add support for user-extensions.js and user-extensions-ide.js for users migrating from the old Selenium IDE

### ISSUE THREAD

**Issue by gwtuser** [SeleniumHQ/selenium-ide#184] opened 2018-05-03 17:26 UTC
Background:

We have a Framework that we advise customers to test using Selenium.  Since Selenium v3, when the user extensions have no longer been supported in the Selenium JARs, we've added an interpreter to our code that reads Selenese v1 scripts (with support for our user-extensions.js) and executes them against a wrapper we wrote around the Java WebDriver APIs.

Since Selenium IDE is a separate product from the Selenium JARs, we've been continuing to tell customers to use Selenium IDE (in FF52 ESR) to develop their scripts, or at least to capture locators, which they can then either use in WebDriver code (with our Java wrapper), or - if they want to actually run the Selenese - use our interpreter.

Problem:

We've been telling customers not to worry because although the old Selenium IDE is broken in current FF versions, a port is underway, but now it seems that user-extensions.js and user-extensions-ide.js are not supported in the new version, which is a showstopper for us.  Our special locators can only be supported through the use of these files.

My understanding is that some type of extension module will be supported - though not in such a simple way as providing those two files.  So would it be possible for us to write such an extension module that, in turn, allows users to plug in our old JS user extension files?

If there's an easy path to support this, then feel free to close this after pointing it out.  Otherwise, we'd like to request support for some way of plugging in the old user extensions.

**Comment by QA1MTG** [comment] 2018-05-04 14:35
I'm curious about this one as well

**Comment by corevo** [comment] 2018-05-04 16:01
Yes! We are building a plugin module for the IDE, the first release of it will enable adding new commands.  
But adding more locators is definitely on the list of things.  
I'll close this as it's a duplicate of #104

**Closed by corevo** 2018-05-04 16:01 UTC
