### ISSUE TITLE
Streamlined Save

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#415] opened 2018-09-26 11:49 UTC
## 🚀 Feature Proposal

Currently the "Save" button works like a "Save As" plus it downloads a file. It should just save the file silently.

## Motivation

The user should not have to re-choose the name and have a download appear below. This is standard UI behaviour. A "Save As" button could be added. No download file should appear.

**Comment by corevo** [comment] 2018-09-26 11:57
Duplicate of #363

**Closed by corevo** 2018-09-26 11:57 UTC

**Comment by cawoodm** [comment] 2018-09-28 06:55
It's kind of a duplicate but not really. I'm not asking for a "Save As", I'm asking for a simple Save.
I think you'll find this *is* possible with a Chrome Extension - you just have to ask the user for permission to access the file system. Checkout "chrome extension permissions" on google.

**Comment by corevo** [comment] 2018-09-28 09:11
There is no [filesystem permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#API_permissions)

**Comment by cawoodm** [comment] 2018-09-28 12:37
[There sure is](https://developer.chrome.com/apps/fileSystem).

**Comment by corevo** [comment] 2018-09-28 13:09
That is a Chrome App API, not a Chrome Extension API, you can read more about their differences [here](https://developer.chrome.com/webstore/apps_vs_extensions).  
List of Chrome Extensions APIs is [here](https://developer.chrome.com/extensions/declare_permissions), which only gives partial filesystem permissions on Chrome OS.  

Now let me be clear on something, if you think it is my intention to make Selenium IDE bad, and you think that I do not wish to have a comfortable save mechanism, then you are more than welcome send a pr, I'll be the first one to merge it, I promise you.

**Comment by corevo** [comment] 2018-09-28 17:08
I show the file dialog on purpose, because otherwise it'll download to the downloads directory, which I assume is **not** the intended location of the file.  
The problem with not showing the dialog, is that it will create the confusion of the user believing the file was saved, while in reality, it was downloaded, showing the dialog averts that confusion.

**Comment by cawoodm** [comment] 2018-09-28 18:04
So the button is explicitly a "Save As" and I don't work like that. I'm working for hours on the same project and I want to constantly save (Ctrl+S) and not have to each time select a location and confirm that I want to overwrite a file.

Not sure what confusion you are referring to: I click save and it saves. I see the download appear below which is annoying but cannot be avoided.

So pretty please make a nice, normal, silent Save button :-)
