### ISSUE TITLE
Cannot be saved in a normal format in chrome for win10

### ISSUE THREAD

**Issue by borsteinreports** [SeleniumHQ/selenium-ide#875] opened 2019-11-12 18:19 UTC
## 🐛 Bug Report

In Chrome on Win10, Selenium IDE save scripts without a suffix. This prevents the script from being imported again.

This is similar to issue #516 

## To Reproduce

1. Add the Chrome Extension MalewareBytes and enable it.
2. Open Selenium IDE
3. Start a New Project and enter in required information
4. Click Save.
5. Note that "Save as Type" will not have "*.side" as a selection.

## Expected behavior

When saving a project, a file save dialog is presented with the ability to save with a ".side" file extension

## Project file reproducing this issue (highly encouraged)

This problem occurs in the Selenium IDE, so no scripts are required for this problem

## Environment
OS: Windows 10
Selenium IDE Version:  3.15.1
Browser: Chrome
Browser Version: 78.0.3904.97

**Comment by tourdedave** [comment] 2019-12-02 07:31
The underlying problem causing issue #516 was fixed in `v3.15.0`.

If you disable MalwareBytes does the file extension issue go away? Please also provide the Chrome version you're running.

**Comment by borsteinreports** [comment] 2019-12-02 11:07
As stated in Environment section above, Chrome version at the time of the creation of this issue was 
Browser Version: 78.0.3904.97
Today, the browser version is
Browser Version: 78.0.3904.108

Correct, if I completely disable MalewareBytes extension, the file extension issue goes away.

**Comment by corevo** [comment] 2019-12-02 11:11
Then a conclusion could be made that MalwareBytes is tampering with Selenium IDE's save operation.

**Comment by borsteinreports** [comment] 2019-12-02 11:46
@corevo  Yes, I would agree with that.

The question is, without sacrificing security, what be done? Since the IDE opens without the tool bar, this is no way to control MalewareBytes just for the IDE, or any information about what is triggering MalewareBytes. It would be best if I didn't have to turn off security features to just use the IDE.

**Comment by corevo** [comment] 2019-12-02 13:52
Seems like its a problem with MalewareBytes, and you should contact them, we have no problems working with them, and giving them our extension identifiers for them to exclude.

But the problem is on their end, I suggest you contact them, and if they need information from us, we will be happy to provide.

**Closed by corevo** 2019-12-02 13:52 UTC
Labels: awaiting answer
