### ISSUE TITLE
Very annoying issue. If not automatic "save" after `Ctrl + S`, then at least path to my project should be remembered. Now I have to change folder anytime I press `Ctrl + S`. Folder` ~/Downloads` is offered instead of expected `~/selenium-ide` where the project is stored.

### ISSUE THREAD

**Issue by zzzxx8000** [SeleniumHQ/selenium-ide#1095] opened 2020-07-17 06:35 UTC
Very annoying issue. If not automatic "save" after `Ctrl + S`, then at least path to my project should be remembered. Now I have to change folder anytime I press `Ctrl + S`. Folder` ~/Downloads` is offered instead of expected `~/selenium-ide` where the project is stored.
I'm running Ubuntu 18.10

_Originally posted by @mirao in https://github.com/SeleniumHQ/selenium-ide/issues/363#issuecomment-467175306_

**Comment by corevo** [comment] 2020-07-17 17:34
Duplicate of #364

**Closed** 2020-07-17 17:34 UTC
