### ISSUE TITLE
Add support for "patterns" for text verification

### ISSUE THREAD

**Issue by JamesZoft** [SeleniumHQ/selenium-ide#141] opened 2018-04-05 13:04 UTC
Raising this after seeing another user talk about it.

The old IDE allowed regex in text verification steps (and possibly other places too) eg

verify text | target | you are the * User to log in today

This should be added to the new IDE as well to keep feature parity.

**Comment by 98gmarquee** [comment] 2018-04-05 23:53
That actual syntax worked? Ha!

I always used 2 xargs with something like 
`verifyElementPresent|target|//a@[starts-with(.,'you are the') and contains(.,'User to log in today')]`

**Comment by frankkienl** [comment] 2018-06-07 11:33
Having regex support in the IDE would be really helpful

**Comment by tourdedave** [comment] 2018-06-12 14:19
Per the old IDE spec:

```
Patterns are used for various reasons, e.g. to specify the expected value of an input field, or identify a select option. Selenium supports various types of pattern, including regular-expressions, all of which are described in more detail below.

String-match Patterns

Various Pattern syntaxes are available for matching string values:

glob:pattern: Match a string against a "glob" (aka "wildmat") pattern. "Glob" is a kind of limited regular-expression syntax typically used in command-line shells. In a glob pattern, "*" represents any sequence of characters, and "?" represents any single character. Glob patterns match against the entire string.
regexp:regexp: Match a string using a regular-expression. The full power of JavaScript regular-expressions is available.
regexpi:regexpi: Match a string using a case-insensitive regular-expression.
exact:string: Match a string exactly, verbatim, without any of that fancy wildcard stuff.
If no pattern prefix is specified, Selenium assumes that it's a "glob" pattern.

For commands that return multiple values (such as verifySelectOptions), the string being matched is a comma-separated list of the return values, where both commas and backslashes in the values are backslash-escaped. When providing a pattern, the optional matching syntax (i.e. glob, regexp, etc.) is specified once, as usual, at the beginning of the pattern.
```

**Comment by tourdedave** [comment] 2018-06-12 14:20
Once this gets implemented, we'll need to remember to update the documentation accordingly.

**Comment by AyaSF** [comment] 2018-06-16 10:20
Hi,
I have the same problem: the wildcard * is missing.
Thanks by advance for the improvment,
AyaSF

**Comment by stuart1975** [comment] 2018-06-21 16:55
Hi,
I am using Firefox Version 60.0.2 and Selenium IDE 3.0.30. Wildcards not working
I use command: "verify text" put in value field the following: 

glob:*items found* 
and got the following error message:

Actual value '2,480 items found, displaying 1 to 20.' did not match 'glob:*items found*'

**Comment by cinnest** [comment] 2018-08-22 09:52
Is there any workaround for it? I was wondering using the storeXpathCount and asserting the result of its variable. The problem is I don't know how I could assert the value of a variable. Does anybody know how to do it? Is it actually possible?

**Comment by tourdedave** [comment] 2018-08-22 10:05
@cinnest There's a generic `assert` command. You can use it to check a variable against an expected value.

**Comment by corevo** [comment] 2018-08-22 10:33
I'm thinking we can add `regex` pretty easily, I think that `glob` is the issue, since JavaScript doesn't have a default `glob` implementation, and I don't wanna bundle that with the runner.  
First off we can definitely add `regex`, globbing though, I see 2 solutions:
 - Bundle a globbing library with the runner
 - Convert globs to regexes in Selianize

\cc @tourdedave

**Comment by cinnest** [comment] 2018-08-22 12:57
@tourdedave Sorry for deleting my post. I've realized @98gmarquee had already mentioned a workaround and therefore I though me question was not relevant. It is nice tough knowing that with the assert I could indeed verify a variable. thanks

**Comment by VChris1975** [comment] 2018-09-05 13:27
I'm trying Selenium IDE 3 Chrome plugin for some days. It's a great and powerful tool, but I am unable to perform the most important test... How to test if a piece of text is present inside a div? 
* character as wildcar not working in verify text, assert text, etc... There is no verify text present command.
I was trying everything but I am unable to find out a solution? 
Why there is no substring, or * as wildcard, or a command to check a text exist somewhere on the page or inside a div?
Or if there is a solution, can somebody help me how to perform it step by step?
Selenium IDE 3.x

**Comment by cinnest** [comment] 2018-09-06 09:52
@VChris1975 I was facing a similar issue and it took me a while 'til I realize @98gmarquee had already given a solution for that: with the use of xpath and the `verifyElementPresent ` you can check if a given element contains a string. In my case I was verifying the presence of a string in a table, so I solve the problem with the following command:

```
{
      "id": "90ab24b6-959a-4a98-9ef1-652bfd01c64b",
      "comment": "",
      "command": "verifyElementPresent",
      "target": "xpath=(//table[contains(.,${myString})])",
      "targets": [],
      "value": ""
    }
```
I guess you could use this solution too...

**Comment by VChris1975** [comment] 2018-09-06 20:10
@cinnest : thanks for your reply! I understand the logic, it's a very clever solution. Nice :)

**Comment by saca-puntas** [comment] 2018-12-13 21:09
Hi, I'm still new to GitHub-- does the fact that this issue is still open mean that adding wildcard support is still something that is planned to be done? None of the workarounds work for my scenario and there are many places I used a wildcard in the old version that makes it really valuable to me.

**Comment by 98gmarquee** [comment] 2018-12-14 00:37
I hope it's still on the cards to do. I really could have used it today... after stringing together 7 contains(.,'stuff') to verify many sentences on various pages. Stupid things had tabs and new lines in them and I couldn't get a direct text match.

**Comment by corevo** [comment] 2019-01-09 18:46
Yes, this issue is open, and we'll get to it eventually, if someone wishes to contribute we'd love the help.

**Comment by jdelapp42** [comment] 2019-05-01 08:27
Thank you @98gmarquee for this. I'm in the process of taking the CP-SAT certification course, and I was stuck almost out of the gate because the training still relies on regexp being available.

**Comment by adminphdcommy** [comment] 2019-05-14 03:02
Anyone has any code sample for the pattern or regex use case?

**Comment by 98gmarquee** [comment] 2019-05-14 06:24
> 
> 
> Anyone has any code sample for the pattern or regex use case?

You can use what I posted above I think:
https://github.com/SeleniumHQ/selenium-ide/issues/141#issuecomment-379110085

**Comment by tourdedave** [comment] 2019-06-23 12:48
I've updated the FAQ with the workaround using xpath ([link](https://www.seleniumhq.org/selenium-ide/docs/en/introduction/faq/#how-can-i-use-regex-in-text-verifications).

**Comment by radicalbender** [comment] 2019-12-02 15:59
The example provided in the FAQ does not appear to be working. I've tried multiple things, but every use of the syntax (including the example verbatim) is returning:

`Unable to locate an element with the xpath expression //a@[starts-with(.,'you are the') and contains(.,'User to log in today')] because of the following error: SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//a@[starts-with(.,'you are the') and contains(.,'User to log in today')]' is not a valid XPath expression.`

Has something changed? Or am I doing something incorrectly? This is not working for me using assert element present or verify element present.

**Comment by 98gmarquee** [comment] 2019-12-04 04:58
There was an error in my comment before, remove the @ after the //a
`//a**@**[starts-with(.,'you are the') and contains(.,'User to log in today')]`

should be:
//a[starts-with(.,'you are the') and contains(.,'User to log in today')]`

Similar test done on the google home page trying to locate the "Google Search" button:
`//input[starts-with(@value,'Google')  and contains(@value,'earch')]`

Vs having the @ in it which is an invalid xpath
`//input**@**[starts-with(@value,'Google')  and contains(@value,'earch')]`

**Comment by dlpnd** [comment] 2020-08-25 22:39
This workaround works for matching the elements, however what if I want to confirm that the text I get back, a specific part of it should not have decimal points. With regexp I could do something like (Total: )(\d)+

**Comment by nomis51** [comment] 2020-08-27 13:50
> This workaround works for matching the elements, however what if I want to confirm that the text I get back, a specific part of it should not have decimal points. With regexp I could do something like (Total: )(\d)+
> 
> Workaround for me was:
> 
> 1. Store text of element I want to check
> 2. execute script: if (${test}.match(/(Total: )(\d)+$/)) { return true; } else { return false };, store this value as x
> 3. Assert x === true
> 
> ![image](https://user-images.githubusercontent.com/11916166/91235452-b0256d00-e789-11ea-92bc-bd460ae59b87.png)

Works like a charm! Thanks!

**Comment by SalvadorRichter** [comment] 2020-09-23 12:35
> This workaround works for matching the elements, however what if I want to confirm that the text I get back, a specific part of it should not have decimal points. With regexp I could do something like (Total: )(\d)+
> 
> Workaround for me was:
> 
> 1. Store text of element I want to check
> 2. execute script: if (${test}.match(/(Total: )(\d)+$/)) { return true; } else { return false };, store this value as x
> 3. Assert x === true
> 
> ![image](https://user-images.githubusercontent.com/11916166/91235452-b0256d00-e789-11ea-92bc-bd460ae59b87.png)

Works with text finding as well, awesome!
I just changed the script line to: 
if (${test}.startsWith('my simple text')) { return true; } else { return false };

**Comment by toddtarsi** [comment] 2022-11-10 05:34
Closing this, v3 will be taken down from stores soon anyway. Maybe in v4!

**Closed by toddtarsi** 2022-11-10 05:34 UTC
Labels: enhancement
