### ISSUE TITLE
Option to disable hove action on sidebar

### ISSUE THREAD

**Issue by setiseta** [SeleniumHQ/selenium-ide#507] opened 2018-11-27 12:36 UTC
## 🚀 Feature Proposal

The UI is very nervous because of the hover action on the sidebar.
It would be nice if it is possible to disable the hover action.
And maybe remove the limits on the sidebar width.

## Motivation

Improve the new selenium ide

**Comment by tourdedave** [comment] 2018-11-27 12:40
This is a duplicate of #419

**Closed by tourdedave** 2018-11-27 12:40 UTC

**Comment by setiseta** [comment] 2018-11-27 12:41
oh sorry, haven't seen this one. thanks for information

**Comment by tourdedave** [comment] 2018-11-27 13:00
No worries. You're welcome!
