### ISSUE TITLE
Something is wrong with the selenium-side-runner when running dockerfile

### ISSUE THREAD

**Issue by cemol** [SeleniumHQ/selenium-ide#303] opened 2018-07-13 11:23 UTC
## Meta -
OS: Windows 10 (ubuntu in dockerfile)
Selenium IDE Version: v3.2.0-beta.1
Selenium SIDE Runner Version: 3.2.0-beta.1
Node version: npm: 5.6.0, node: v8.11.3
Browser: Chrome

Browser Version:  

## Expected Behavior -
The selenium-side-runner workes fine in Windows 10 with the command:
> selenium-side-runner -c chromeOptions.args=[headless] project.side

CMD in dockerfile:
> CMD ["selenium-side-runner", "-c", "chromeOptions.args=[headless]", "/tmp/project.side"]

But when I run the dockerfile I get this error:

> `fs.js:675
>   return binding.read(fd, buffer, offset, length, position);
>                  ^
> 
> Error: EISDIR: illegal operation on a directory, read
>     at Object.fs.readSync (fs.js:675:18)
>     at tryReadSync (fs.js:540:20)
>     at Object.fs.readFileSync (fs.js:583:19)
>     at _commander2.default.args.map.p (/usr/local/lib/node_modules/selenium-side-runner/dist/index.js:196:76)
>     at Array.map (<anonymous>)
>     at Object.<anonymous> (/usr/local/lib/node_modules/selenium-side-runner/dist/index.js:196:43)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
> `

Is there something I am doing wrong? Or is it a bug in selenium-side-runner?

**Comment by corevo** [comment] 2018-07-13 13:30
Can you post the Dockerfile?

**Comment by cemol** [comment] 2018-07-13 13:53
> FROM ubuntu
> 
> RUN apt-get update
> RUN apt-get install -y npm
> RUN npm install selenium-side-runner@beta -g
> RUN apt-get -yqq install ca-certificates sudo unzip wget 
> 
> RUN npm install chromedriver -g
> RUN wget -N https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
> RUN unzip ~/chromedriver_linux64.zip -d ~/
> RUN rm ~/chromedriver_linux64.zip
> RUN sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
> RUN sudo chown root:root /usr/local/bin/chromedriver
> RUN sudo chmod 0755 /usr/local/bin/chromedriver
> ENV PATH="/usr/local/bin/chromedriver:${PATH}"
> 
> CMD ["selenium-side-runner", "-c", "chromeOptions.args=[headless]", "/tmp/project.side"]

**Comment by corevo** [comment] 2018-07-13 13:57
And how do you set the `/tmp` volume?

**Comment by cemol** [comment] 2018-07-13 14:00
when running the dockerfile:

> docker run -v c:\Users\path:/tmp/project.side <image name>

**Comment by cemol** [comment] 2018-07-16 08:37
Any clues of what could be wrong?

**Comment by corevo** [comment] 2018-07-16 09:49
I'll need to find time to check that, but it seems likely to me that the issue is with the Dockerfile rather than the `runner`.  
Since the error is trying to access a directory, which signals to me that the runner lacks the required permissions inside the container.

**Comment by corevo** [comment] 2018-07-16 09:50
I think that your mount is incorrect, you mount a directory not a file, try mounting a directory containing the `side` file to the container's home directory.  
The permissions inside `/tmp` are sticky!

**Comment by cemol** [comment] 2018-07-16 11:21
I tried both:

> docker run -v c:\path\to\directory_containing_side_files:/project.side image_name
> docker run -v c:/path/to/directory_containing_side_files:/project.side image_name

and changed the docker file cmd to:

> CMD ["selenium-side-runner", "-c", "chromeOptions.args=[headless]", "/project.side"]

but i still get the same error message :/

**Comment by cemol** [comment] 2018-07-16 11:23
Thanks!! I worked :) with mounting the directory

**Comment by cemol** [comment] 2018-07-16 11:30
This is the error I get:

`FAIL ./Default Suite.test.js
  ● Test suite failed to run

    Server terminated early with status 127

      at earlyTermination.catch.e (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/remote/index.js:252:52)
      From: Task: WebDriver.createSession()
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:642:16)
      at buildDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.221s
Ran all test suites.`

**Comment by corevo** [comment] 2018-07-16 14:06
This seems like a problem with the container's java setup rather than the `runner`, from a quick look it seems like a faulty installation of `jre`.

**Comment by cemol** [comment] 2018-07-17 06:43
Thank you so much for all your help, I appreciate that very much!
You where correct, there was something wrong with the java-path.

This time I get a new error.. What could be wrong with the Chrome binary? Is it not included in the chromedriver?

This is the error I got:

```
FAIL ./Default Suite.test.js
  ● Test suite failed to run

    WebDriverError: unknown error: cannot find Chrome binary
      (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.93-linuxkit-aufs x86_64)

      at Object.checkLegacyResponse (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.createSession()
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:642:16)
      at buildDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.287s
Ran all test suites.
```



The updated dockefile is:

```
RUN apt-get update
RUN apt-get install -y npm
RUN npm install selenium-side-runner@beta -g
RUN apt-get -yqq install ca-certificates sudo unzip wget 

RUN apt-get update && \
	apt-get install -y openjdk-8-jdk && \
	apt-get install -y ant && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/oracle-jdk8-installer;
	
RUN apt-get update && \
	apt-get install -y ca-certificates-java && \
	apt-get clean && \
	update-ca-certificates -f && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/oracle-jdk8-installer;

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

RUN wget -N https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
RUN unzip ~/chromedriver_linux64.zip -d ~/
RUN rm ~/chromedriver_linux64.zip
RUN sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
RUN sudo chown root:root /usr/local/bin/chromedriver
RUN sudo chmod 0755 /usr/local/bin/chromedriver
ENV PATH="/usr/local/bin/chromedriver:${PATH}"

CMD ["selenium-side-runner", "-c", "chromeOptions.args=[headless]", "/tests/project.side"]
```

**Comment by corevo** [comment] 2018-07-17 06:57
No, you have to install Chrome separately from `chromedriver`

**Comment by cemol** [comment] 2018-07-17 07:29
Ok, how do you install chrome trought dockerfile? 

I tried both of this options:

```
# Install Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
```
and 

```
# Set the Chrome repo.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

# Install Chrome.
RUN apt-get update && apt-get -y install google-chrome-stable
```


but nothing worked :/

**Comment by cemol** [comment] 2018-07-17 08:08
With this new insert-change in the dockerfile:

```
# Install chrome browser
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
RUN apt update
RUN apt install google-chrome-stable -y
```

I got this error:

```
FAIL ./Default Suite.test.js
  ● Test suite failed to run

    WebDriverError: unknown error: DevToolsActivePort file doesn't exist
      (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.93-linuxkit-aufs x86_64)

      at Object.checkLegacyResponse (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:441:30)
      From: Task: WebDriver.createSession()
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:642:16)
      at buildDriver (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:52:17)
      at WebdriverEnvironment.setup (../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        60.42s
Ran all test suites.

```

What is the correct way to install chrome brwoser in dockerfile?

**Comment by corevo** [comment] 2018-07-17 08:09
That's not a question to ask here, you should consult either docker help forums, chrome or ubuntu.  
I'm closing the issue, unless after the setup there is an issue directly concerning the runner.

**Closed by corevo** 2018-07-17 08:09 UTC

**Comment by caractacus** [comment] 2019-07-22 16:45
Headless from Chrome 75:

selenium-side-runner -c "goog:chromeOptions.args=[--headless,--nogpu] browserName=chrome"
