### ISSUE TITLE
[feature request] Locator builders

### ISSUE THREAD

**Issue by Enrico9009** [SeleniumHQ/selenium-ide#134] opened 2018-03-22 16:05 UTC
In the older version of Selenium IDE, we had the possibility to add locators in Options-->Options-->Locator Builders through a .js extension file.

Is this features planned for the new Selenium IDE ?

Thank you.

**Comment by jeremybramwell** [comment] 2018-03-22 21:32
I think this is a duplicate of #104

**Comment by corevo** [comment] 2018-03-28 20:07
Indeed, closing at it is a duplicate of #104

**Closed by corevo** 2018-03-28 20:07 UTC
