### ISSUE TITLE
How to migrate: captureEntirePageScreenshot from Selenium IDE 2.9.1?

### ISSUE THREAD

**Issue by OleanderRose** [SeleniumHQ/selenium-ide#622] opened 2019-03-18 08:39 UTC
How can I migrate the command captureEntirePageScreenshot to Selenium IDE 3?

**Comment by corevo** [comment] 2019-03-18 08:42
Duplicate of #182 
Also please follow the issue template, subsequent issues will be closed.

**Closed by corevo** 2019-03-18 08:42 UTC
