### ISSUE TITLE
"sendKeys" ${KEY_ENTER} is mishandled at certain cases

### ISSUE THREAD

**Issue by ldthieu** [SeleniumHQ/selenium-ide#151] opened 2018-04-15 09:42 UTC
Tks for a great tools, It is very helpful to me! 
But I have a issue with Selenium IDE plugin for Chrome.
Chrome version: 65.0.3325.181
Selenium IDE version: 3.0.1

![issuse](https://user-images.githubusercontent.com/33156507/38776800-333d3e28-40c7-11e8-9fae-19247ce51f3f.png)

i record a test case for sign in google account by Selenium IDE . When i run test case, Selenium IDE said me that "Trying to execute sendKeys on id=identifierId with value ${KEY_ENTER}... Success" but it is not executed in browser

**Comment by corevo** [comment] 2018-04-15 09:57
Can you upload the `.side` file?

**Comment by corevo** [comment] 2018-05-22 08:54
It seems to be an issue with this specific form.  
The `enter` key is sent, but the form doesn't process it correctly.

**Comment by saradhit** [comment] 2018-06-26 14:06
I am not sure what exactly the issue is, But i think the issue is with the "send Keys", I am actually sending a value to pick a drop down item and then sending ${KEY_ENTER}. This was working perfectly in IDE 2.9.1 on the same drop down and form. But now it is sending the value on some drop down, but Enter is not working. Hope this might help whoever resolving the issue.

**Comment by corevo** [comment] 2018-09-05 10:15
Fixed for Chrome only (ac5596193554a5ba5d57b580f4b603d7bee28f71).  
Explanation on why it isn't fixed for Firefox is available [here](https://github.com/SeleniumHQ/selenium-ide/issues/362#issuecomment-418677591).

**Closed by corevo** 2018-09-05 10:15 UTC
Labels: help wanted, selenium api
