### ISSUE TITLE
side runner not starting

### ISSUE THREAD

**Issue by rafael844** [SeleniumHQ/selenium-ide#288] opened 2018-07-07 16:37 UTC
OS:  
 Windows 7 
Selenium IDE Version:  
 3.1.1.0 
Selenium SIDE Runner Version:  
selenium-side-runner-win.exe
v3.1.0-beta.4 
v.3.1.0-beta3

Browser:  
FF
Browser Version:  
61.0.1 (64-bit)

My testcases.side project
```

{
  "id": "f82518c9-0e36-49d1-be89-358c991bfcf3",
  "name": "Untitled Project",
  "url": "https://www.google.com.br",
  "tests": [{
    "id": "10fbdbcc-839b-44ce-b161-27612c33bba2",
    "name": "test1",
    "commands": [{
      "id": "65c592f3-0d66-4a09-9f1b-3840c64e1757",
      "comment": "",
      "command": "open",
      "target": "/",
      "value": ""
    }, {
      "id": "1db71646-24da-4c02-ad97-61a3271590e2",
      "comment": "",
      "command": "clickAt",
      "target": "id=lst-ib",
      "value": "182,25"
    }, {
      "id": "a16fc8b6-00a5-4366-9499-eb16450c5069",
      "comment": "",
      "command": "type",
      "target": "id=lst-ib",
      "value": "selenium"
    }, {
      "id": "f96210ce-73b5-4433-89fc-22f9b1c9cc46",
      "comment": "",
      "command": "sendKeys",
      "target": "id=lst-ib",
      "value": "${KEY_ENTER}"
    }, {
      "id": "5eb350c0-38f5-4211-ab7e-c6a3d0a8d741",
      "comment": "",
      "command": "clickAt",
      "target": "css=div.srg > div.g > div > div.rc > h3.r > a",
      "value": "188,5"
    }, {
      "id": "f9cae899-f275-41b3-82d1-fd110fd378d6",
      "comment": "",
      "command": "clickAt",
      "target": "//a[contains(text(),'Learn more about sponsorship')]",
      "value": "37,6"
    }]
  }],
  "suites": [{
    "id": "045780d7-1455-407f-aa14-1c8afa1d7cf3",
    "name": "Default Suite",
    "parallel": false,
    "timeout": 300,
    "tests": ["10fbdbcc-839b-44ce-b161-27612c33bba2"]
  }],
  "urls": ["https://www.google.com.br/"],
  "plugins": [],
  "version": "1.0"
}
```

Tried to run the side runner but not happens
beta7
v3.1.0-beta.4

C:\teste>selenium-side-runner-win.exe testcases.side
error:   The project Untitled Project is of older format, open and save it again
 using the IDE.

v3.1.0-beta.3

C:\teste>selenium-side-runner-win.exe testcases.side
C:\snapshot\selenium-ide\packages\selenium-side-runner\dist\index.js:101
  Object.keys(project.code).forEach(suite => {
         ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at runProject (C:\snapshot\selenium-ide\packages\selenium-side-runner\dist\i
ndex.js:101:10)
    at runAll (C:\snapshot\selenium-ide\packages\selenium-side-runner\dist\index
.js:114:10)
    at Object.<anonymous> (C:\snapshot\selenium-ide\packages\selenium-side-runne
r\dist\index.js:122:1)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:650:10)
    at Module.load (module.js:558:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1298:12)

and if I play it again...
C:\teste>selenium-side-runner-win.exe testcases.side
fs.js:905
  return binding.mkdir(pathModule.toNamespacedPath(path),
                 ^

Error: EEXIST: file already exists, mkdir 'C:\teste\side-suite-Untitled Project'

    at Object.fs.mkdirSync (fs.js:905:18)
    at runProject (C:\snapshot\selenium-ide\packages\selenium-side-runner\dist\i
ndex.js:95:16)
    at runAll (C:\snapshot\selenium-ide\packages\selenium-side-runner\dist\index
.js:114:10)
    at Object.<anonymous> (C:\snapshot\selenium-ide\packages\selenium-side-runne
r\dist\index.js:122:1)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:650:10)
    at Module.load (module.js:558:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1298:12)

Am I doing something wrong??

**Comment by corevo** [comment] 2018-07-08 08:32
Duplicate of https://github.com/SeleniumHQ/selenium-ide/issues/212#issuecomment-401753630

**Closed by corevo** 2018-07-08 08:32 UTC
