### ISSUE TITLE
Stop auto-resizing the navigation

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#468] opened 2018-10-26 06:58 UTC
The left hand navigation resizes everytime you mouse over it to no obvious benefit and much frustration. No matter what size you make it, it wants to expand and shrink each time it is moused over or off. Please stop this as, for one thing, it makes the user "miss" clicking a button:

![image](https://user-images.githubusercontent.com/498834/47549713-34440a80-d8fd-11e8-9bd9-c9cc60093a4f.png)

Buttons have now moved:
![image](https://user-images.githubusercontent.com/498834/47549742-44f48080-d8fd-11e8-86bb-00ee7a262127.png)

**Comment by corevo** [comment] 2018-10-26 07:58
This is not the first time it confuses someone, we will definitely take a look, for the time being if you retract the menu to it's thinnest size, it will not expand when you hover it.

**Comment by giznaj** [comment] 2018-10-27 02:13
@corevo - Yes, this is what I was telling you about earlier.  I am just getting used to it now, but you really see it when you have windows beside each other and do split screen (1/2 browser, 1/2 IDE).

**Comment by tourdedave** [comment] 2018-11-14 09:46
Duplicate of #419

**Closed by tourdedave** 2018-11-14 09:46 UTC
Labels: duplicate
