### ISSUE TITLE
Permission denied to access property "document" on cross-origin object

### ISSUE THREAD

**Issue by drexlma** [SeleniumHQ/selenium-ide#103] opened 2018-02-21 13:50 UTC
rying to execute assertText on css=div.notice.success > div with value *storniert*... Failed:
Permission denied to access property "document" on cross-origin object

**Comment by corevo** [comment] 2018-02-21 13:55
I'm gonna have to see the source, to be able to reproduce this,  
But my suspicion is that it's a [duplicate of this](https://github.com/SeleniumHQ/selenium-ide/issues/65#issuecomment-352354097).  
For the time being I'll close this unless you provide me with sources that would indicate a different issue.

**Closed by corevo** 2018-02-21 13:55 UTC
