### ISSUE TITLE
"Save" acts as "Save as"- Downloads a new file every single time you save a test case.

### ISSUE THREAD

**Issue by dinbtechit** [SeleniumHQ/selenium-ide#315] opened 2018-07-24 00:48 UTC
## Meta -
OS:  Windows 10
Selenium IDE Version:  3.1.0
Selenium SIDE Runner Version:  N/A
Node version:  N/A
Browser:  Chrome
Browser Version:  Version 67.0.3396.99 (Official Build) (64-bit)

## Expected Behavior -
Should override the saved .side file for consecutive saves.
## Actual Behavior -
Prompts to save the test case/test suite as a new file every single time, even if the test case was already saved. And it cant seems to remember the path of the previously save  .side file.
## Steps to reproduce -
1. Record a test case.
2. Save the .side file in some location.
3. Make some changes to the test case.
4. Save the test case. Now it would try to save the test case as a new file rather than appending the existing file.

**Comment by corevo** [comment] 2018-07-24 07:13
Duplicate of #116 #236

**Closed by corevo** 2018-07-24 07:13 UTC
Labels: duplicate
