### ISSUE TITLE
Stop button doesn't end debug session

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#518] opened 2018-12-10 10:31 UTC
When running a test with "pause on exceptions" the IDE will pause if an error occurs and say "Paused in debugger". If you then press "Stop" nothing happens, you remain in the debug session. I would expect the session to end.

![image](https://user-images.githubusercontent.com/498834/49726770-0cbbbe00-fc6f-11e8-86b8-2082164922d3.png)

Workaround: click "Pause" and it stops the session.

**Comment by corevo** [comment] 2018-12-10 11:45
Please use the issue templates, as it tells us which version you use and other useful metadata.  
Since I do not have that information, I've tried with the version I have at hand, and stop kills the session as expected.

**Comment by corevo** [comment] 2018-12-10 11:58
Closing until all additional information is given.

**Comment by cawoodm** [comment] 2019-01-30 07:58
I was just about to report this issue again and see that you closed it. That is indeed strange as the issue is plain to reproduce and it has nothing to do with the platform. Nevertheless here is the information:

## Environment

OS: 10
Selenium IDE Version:  3.5.3
Browser Version: Chrome 70

**Comment by tourdedave** [comment] 2019-01-30 08:06
What version of MacOS 10?

Can you try it with the latest version of Chrome (72.x.x).

**Comment by tourdedave** [comment] 2019-01-30 08:16
@cawoodm For context -- we ask for the metadata for a reason. Issues can present in one OS and not another, or in one browser and not another for various reasons. Just because you are experiencing the issue does not mean it's broken for everyone and easy to reproduce.

**Comment by tourdedave** [comment] 2019-09-01 12:40
Is this still a problem?

**Comment by toddtarsi** [comment] 2022-11-14 00:23
Closing this, no activity in 3 years and we're worrying about v4 now.

**Closed by toddtarsi** 2022-11-14 00:23 UTC
Labels: reproducer required
