### ISSUE TITLE
Wait Options

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#414] opened 2018-09-26 06:31 UTC
Sometimes when a button is clicked we want Selenium to wait for a page reload, sometimes not (e.g. XHR). There is a `pause` command but we would need:

* `wait for element`
* `wait for page reload`

**Comment by corevo** [comment] 2018-09-26 07:11
It is a duplicate of multiple tickets filed before, I won't go finding them, there are plenty, but here is the gist of it:
 - in the next version `wait for element present` and it's opposite, along side other 4 wait commands will be added.
 - `wait for page to load` is waited upon implicitly, if there is a case where it fails, file it as a bug and we'll see what can be done about that.

**Closed by corevo** 2018-09-26 07:11 UTC
