### ISSUE TITLE
selenium-side-driver 4.0.0-alpha.15 fails with error '`.each` called with an empty Array of table data'

### ISSUE THREAD

**Issue by balimoon777** [SeleniumHQ/selenium-ide#1535] opened 2022-10-10 18:27 UTC
## 🐛 Bug Report

selenium-side-driver 4.0.0-alpha.15 fails with error '`.each` called with an empty Array of table data'
It works fine with selenium-side-driver v3.17.0

## To Reproduce

Run concurrent tests from command line: 
selenium-side-runner --filter="happy" demo_project.side

Output:
 FAIL  ../../../../../../../usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js
  Running project demo_project
    Running suite unhappy_suite
      ✕ Running test $name
    Running suite happy_suite
      ✕ Running test $name (1 ms)

  ● Running project demo_project › Running suite unhappy_suite › Running test $name

    Error: `.each` called with an empty Array of table data.

      at testConcurrent (node_modules/jest-each/build/index.js:44:58)
      at src/main.test.ts:98:7
          at Array.forEach (<anonymous>)
      at src/main.test.ts:89:18

  ● Running project demo_project › Running suite happy_suite › Running test $name

    Error: `.each` called with an empty Array of table data.

      at testConcurrent (node_modules/jest-each/build/index.js:44:58)
      at src/main.test.ts:98:7
          at Array.forEach (<anonymous>)
      at src/main.test.ts:89:18

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        2.025 s
Ran all test suites within paths "/usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js".

## Expected behavior

Tests are executed concurrently and successfully,

## Project file reproducing this issue (highly encouraged)

{
  "id": "ff444a72-afd5-4db8-a6a4-e8c91aa337b8",
  "version": "2.0",
  "name": "demo_project",
  "url": "https://myurl",
  "tests": [{
    "id": "7f5a28ab-ac08-48eb-a03e-567f149d75e6",
    "name": "invalid_credential",
    "commands": [{
      "id": "e2913f17-fb0e-4101-b8a3-f7db8b48d95d",
      "comment": "",
      "command": "run",
      "target": "st_global_vars",
      "targets": [],
      "value": ""
    }, {
      "id": "4fdf9e65-0342-4294-8375-4edf590e1431",
      "comment": "",
      "command": "store",
      "target": "${invalid_username}",
      "targets": [],
      "value": "username"
    }, {
      "id": "35464d76-ee2f-4abb-8eec-71945d7f9a56",
      "comment": "",
      "command": "store",
      "target": "${invalid_password}",
      "targets": [],
      "value": "password"
    }, {
      "id": "e63b23ea-fc41-4065-9e99-9e18e9b4e64f",
      "comment": "",
      "command": "run",
      "target": "st_login",
      "targets": [],
      "value": ""
    }, {
      "id": "7f13d472-e936-4577-92a1-ab82de683be4",
      "comment": "",
      "command": "click",
      "target": "css=.btn",
      "targets": [
        ["css=.btn", "css:finder"],
        ["xpath=//button[@type='submit']", "xpath:attributes"],
        ["xpath=//div[4]/div/button", "xpath:position"],
        ["xpath=//button[contains(.,'Login')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "b6720496-e0da-4541-b41f-8397e939d9ae",
      "comment": "",
      "command": "assertText",
      "target": "css=.alert:nth-child(2) > span",
      "targets": [
        ["css=.alert:nth-child(2) > span", "css:finder"],
        ["xpath=//div[2]/span", "xpath:position"],
        ["xpath=//span[contains(.,'Sorry, we were not able to find a user with that username and password.')]", "xpath:innerText"]
      ],
      "value": "Sorry, we were not able to find a user with that username and password."
    }]
  }, {
    "id": "6ec401fb-d842-400f-aca0-d08d3c84f69b",
    "name": "st_logout",
    "commands": [{
      "id": "a6f67084-5419-4d40-a79c-40369a8247fa",
      "comment": "",
      "command": "click",
      "target": "css=.dropdown-toggle > .svicon2-admin",
      "targets": [
        ["css=.dropdown-toggle > .svicon2-admin", "css:finder"],
        ["xpath=//ul[@id='topRightDropDown']/li/a/span", "xpath:idRelative"],
        ["xpath=//div[2]/ul/li/a/span", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "14054902-b81d-4ed6-953d-8b7bfeb49d88",
      "comment": "",
      "command": "click",
      "target": "css=.dropdown-toggle > .svicon2-admin",
      "targets": [
        ["css=.dropdown-toggle > .svicon2-admin", "css:finder"],
        ["xpath=//ul[@id='topRightDropDown']/li/a/span", "xpath:idRelative"],
        ["xpath=//div[2]/ul/li/a/span", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "1caf976c-2d46-455e-9530-2d33cf411d4e",
      "comment": "",
      "command": "click",
      "target": "linkText=Log Out",
      "targets": [
        ["linkText=Log Out", "linkText"],
        ["css=.dropdown-menu:nth-child(2) > li:nth-child(4) > a", "css:finder"],
        ["xpath=//a[contains(text(),'Log Out')]", "xpath:link"],
        ["xpath=//ul[@id='topRightDropDown']/li/ul/li[3]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/ECM/j_spring_security_logout')]", "xpath:href"],
        ["xpath=//li/ul/li[3]/a", "xpath:position"],
        ["xpath=//a[contains(.,' Log Out')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }, {
    "id": "f18ccca7-8532-41d7-8ffa-65d45f790808",
    "name": "st_login",
    "commands": [{
      "id": "1f8538cb-c58a-43e5-af53-326a52c01d77",
      "comment": "",
      "command": "open",
      "target": "/ECM/login/auth",
      "targets": [],
      "value": ""
    }, {
      "id": "80580b97-ea91-4bff-9629-c7b9e984ff30",
      "comment": "",
      "command": "setWindowSize",
      "target": "1287x767",
      "targets": [],
      "value": ""
    }, {
      "id": "45373104-2a0b-4827-95cc-85968c0cb07f",
      "comment": "",
      "command": "click",
      "target": "id=username",
      "targets": [
        ["id=username", "id"],
        ["name=j_username", "name"],
        ["css=#username", "css:finder"],
        ["xpath=//input[@id='username']", "xpath:attributes"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "bc94838a-08f0-4b60-892e-6e64f03c103c",
      "comment": "",
      "command": "type",
      "target": "id=username",
      "targets": [
        ["id=username", "id"],
        ["name=j_username", "name"],
        ["css=#username", "css:finder"],
        ["xpath=//input[@id='username']", "xpath:attributes"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "${username}"
    }, {
      "id": "d6534a0e-40c9-4a9d-aa6a-d4ec6c8e6398",
      "comment": "",
      "command": "click",
      "target": "name=j_password",
      "targets": [
        ["name=j_password", "name"],
        ["css=.form-label-group:nth-child(3) > .form-control", "css:finder"],
        ["xpath=//input[@name='j_password']", "xpath:attributes"],
        ["xpath=//div[3]/input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "d51fd8af-89a8-4aa3-b9b4-eca57a56c775",
      "comment": "",
      "command": "type",
      "target": "name=j_password",
      "targets": [
        ["name=j_password", "name"],
        ["css=.form-label-group:nth-child(3) > .form-control", "css:finder"],
        ["xpath=//input[@name='j_password']", "xpath:attributes"],
        ["xpath=//div[3]/input", "xpath:position"]
      ],
      "value": "${password}"
    }, {
      "id": "a327a971-e163-4357-8422-6996397e8613",
      "comment": "",
      "command": "click",
      "target": "css=.btn",
      "targets": [
        ["css=.btn", "css:finder"],
        ["xpath=//button[@type='submit']", "xpath:attributes"],
        ["xpath=//div[4]/div/button", "xpath:position"],
        ["xpath=//button[contains(.,'Login')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }, {
    "id": "dd19e37b-eda4-4926-94c6-a8a8a76e753d",
    "name": "valid_credential",
    "commands": [{
      "id": "fbf3a3d6-4b1b-4e2a-96d7-3e88d0afbbd5",
      "comment": "",
      "command": "run",
      "target": "st_global_vars",
      "targets": [],
      "value": ""
    }, {
      "id": "5703d1fa-6b1b-448a-b274-56a87adff669",
      "comment": "",
      "command": "store",
      "target": "${valid_username}",
      "targets": [],
      "value": "username"
    }, {
      "id": "f82c2b8c-f03c-4732-a755-263a30ffd082",
      "comment": "",
      "command": "store",
      "target": "${valid_password}",
      "targets": [],
      "value": "password"
    }, {
      "id": "64c4df77-1e8e-4941-9d27-98d53d6b9e95",
      "comment": "",
      "command": "run",
      "target": "st_login",
      "targets": [],
      "value": ""
    }, {
      "id": "3cdcec82-9c72-4c89-9b5d-76be892300dc",
      "comment": "",
      "command": "run",
      "target": "st_logout",
      "targets": [],
      "value": ""
    }]
  }, {
    "id": "7f50d2bb-5695-4e73-8c54-cdc5fab736b9",
    "name": "create_ss",
    "commands": [{
      "id": "4624235a-0ce2-427e-965c-1173e0c24cde",
      "comment": "",
      "command": "store",
      "target": "myuser",
      "targets": [],
      "value": "username"
    }, {
      "id": "3c2f2858-3cae-4831-8c4b-9789915deb7d",
      "comment": "",
      "command": "store",
      "target": "mypwd",
      "targets": [],
      "value": "password"
    }, {
      "id": "8debb7fb-c2db-4e2d-9de2-94de511c59b0",
      "comment": "",
      "command": "run",
      "target": "st_login",
      "targets": [],
      "value": ""
    }, {
      "id": "b78cf27e-48c3-4fac-8324-0971e7ce2545",
      "comment": "",
      "command": "click",
      "target": "linkText=Admin",
      "targets": [
        ["linkText=Admin", "linkText"],
        ["css=#ADMIN > a", "css:finder"],
        ["xpath=//a[contains(text(),'Admin')]", "xpath:link"],
        ["xpath=//a[@onclick=\"updateLeftMenu('ADMIN')\"]", "xpath:attributes"],
        ["xpath=//li[@id='ADMIN']/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/ECM/flatViewJobcontrol/flatViewJobList')]", "xpath:href"],
        ["xpath=//li[6]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Admin')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "ad448871-9ab7-4f0f-8d20-5b76eb59ea81",
      "comment": "",
      "command": "click",
      "target": "css=#irep > a > .title",
      "targets": [
        ["css=#irep > a > .title", "css:finder"],
        ["xpath=//span[@onclick=\" window.location.href = '/ECM/users/list';\"]", "xpath:attributes"],
        ["xpath=//li[@id='irep']/a/span[2]", "xpath:idRelative"],
        ["xpath=//li[2]/a/span[2]", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "70d5b134-dfc6-4d28-9e73-08b19942b09f",
      "comment": "",
      "command": "click",
      "target": "css=#secsys > a",
      "targets": [
        ["css=#secsys > a", "css:finder"],
        ["xpath=//li[@id='secsys']/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/ECM/securitysystems/list')]", "xpath:href"],
        ["xpath=//li[2]/ul/li[7]/a", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "246e218c-8f55-44f4-9457-aa104a3d5111",
      "comment": "",
      "command": "click",
      "target": "css=#tab_1-1 .portlet-title .btn > .icon-angle-down",
      "targets": [
        ["css=#tab_1-1 .portlet-title .btn > .icon-angle-down", "css:finder"],
        ["xpath=//div[@id='tab_1-1']/div/div/div[2]/div/a/i[2]", "xpath:idRelative"],
        ["xpath=//i[2]", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "b5d4d64e-4b36-4f92-8eac-7b85bc47023f",
      "comment": "",
      "command": "click",
      "target": "linkText=Create Security System",
      "targets": [
        ["linkText=Create Security System", "linkText"],
        ["css=.open > .dropdown-menu > li:nth-child(1) > a", "css:finder"],
        ["xpath=//div[@id='tab_1-1']/div/div/div[2]/div/ul/li/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/ECM/securitysystems/create')]", "xpath:href"],
        ["xpath=//div[2]/div/ul/li/a", "xpath:position"],
        ["xpath=//a[contains(.,' Create Security System')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "ebc9f966-85e2-4f79-a8b0-cfd6fab40c6f",
      "comment": "",
      "command": "click",
      "target": "id=systemname",
      "targets": [
        ["id=systemname", "id"],
        ["name=systemname", "name"],
        ["css=#systemname", "css:finder"],
        ["xpath=//input[@id='systemname']", "xpath:attributes"],
        ["xpath=//form[@id='createsystem']/div/div/div/input", "xpath:idRelative"],
        ["xpath=//div/input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "bf3ea297-cf09-4b89-bff7-f2ad7ebc782f",
      "comment": "",
      "command": "type",
      "target": "id=systemname",
      "targets": [
        ["id=systemname", "id"],
        ["name=systemname", "name"],
        ["css=#systemname", "css:finder"],
        ["xpath=//input[@id='systemname']", "xpath:attributes"],
        ["xpath=//form[@id='createsystem']/div/div/div/input", "xpath:idRelative"],
        ["xpath=//div/input", "xpath:position"]
      ],
      "value": "budi_ss1"
    }, {
      "id": "1cb04feb-8e6e-4789-9f28-3849dbc00a3f",
      "comment": "",
      "command": "click",
      "target": "id=displayName",
      "targets": [
        ["id=displayName", "id"],
        ["name=displayName", "name"],
        ["css=#displayName", "css:finder"],
        ["xpath=//input[@id='displayName']", "xpath:attributes"],
        ["xpath=//form[@id='createsystem']/div/div/div[2]/input", "xpath:idRelative"],
        ["xpath=//div[2]/input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "b17bcd8e-ff4b-4b41-97d4-438e2b823457",
      "comment": "",
      "command": "type",
      "target": "id=displayName",
      "targets": [
        ["id=displayName", "id"],
        ["name=displayName", "name"],
        ["css=#displayName", "css:finder"],
        ["xpath=//input[@id='displayName']", "xpath:attributes"],
        ["xpath=//form[@id='createsystem']/div/div/div[2]/input", "xpath:idRelative"],
        ["xpath=//div[2]/input", "xpath:position"]
      ],
      "value": "budi_ss1"
    }, {
      "id": "dbddf9b7-a33b-474b-8c1f-5a9c193ac672",
      "comment": "",
      "command": "click",
      "target": "linkText=Create",
      "targets": [
        ["linkText=Create", "linkText"],
        ["css=.form-actions > .btn", "css:finder"],
        ["xpath=//a[contains(text(),'Create')]", "xpath:link"],
        ["xpath=//a[@onclick='checkAndCreate(this)']", "xpath:attributes"],
        ["xpath=//form[@id='createsystem']/div[2]/a", "xpath:idRelative"],
        ["xpath=(//a[contains(@href, 'javascript:;')])[9]", "xpath:href"],
        ["xpath=//div[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Create ')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "c04c0ba9-eed1-4b25-bf6b-e56bf980553d",
      "comment": "",
      "command": "run",
      "target": "st_logout",
      "targets": [],
      "value": ""
    }]
  }, {
    "id": "4403636b-cb74-451a-a3c2-2f2bc141b333",
    "name": "invalid_credential_2",
    "commands": [{
      "id": "eb2a3165-54ab-4b58-9f9b-a4330c441bb5",
      "comment": "",
      "command": "store",
      "target": "blah",
      "targets": [],
      "value": "username"
    }, {
      "id": "c5a45bef-cf4a-4c0d-8b6d-3d131d2404e7",
      "comment": "",
      "command": "store",
      "target": "blah",
      "targets": [],
      "value": "password"
    }, {
      "id": "d46e9e9d-44a3-482e-a9d7-435d492a6056",
      "comment": "",
      "command": "run",
      "target": "st_login",
      "targets": [],
      "value": ""
    }, {
      "id": "52dab24e-59c2-47e4-a441-79f98f85be9c",
      "comment": "",
      "command": "click",
      "target": "css=.btn",
      "targets": [
        ["css=.btn", "css:finder"],
        ["xpath=//button[@type='submit']", "xpath:attributes"],
        ["xpath=//div[4]/div/button", "xpath:position"],
        ["xpath=//button[contains(.,'Login')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "e4e7baf8-ecb2-4d08-9ebc-78b42425a6ac",
      "comment": "",
      "command": "assertText",
      "target": "css=.alert:nth-child(2) > span",
      "targets": [
        ["css=.alert:nth-child(2) > span", "css:finder"],
        ["xpath=//div[2]/span", "xpath:position"],
        ["xpath=//span[contains(.,'Sorry, we were not able to find a user with that username and password.')]", "xpath:innerText"]
      ],
      "value": "Sorry, we were not able to find a user with that username and password."
    }]
  }, {
    "id": "546ab4c3-a111-4187-b811-64cc3cb0b816",
    "name": "st_global_vars",
    "commands": [{
      "id": "89962537-ea5a-4d87-9002-cc4cade91d76",
      "comment": "",
      "command": "store",
      "target": "foo",
      "targets": [],
      "value": "invalid_username"
    }, {
      "id": "05725456-1f7a-4fc6-ab06-20974bb3fd74",
      "comment": "",
      "command": "store",
      "target": "foo",
      "targets": [],
      "value": "invalid_password"
    }, {
      "id": "6b6a9296-9726-4b4c-923f-7910433d82b3",
      "comment": "",
      "command": "store",
      "target": "myusr",
      "targets": [],
      "value": "valid_username"
    }, {
      "id": "bcabab52-9a64-4e6c-8704-63da48d91248",
      "comment": "",
      "command": "store",
      "target": "mypwd",
      "targets": [],
      "value": "valid_password"
    }]
  }],
  "suites": [{
    "id": "2797798e-f06e-4b35-a831-1d1bbfd27e9e",
    "name": "unhappy_suite",
    "persistSession": false,
    "parallel": true,
    "timeout": 300,
    "tests": ["7f5a28ab-ac08-48eb-a03e-567f149d75e6", "4403636b-cb74-451a-a3c2-2f2bc141b333"]
  }, {
    "id": "bd52818f-5035-41d9-a955-22956a7d641e",
    "name": "common_suite",
    "persistSession": false,
    "parallel": true,
    "timeout": 300,
    "tests": ["f18ccca7-8532-41d7-8ffa-65d45f790808", "6ec401fb-d842-400f-aca0-d08d3c84f69b"]
  }, {
    "id": "e73050cd-284c-40c9-a005-77927c86c1d5",
    "name": "happy_suite",
    "persistSession": false,
    "parallel": true,
    "timeout": 300,
    "tests": ["dd19e37b-eda4-4926-94c6-a8a8a76e753d"]
  }, {
    "id": "b487d9a2-3a63-4e17-8c27-a0f5b156b263",
    "name": "ss_suite",
    "persistSession": false,
    "parallel": true,
    "timeout": 300,
    "tests": ["7f50d2bb-5695-4e73-8c54-cdc5fab736b9"]
  }],
  "urls": ["https://myurl"],
  "plugins": []
}

Issues without a reproduction project are likely to stall.

## Environment

OS: MacOS Monterey 12.6
Selenium IDE Version:  v3.17.0
Selenium SIDE Runner Version:  4.0.0-alpha.15
Node version: v18.10.0
ChromeDriver version: 106.0.5249.61
Browser:
Browser Version: 106.0.5249.61

**Comment by toddtarsi** [comment] 2022-10-10 18:32
@balimoon777 - Thanks for reporting! Should be an easy fix, will look tonight.

**Comment by balimoon777** [comment] 2022-10-11 17:36
@toddtarsi I removed v4, reinstalled v3 and v3 fails now with error 'The programmatic API was removed in npm v8.0.0'

```
% selenium-side-runner -V                                
3.7.4
% selenium-side-runner --filter="happy" demo_project.side
info:    Running demo_project.side
/usr/local/lib/node_modules/selenium-side-runner/dist/npm.js:27
    throw err;
    ^

Error: The programmatic API was removed in npm v8.0.0
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/index.js:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /usr/local/lib/node_modules/selenium-side-runner/node_modules/global-npm/index.js:29:15
    at Object.<anonymous> (/usr/local/lib/node_modules/selenium-side-runner/node_modules/global-npm/index.js:41:3)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)

Node.js v18.10.0
```

**Comment by toddtarsi** [comment] 2022-10-11 17:38
@balimoon777 - Seems like you want your npm version to go down to stay on 3.x

**Comment by balimoon777** [comment] 2022-10-11 17:40
@toddtarsi I see. Let me wait then for the v4 fix. Thanks.

**Comment by balimoon777** [comment] 2022-10-17 18:18
@toddtarsi Have you had a chance to fix this issue on v4? Thanks.

**Comment by toddtarsi** [comment] 2022-10-17 19:08
@balimoon777 - Sorry, no

**Comment by balimoon777** [comment] 2022-10-19 05:10
@toddtarsi  I was able to install selenium-side-drive v3.17.0, tried it out, and observed a few issues which look like bugs. Please let me know once you've got a chance to fix the v4 version, so I can verify whether the issues occur in v4 as well. Thanks.

**Comment by toddtarsi** [comment] 2022-10-19 12:14
@balimoon777 - will do

**Comment by AuroreLeblois** [comment] 2022-10-20 09:44
Hello, I  face the same issue but i have other messages before the error .each.

When I run my test one by one I have the same behavior. 
But when i run them all together (with a run_tests.bat) => I face an other error before having the .each error  on each test => 'Unknown command storeXpathCount'
![image_2022-10-20_113851436](https://user-images.githubusercontent.com/51274472/196913779-027c3f8a-6f06-4b08-bdfd-9ec9c8e42771.png)

Maybe it will help...

Environment
OS: Windows 10 Pro
Selenium IDE Version: v3.17.0
Selenium SIDE Runner Version: 4.0.0-alpha.16
Node version: v16.15.0
ChromeDriver version: 106.0.5249.61
Browser: Chrome
Browser Version: 106.0.5249.61


EDIT: I fixed my first problem by replacing 'storeXpathCount' by 'storeElementCount' => my tests work now! ;)

**Comment by balimoon777** [comment] 2022-10-31 21:12
@toddtarsi Any ETA on this? The sooner this is fixed, the earlier I could test the v4 alpha version. Thanks.

**Comment by toddtarsi** [comment] 2022-10-31 21:23
@balimoon777 - Nope. I honestly just kind of disconnected after the last wave of issues. I'm tired of maintaining this stuff. It's exhausting and all consuming and I am struggling to care. I'm not sure there is an ETA. I can't even get myself to have cursory interest right now.

**Comment by balimoon777** [comment] 2022-11-01 16:19
@toddtarsi How can I help?

**Comment by toddtarsi** [comment] 2022-11-06 01:23
@balimoon777 - I'm pushing out a PR shortly. I think it should resolve this. Please let me know if it doesn't. Your feedback is very valuable.

**Comment by toddtarsi** [comment] 2022-11-10 04:35
@balimoon777 - This should be resolved on the latest version. I'm going to close this, but feel free to re-open if you're still getting this issue.

**Comment by jezahl** [comment] 2022-12-02 14:57
Hey @toddtarsi I'm seeing this issue right now on 4.0.0-alpha.32

**Comment by toddtarsi** [comment] 2022-12-02 14:58
@jezahl - Interesting! I thought I resolved this. Would you be able to post a reproducing side file and run command?

**Comment by jezahl** [comment] 2022-12-02 15:00
I'll need to sanitize my side file before I can post it....

**Comment by jezahl** [comment] 2022-12-02 15:05
Re-created the issue with a simple file:-

{
  "id": "0b92c09c-f225-4b25-8f4c-c57b15e9a79c",
  "version": "2.0",
  "name": "Simple",
  "url": "https://google.com/",
  "tests": [{
    "id": "b4f4ff9b-1356-444b-bd0c-fa8dd6fc4f2f",
    "name": "Test 2",
    "commands": [{
      "id": "c58a8c25-30c0-451f-a313-892fd74f9051",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "d15ae65e-886c-4f37-952b-ad9378a0c537",
      "comment": "",
      "command": "echo",
      "target": "Test 2",
      "targets": [],
      "value": ""
    }]
  }, {
    "id": "cf3264b4-51c5-4e69-8744-3e43c263d16c",
    "name": "Test 1",
    "commands": [{
      "id": "e5cdf636-eac7-4d0e-abf5-d7368ca67a7a",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "dfb2047d-f362-4341-9197-268d5b9a7338",
      "comment": "",
      "command": "echo",
      "target": "Test 1",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "b252fa97-3a81-43f0-bc31-cecfd20aa525",
    "name": "2A - Suite 1",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["cf3264b4-51c5-4e69-8744-3e43c263d16c"]
  }, {
    "id": "4849d60c-9c95-4779-aa42-6c014399fa6f",
    "name": "2B - Suite 2",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["b4f4ff9b-1356-444b-bd0c-fa8dd6fc4f2f"]
  }],
  "urls": ["https://google.com/", "https://google.co.uk/"],
  "plugins": []
}


[autotest@AUTOTEST ~]$ selenium-side-runner Simple.side -f 2A
 FAIL  .local/lib/node_modules/selenium-side-runner/dist/main.test.js
  Running project Simple
    Running suite 2A - Suite 1
      ✕ Running test $name (1 ms)

  ● Running project Simple › Running suite 2A - Suite 1 › Running test $name

    Error: `.each` called with an empty Array of table data.

      at test (node_modules/jest-each/build/index.js:38:47)
      at src/main.test.ts:145:7
          at Array.forEach (<anonymous>)
      at src/main.test.ts:136:18

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.696 s, estimated 5 s
Ran all test suites within paths "/home/autotest/.local/lib/node_modules/selenium-side-runner/dist/main.test.js".

**Comment by toddtarsi** [comment] 2022-12-02 15:38
@jezahl - Thank you very much! I'll try and take a look this weekend.

**Comment by jezahl** [comment] 2022-12-12 14:36
Hey @toddtarsi - Did you get a chance to look into this?

Thanks!

**Comment by toddtarsi** [comment] 2022-12-12 14:46
@jezahl - I did not this weekend. I was focused on frontend stabilizations and better supporting suite troubleshooting flows.

**Comment by pekonchan** [comment] 2022-12-20 06:04
I'm also seeing this issue right now on 4.0.0-alpha.34

**Comment by BorderCloud** [comment] 2022-12-20 16:25
+1 same problem with the last selenium/hub:3 with selenium-side-runner (4_alpha)
In Selenium IDE, storeXpathCount returns now a string... In the past, it was integer :'(

Edit:
I downgraded the version of selenium-side-runner for selenium/hub:3
`npm install -g selenium-side-runner@3.17.0`

**Comment by toddtarsi** [comment] 2022-12-20 19:28
Wowie, ok this is affecting people. Thanks for trying v4 and I know what I'm looking at next.

**Comment by toddtarsi** [comment] 2023-01-03 03:34
Oh gosh, I didn't mean for this to be closed. Re-opened.
 
 @jezahl - I tried with your side file. It passed just fine for me on this branch locally. I'm very surprised if you're still getting this on latest. Happy new year!

**Comment by jezahl** [comment] 2023-01-03 08:19
@toddtarsi I still get this error, with 4.0.0-alpha.36 ?

**Comment by toddtarsi** [comment] 2023-01-03 13:02
@jezahl - That is with the above side file? I'm using the above side file without issue on latest, but I'll try point 36

**Comment by jezahl** [comment] 2023-01-03 15:41
@toddtarsi Yep I still get the same error, using the file above.
I get the same error when trying to run any particular suite within any of my side files

**Comment by jezahl** [comment] 2023-01-16 10:50
@toddtarsi were you able to recreate this issue?

**Comment by toddtarsi** [comment] 2023-01-16 14:02
@jezahl - No! I was trying last night. I was thinking maybe its some filter flag thing.

**Comment by toddtarsi** [comment] 2023-01-16 14:05
Wait, I lied, I have it reproduced here! I needed your filter flag command and tried to do it myself ugh anyway, gonna see if I can just do it rill quick this morning.

**Comment by toddtarsi** [comment] 2023-01-16 14:55
@jezahl, okay, .37 should fix this and is building now. I should have it out in like 15 or so. Sorry about that all, looks like I was applying the filter twice, once to the suite and again to the tests in the suite, that last part is gone now.

Also, we're like two unit test tweaks and some extra branch protections from having A LOT more testing around features. Being able to test the side-runner a lot more will be a big part of moving out of alpha.

**Comment by toddtarsi** [comment] 2023-01-16 14:56
@jezahl - Oh no wait I lied again it's already out. I'm going to close this, but re-open if I'm you encounter otherwise. Thanks!

**Closed as completed by toddtarsi** 2023-01-16 14:56 UTC

**Comment by jezahl** [comment] 2023-01-16 15:55
@toddtarsi All working now,
Thanks and sorry for chasing you!

**Comment by toddtarsi** [comment] 2023-01-16 15:55
@jezahl - Not at all! Thank you for helping guide me to that! 😄
