### ISSUE TITLE
 Is it possible to make a call to RemoteLocalStorage API from selenium ide?

### ISSUE THREAD

**Issue by akshattambe** [SeleniumHQ/selenium-ide#947] opened 2020-02-10 11:55 UTC
## 💬 Questions and Help

Hi experts, I have just started with Selenium IDE and was wondering if it is possible to make a call to RemoteLocalStorage API from selenium ide?

I am curious to know if I can make a call something like below as a command from Selenium IDE-
`new RemoteLocalStorage(new RemoteExecuteMethod((RemoteWebDriver) driver)).clear();
`

I have posted the same question in slack and waiting for a response. Quick help is appreciated :)

Thanks in advance

**Comment by tourdedave** [comment] 2020-02-10 12:18
Duplicate of #946. Closing.

**Closed by tourdedave** 2020-02-10 12:18 UTC
