### ISSUE TITLE
send Keys does not work with chrome version 92.0.4515.107

### ISSUE THREAD

**Issue by VSAart** [SeleniumHQ/selenium-ide#1257] opened 2021-07-26 12:51 UTC
## 🐛 Bug Report

The SendKeys command doesn't work properly with chrome Version 92.0.4515.107

## To Reproduce

Create a TestSuite with the command SendKeys and Value ${KEY_ENTER}
The Command is not processed by chrome .side (in zipfile) attached.

## Expected behavior

The command SendKeys should send the keydown just like a physical keyboard.

## Project file reproducing this issue (highly encouraged)

[bug Key Enter.zip](https://github.com/SeleniumHQ/selenium-ide/files/6878245/bug.Key.Enter.zip)

## Environment

OS: Windows 10
Selenium IDE Version:  3.17.0
Browser: Chrome
Browser Version: 92.0.4515.107 (64-bit)

**Comment by toddtarsi** [comment] 2021-07-28 04:40
Interesting. I am on Mac OS and am not encountering this issue. I'll probably need to do some testing using a VM to figure out what is going on here.

**Comment by cford-hub** [comment] 2021-07-28 18:55
I'm having the same issue with this latest version of Chrome.  Both with IDE and running via the .side-runner in 
OS: Windows 10
Selenium IDE Version: 3.17.0
Browser: Chrome
Browser Version: 92.0.4515.107 (64-bit)

**Comment by toddtarsi** [comment] 2021-07-28 20:06
@cford-hub - Interesting. If it's also failing via the side-runner, that is indicative of possibly a greater problem. I believe the ide version uses simulated javascript events, but the side-runner should be using standard webdriver stuff.

@corevo - Would you have any thoughts off the top of your head for this one? I'm thinking this might be a Chromedriver issue possibly.

**Comment by cford-hub** [comment] 2021-07-28 20:46
@toddtarsi - I was wondering that too re:  Chormedriver.  The timing is related to Chrome updates.  For me, it started July 22, which is when I upgraded to v92.   I see in chromedriver history:   
ChromeDriver 91.0.4472.19
Supports Chrome version 91
Resolved issue 3744: SendKeys() and Click() silently fail after link navigation

It does seem now side-runner is better with v92, but IDE is still unable to sendKeys in Windows.

**Comment by toddtarsi** [comment] 2021-07-28 21:29
@cford-hub - Thanks for looking closer, and I'm glad to hear that at least the side-runner is okay. I'll try and figure out what's going on later tonight, but this will probably take me a while due to needing to get set up to develop on a windows os.

**Comment by toddtarsi** [comment] 2021-07-30 14:43
@cford-hub @VSAart - I am seeing this issue as well. I have not yet begun to debug, but I do have things reproducing on my end. Thanks for reporting this.

It is very interesting how it occurs on follow up enter keys, but not the first.

**Comment by cford-hub** [comment] 2021-08-04 20:23
@toddtarsi - Any progress on this or a workaround?  It's definitely strange that it impacts only the key strokes.  I haven't found a workaround yet, so it's been pretty problematic.  It does seem like it could be related to the last driver update, as that's about the time the issue appeared.

**Comment by toddtarsi** [comment] 2021-08-04 20:51
@cford-hub - Unforunately, not yet. I have been taking about 2 hours every other day, but most of that thus far has been installing windows, trying to use the linux subsystem, starting over, etc. Tonight I will be building the extension in Windows and re-running your test script with additional loggers. Thanks for providing those.

**Comment by toddtarsi** [comment] 2021-08-04 23:28
@cford-hub - Of course it turns out we can only build on mac and linux lol. That actually makes life easier, now I just need a workflow of sending it to myself.

**Comment by RunskyX** [comment] 2021-08-05 07:59
I also meet the same problem, when running send keys, the ide got stuck. when I debug it, I found out 
`getDocument() {
                return this.sendCommand("DOM.getDocument", {
                    pierce: !0,
                    depth: -1
                }).then(e=>e.root)
            }`
sendCommand it ,and then got pending
![image](https://user-images.githubusercontent.com/32878485/128313590-61a8d232-8624-46f9-a276-88c254af887f.png)
and throws error "Unchecked runtime.lastError: Another debugger is already attached to the tab with id: 63."

![image](https://user-images.githubusercontent.com/32878485/128314134-d7654974-1858-4227-a8fa-6a223b46af9a.png)

**Comment by toddtarsi** [comment] 2021-08-12 16:39
@RunskyX - Thanks for taking such a close look at this. I'm closer to building on Windows and hope to actually be debugging this sometime in the next week or two.

**Comment by toddtarsi** [comment] 2021-08-17 23:47
@RunskyX @cford-hub - Building turned out to be rather easy using WSL. I know that doesn't do anything for ya, but I do want you to know that I am slowly making my way here, and it is important to me to fix this.

**Comment by cford-hub** [comment] 2021-08-18 13:11
@toddtarsi  Great news!  Thanks very much for looking into this.

**Comment by cford-hub** [comment] 2021-09-01 13:14
@toddtarsi Are you having any luck debugging/fixing this issue?

**Comment by toddtarsi** [comment] 2021-09-01 15:20
@cford-hub - Not a lot these last couple weeks. We have been prepping for a series at my workplace for this last month, so I haven't had a lot of time to invest in coding aside from work. Things finished up last Friday, so I'm probably going to be caught up enough to not be panic programming all night some time this week. So next week should show more progress. I'll keep you apprised of what I find. Thanks for keeping me accountable haha 😄

**Comment by toddtarsi** [comment] 2021-09-05 16:21
@RunskyX - Yeah, after looking a bit more, I'm on the same page as you. Wowie woof, this bug doth suxxx royally indeed. 

At this point, I think the most likely culprit is a bug in Chrome Windows. The reason I'm leaning this way is that the debugger top bar thingy shows weirdly on more tabs than the active one.

My goal has shifted pretty much from solving this to obtaining the simplest reproduction, which I could hopefully take to the CDP team and find out if it's them or me.

**Comment by toddtarsi** [comment] 2021-09-13 14:29
@RunskyX @cford-hub - Okay, I am big dumb. I opened issue with chrome devtools team here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1249025

I will just work with them there. I should have done this weeks ago, but again, I am big dumb.

**Comment by mattmundell** [comment] 2021-09-18 14:51
Maybe the same issue: 'send keys' of ${KEY_SPACE} hangs for me in 3.17.0 with Chromium 93.0.4577.82 on Ubuntu.  Worked okay in Firefox.

**Comment by toddtarsi** [comment] 2021-09-18 15:14
Thanks for reporting. The good news is that Google is pursuing this. The
bad news is that we have little to no control over a hang from CDP on
windows only.

**Comment by mattmundell** [comment] 2021-09-18 16:01
> on windows only.

Just to be clear: I'm seeing this on Ubuntu.

**Comment by toddtarsi** [comment] 2021-09-18 16:38
Oh man. I currently only have a windows and Mac. Are you seeing the
provided side file fail as well? If so, I’ll update the chromium bug
accordingly.

**Comment by mattmundell** [comment] 2021-09-18 16:57
> Are you seeing the provided side file fail as well?

Sort of.  The first two work, but it hangs after 'test1'.

On Firefox it works fine (but have to slow it down for the page to load at all).

**Comment by toddtarsi** [comment] 2021-09-18 17:06
The after test1 is occurring on windows too. For the Firefox slow down
stuff, I am not sure what would be occurring

**Comment by toddtarsi** [comment] 2021-09-18 17:07
It’s not all send keys, it’s after some combo of previous commands and
router transitions.

**Comment by mattmundell** [comment] 2021-09-18 18:12
> For the Firefox slow down stuff, I am not sure what would be occurring

It's well known I think.  It's also fixed by putting a commented out command at the beginning.

By the way, seems my original issues is different, the 'send key' works but does nothing, I guess due to the target I'm using.

**Comment by toddtarsi** [comment] 2021-09-20 11:19
@mattmundell - Thanks for the clarification. Woof, this is a real bummer of a bug. I don't have enough computers to look into this as well without cycling my OS. With that unfortunate limitation on my actions, I'll keep the current chromium ticket focused to just windows, and after we clear that, if this persists, I'll start going after CDP ubuntu send keys. It's wild that everything appears to be dumping here except mac.

**Comment by jder** [comment] 2021-09-20 14:16
I can reproduce this (hang after entering "test1" when trying to send the enter key with the test file) on macOS 11.6, Chrome version 93. So, maybe this is not OS-specific?

**Comment by toddtarsi** [comment] 2021-09-20 14:19
Hm. I'm seeing this ~~pass~~  fail on my MacOS as well, but I could swear I saw this test pass back when we were on 92.

UPDATE: I changed pass to fail, sorry about that.

**Comment by toddtarsi** [comment] 2021-09-20 14:27
Okay, so with everyone having weighed in, I'd like to just confirm.

We are seeing the hang at the "test1" step on Windows, MacOS, and Ubuntu. Not an instant or sub 30 second failure, but a hang.

**Comment by toddtarsi** [comment] 2021-09-20 14:36
Okay, I'll update the Chromium issue. This is 99% likely still hanging at the `DOM.getDocument` call to CDP.

**Comment by toddtarsi** [comment] 2021-11-27 16:26
@VSAart - Are you up to a version where it works again by any chance? I see the Chromium issue is still open and un-responded to. I'm hoping maybe this got fixed somewhere else.

**Comment by toddtarsi** [comment] 2021-11-27 16:29
For now, marking this as blocked native, since it comes down to CDP issues, and the source issue has someone who repro'd without the ide involved.

**Comment by mattmundell** [comment] 2021-11-27 17:28
Works now for me.  Chromium Version 96.0.4664.45 on Ubuntu.

**Comment by toddtarsi** [comment] 2021-11-27 17:30
@mattmundell - Awesome, I'll have to call that good enough. I'll close this ticket and mark as resolved on latest in Chromium threads.

**Closed as completed by toddtarsi** 2021-11-27 17:30 UTC
Labels: blocked native

**Comment by cford-hub** [comment] 2021-11-29 14:14
This works for me again now in IDE Chrome version 96.
