### ISSUE TITLE
Test Suites are skipping every other test after the 3rd Test

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#871] opened 2019-11-11 12:31 UTC
## To Reproduce

Run a Test Suite with at least 9 test
## Expected behavior
All Tests should run
After the 2nd test, the 3rd,5th,7th...... tests are being skipped
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by tourdedave** [comment] 2019-11-11 12:38
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

**Closed by tourdedave** 2019-11-11 12:38 UTC

**Comment by Kielmed** [comment] 2019-11-11 12:59
Please re-open this and fix it.

**Comment by tourdedave** [comment] 2019-11-11 13:03
@Kielmed Please open a new issue and fill out the template in its entirety. Then we'll be happy to look into it.

**Comment by Kielmed** [comment] 2019-11-11 13:07
You have a fundamental issue with your app, I cannot take the time to spell it out for you, busy here. You fill out the form.

**Comment by tourdedave** [comment] 2019-11-11 13:20
@Kielmed There's no need to be rude. This is an open source project with hundreds of open issues. In order for us to prioritize and look into bugs, we need all of the information requested regardless of how severe an issue may or may not be.

**Comment by tourdedave** [comment] 2019-11-11 18:22
Duplicate of #873
