### ISSUE TITLE
Selenium Side Runner 4.0.0-alpha.16 not running simple side script

### ISSUE THREAD

**Issue by NikhilHedau** [SeleniumHQ/selenium-ide#1547] opened 2022-10-20 10:46 UTC
## 🐛 Bug Report

I've created a simple .side file in Chrome using selenium IDE (on Mac), and when I am trying to run this using the side runner on mac I am  getting the below  error .  The side file is running fine with selenium-side-runner v3.17.0

selenium-side-runner -c "browserName=chrome" test.side --debug 
Could not load /Users/userName/Downloads/.side.yml
Configuration: {
  baseUrl: '',
  capabilities: { browserName: 'chrome' },
  debug: true,
  filter: '.*',
  force: undefined,
  maxWorkers: 8,
  params: {},
  projects: [ '/Users/userName/Downloads/test.side' ],
  proxyOptions: {},
  runId: '3940e2d15135bc8a5d38759ad2f0a69c',
  path: '/usr/local/lib/node_modules/',
  server: '',
  timeout: 15000
}
info: Running test Untitled
debug: Playing state changed prep
info: Building driver for chrome
info: Driver has been built for chrome
debug: Playing state changed playing
debug: executing open|https://martinfowler.com
  console.warn
    Unexpected error occured during command: open-https://martinfowler.com- retrying...

      at CommandNode.handleTransientError (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:186:15)
      at CommandNode.retryCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:144:12)
      at CommandNode._executeCoreCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:156:12)

  console.error
    Command failure: open-https://martinfowler.com-

      at CommandNode.handleTransientError (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:197:15)
      at CommandNode.retryCommand (node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:144:12)

debug: errored open|https://martinfowler.com
debug: Playing state changed errored
info: Finished test Untitled Failure
warn: Completed with failure
 FAIL  ../../../usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js (6.515 s)
  Running project test
    Running suite Default Suite
      ✕ Running test Untitled (6308 ms)

  ● Running project test › Running suite Default Suite › Running test Untitled

    thrown: true

      at node_modules/jest-each/build/bind.js:43:11
          at Array.forEach (<anonymous>)
      at src/main.test.ts:107:7
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        56.067 s
Ran all test suites within paths "/usr/local/lib/node_modules/selenium-side-runner/dist/main.test.js".
/usr/local/lib/node_modules/selenium-side-runner/node_modules/@seleniumhq/side-runtime/dist/playback-tree/command-node.js:86
            throw new Error('Operation timed out!');
            ^

Error: Operation timed out!
    at Timeout._onTimeout (/usr/local/lib/node_modules/selenium-side-runner/node_modules/@seleniumhq/side-runtime/src/playback-tree/command-node.ts:137:13)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

## To Reproduce

selenium-side-runner -c "browserName=chrome" test.side --debug

## Expected behavior

Test should pass

## Project file reproducing this issue (highly encouraged)

{
  "id": "dd67bf12-4c9b-4c21-a1d5-d982e225c313",
  "version": "2.0",
  "name": "test",
  "url": "",
  "tests": [{
    "id": "1c6326e3-716f-4f5c-9ed1-196aee553c67",
    "name": "Untitled",
    "commands": [{
      "id": "dae34486-22df-4819-b7af-4c97cce57f73",
      "comment": "",
      "command": "open",
      "target": "https://martinfowler.com",
      "targets": [],
      "value": ""
    },{
        "id": "f3005c16-c500-46d6-a5d8-3b75fe05f997",
        "comment": "",
        "command": "pause",
        "target": "10000",
        "targets": [],
        "value": ""
      }]
  }],
  "suites": [{
    "id": "25d6220d-cd85-426a-9760-df1f49d0c974",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 20000,
    "tests": ["1c6326e3-716f-4f5c-9ed1-196aee553c67"]
  }],
  "urls": [],
  "plugins": []
}

## Environment

OS: macOS Monterey 12.5, Chip : Apple M1 Pro
Selenium IDE Version:  3.17.2
Selenium SIDE Runner Version:  4.0.0-alpha.16
Node version: 16.18.0
Browser: Chrome
Browser Version: 106.0.5249.61 (Official Build) (arm64)
Chrome Driver Version : 106.0.5249.61

**Comment by toddtarsi** [comment] 2022-11-10 04:33
@NikhilHedau - Sorry for the delay in responding here! I think the issue is how the url is specified. I think the top level url field should be `"https://martinfowler.com"` and then the target on the open command would be `"/"`. Let me know if that makes sense or resolves your issue?

**Comment by NikhilHedau** [comment] 2022-11-11 12:38
@toddtarsi , Thanks for the update. I tried executing your changes, getting the attached error now. Environment is the same as shared above.
[error.txt](https://github.com/SeleniumHQ/selenium-ide/files/9990262/error.txt)

Side File 

{
  "id": "6eacb2ff-43bf-4d6a-b54f-c6a75f5beb75",
  "version": "2.0",
  "name": "Test",
  "url": "https://www.martinfowler.com",
  "tests": [{
    "id": "bb1a68d5-95ed-4767-b406-dde3c9e7295a",
    "name": "Untitled",
    "commands": [{
      "id": "3337617e-2920-4dbe-8210-f7a9d1b01538",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "d5ee5bd2-05ac-4933-8a5d-4981a629cb5b",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["bb1a68d5-95ed-4767-b406-dde3c9e7295a"]
  }],
  "urls": ["https://www.martinfowler.com/"],
  "plugins": []
}

**Comment by toddtarsi** [comment] 2022-11-11 13:01
Interesting! I'll try and take a look one of these upcoming nights. Thanks for taking a close look 😄

**Comment by NikhilHedau** [comment] 2022-11-11 15:01
Sure, Thanks for helping out.

**Comment by toddtarsi** [comment] 2022-11-14 01:17
@NikhilHedau - Looks like maybe its fixed on latest? Just ran this test locally without issue:

```
> test:side-runner
> node ./packages/side-runner/dist/bin.js -t 15000 ./tests/examples/nikhil.side

info: Running test Untitled
info: Building driver for chrome
info: Driver has been built for chrome
info: Finished test Untitled Success
 PASS  packages/side-runner/dist/main.test.js
  Running project Test
    Running suite Default Suite
      ✓ Running test Untitled (3263 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.654 s, estimated 5 s
Ran all test suites within paths ".../Code/selenium-ide/packages/side-runner/dist/main.test.js".
```

**Comment by toddtarsi** [comment] 2022-11-14 01:17
I'm going to close this for now, but if you keep getting issues, let me know.

**Closed as completed by toddtarsi** 2022-11-14 01:17 UTC

**Comment by NikhilHedau** [comment] 2022-11-14 05:38
@toddtarsi , Thanks for the update, I will check with the latest version and update here.

**Comment by NikhilHedau** [comment] 2022-11-14 12:47
@toddtarsi , I have verified with the latest version (alpha.31) , the error seems to be resolved now.
