### ISSUE TITLE
Chrome Selenium IDE plugin does not allow to call JS functions (of the website under test) , which are available in Chrome DEV console 

### ISSUE THREAD

**Issue by sporthcophcop** [SeleniumHQ/selenium-ide#386] opened 2018-09-07 09:52 UTC
## 🐛 Bug Report

Chrome Selenium IDE plugin does not allow to call JS functions (of the website under test) , which are available in Chrome DEV console. The same Selenium IDE test works fine in Firefox Selenium IDE.

## To Reproduce

Go to Google.com and try to call googleapis.constructor
in FF Selenium IDE it executes, in Chrome Selenium IDE "Failed: googleapis is not defined"
See attached .side example

## Expected behavior

I would assume both plugins and browser (FF and Chrome) combination have the same behavior, and what is possible on the Development console of Web browser is possible in Selenium IDE. 

## Project file reproducing this issue (highly encouraged)

See included .side file:
{
  "id": "6993202d-80b9-479e-b83d-75bdb89dea04",
  "version": "1.1",
  "name": "FF+Chrome-diff",
  "url": "http://www.google.com/",
  "tests": [{
    "id": "f11575cd-046a-4a5b-a01c-5aab1acc36be",
    "name": "Chrome is different",
    "commands": [{
      "id": "aaf561d4-007b-472e-aab7-28f15d6cd5d9",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "ecb9ad16-e39c-4a91-b0eb-223e867ec9c8",
      "comment": "",
      "command": "executeScript",
      "target": "googleapis.constructor",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [],
  "urls": ["http://www.google.com/"],
  "plugins": []
}

## Environment

OS: Windows 10 Pro
Selenium IDE Version:  3.3.1
Browser: Chrome
Browser Version:  69.0.3497.81 (Official build) (64-bits)
Browser: Firefox Quantum
Browser Version:  62.0 (64-bits)

**Comment by corevo** [comment] 2018-09-21 08:47
Duplicate of #368

**Closed by corevo** 2018-09-21 08:47 UTC
