### ISSUE TITLE
goback command is missing from selenium ide Version 3.0.3.0.

### ISSUE THREAD

**Issue by khalid123456** [SeleniumHQ/selenium-ide#408] opened 2018-09-24 09:08 UTC
## 👉 [Please follow one of these issue templates](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by corevo** [comment] 2018-09-24 09:11
This issue does not follow the issue template format (which makes it harder for us to track bunch of issues at once).
And it is a duplicate of #393

**Closed by corevo** 2018-09-24 09:11 UTC
