### ISSUE TITLE
`type` command on `input type=file` broken for Chrome 72

### ISSUE THREAD

**Issue by vincent-olivert-riera** [SeleniumHQ/selenium-ide#569] opened 2019-02-03 17:51 UTC
## 🐛 Bug Report

`type` command for setting a value into an `<intput type="file">` element is broken in current Google Chrome stable (72). Works on previous one (71).

## To Reproduce

Execute a `type` command to set a value on an `<input type="file">` element.

## Expected behavior

The `input` element should be set with the value provided.

## Project file reproducing this issue.

https://github.com/vincent-olivert-riera/test-selenium-bug/blob/master/foo.side

## Environment

OS: Debian (same problem in Ubuntu)
Selenium IDE Version:  all (I have tried from 3.5.3 to 3.2.5)
Browser: Google Chrome
Browser Version: 72.0.3626.81-1 (64-bit)

**Comment by corevo** [comment] 2019-02-04 12:15
Can you please provide more info, I've ran your test case and it looks fine
![image](https://user-images.githubusercontent.com/888886/52207817-3ff18680-2887-11e9-9b1e-0f3d9d6319fd.png)
I'll try to get my hands on Ubuntu and see if the problem is OS specific.

**Comment by corevo** [comment] 2019-02-04 12:18
I just ran against version 72, mistakenly I used 71

**Comment by corevo** [comment] 2019-02-04 13:02
I filed a ticket with Chrome [here](https://bugs.chromium.org/p/chromium/issues/detail?id=928255), I used the url you provided in the ticket, so please keep it alive.

**Comment by vincent-olivert-riera** [comment] 2019-02-04 13:05
> I used the url you provided in the ticket, so please keep it alive.

@corevo ok, no problem. By the way, in that ticket you say...
> Does this work in other browsers? Yes

I thought file uploading with `selenium-ide` only worked in Chrome.

**Comment by corevo** [comment] 2019-02-04 13:07
File upload is chrome only, I said yes because it is a Chrome only feature, so it's a Chrome only issue, both answers are ambiguous since other browsers don't do that.

**Comment by twnew** [comment] 2019-02-09 10:06
Thanks for looking into this! I tested on several websites on Linux and Windows with the latest version of the IDE and Chrome 72.0.3626.96. Always the same result: `{"code":-32000,"message":"Not allowed"}`

The issue seems to happen on **every** file upload dialog on the web, for example

- https://fineuploader.com/demos.html 
- https://blueimp.github.io/jQuery-File-Upload/

(These are _not_ my websites).

I found a workaround using the [xtype](https://forum.a9t9.com/t/chrome-update-disabled-the-file-upload-feature-code-32000-message-not-allowed/1709/2) command, but this requires the computer/server to remain unlocked. So it is only a workaround, no solution.

**Comment by vdrouet** [comment] 2019-02-12 14:11
How to make the "XType" command work on Selenium IDE ?
I have a "Failed: Unknow command xtype" error when i try to use it.

**Comment by corevo** [comment] 2019-02-12 14:17
@vdrouet `xtype` is not a Selenium IDE command, I am unsure where that false information is coming from.  
@twnew please refrain from promoting competitor tools in our issue tracker, it confuses users.

**Comment by osharke** [comment] 2019-03-07 17:53
I'm not having much luck getting uploads to work with the latest Selenium IDE Chrome extension. I have read all the threads but still I'm getting the same error {"code":-32000,"message":"Not allowed"}
Question, is this is issue with Chrome supporting this feature and or can somebody provide the exact command within the IDE that will function for upload functionality.

**Comment by vincent-olivert-riera** [comment] 2019-03-07 18:34
@osharke it's a problem in Chrome which is being fixed:

https://bugs.chromium.org/p/chromium/issues/detail?id=928255

Hopefully it will be ready for Chrome 74. Meanwhile you can use Chrome 71.

**Comment by osharke** [comment] 2019-05-01 16:05
Chrome 74 just release – you still not resolved. Was the fix not included?

Thanks,

-steven-

**Comment by osharke** [comment] 2019-05-10 14:17
Still not having any luck within Chrome 74. Any chance you have an insight on when this will be resolved?

code :-32000 message : not allowed working


Thanks,

-steven-

**Comment by oggo** [comment] 2019-05-11 21:18
I have the same problem :-O Is it going to be fixed, or should i look for another solution?

Cheers, 
Oggo

**Comment by corevo** [comment] 2019-05-12 11:05
@oggo @osharke posting here won't help solve the issue, as it is a problem with chrome, you should seek the chromium dev team for progress on the issue.

**Comment by qatestchannelass** [comment] 2019-05-15 20:11
Any idea when the issue will be fixed?

**Comment by tourdedave** [comment] 2019-05-16 06:18
@qatestchannelass Unfortunately no, since we're waiting on a fix from the Chromium team. See [here](https://bugs.chromium.org/p/chromium/issues/detail?id=928255) for details.

**Comment by corevo** [comment] 2019-05-16 06:53
Closing as it is an issue with Chrome.

**Closed by corevo** 2019-05-16 06:53 UTC
Labels: confirmed, waiting on external fix

**Comment by vincent-olivert-riera** [comment] 2019-05-21 09:38
@corevo they have asked to reopen the ticket:
https://bugs.chromium.org/p/chromium/issues/detail?id=928255#c23

**Comment by corevo** [comment] 2019-05-21 11:39
I'm sorry I can't do it on my end, I will try to check on my end, it would be helpful if you could try using a beta or canary version of Chrome and see if it is fixed in those.

**Comment by p2635** [comment] 2019-05-22 12:35
Can someone do me a favour and update this ticket when the chromium come back to us? I hope they reopen it..

**Comment by vincent-olivert-riera** [comment] 2019-05-22 12:40
> Can someone do me a favour and update this ticket when the chromium come back to us? I hope they reopen it..

The ticket has already been reopened.

**Comment by p2635** [comment] 2019-05-22 13:11
Thanks @vincent-olivert-riera , I'm struggling to find a way to subscribe to that issue. Do you know how I can keep up to date with that?

**Comment by vincent-olivert-riera** [comment] 2019-05-22 13:14
> Thanks @vincent-olivert-riera , I'm struggling to find a way to subscribe to that issue. Do you know how I can keep up to date with that?

I don't know, I just check it from time to time.

**Comment by vincent-olivert-riera** [comment] 2019-06-08 09:30
I have tested it with `Version 74.0.3729.169 (Official Build) (64-bit)` and it seems to be fixed.

**Comment by tomdavies14** [comment] 2019-06-10 07:56
Im still getting `Failed: {"code":-32000,"message":"Not allowed"}`, on `Version 74.0.3729.169`..

Is it fixed for anyone else?

**Comment by tourdedave** [comment] 2019-06-10 08:28
Chrome 75.0.3770.80 with a matching ChromeDriver just came out. Can you try on that?

**Comment by tomdavies14** [comment] 2019-06-10 09:17
updated to 75.0.3770.80 and no change, for me anyway...

**Comment by buckett** [comment] 2019-06-13 17:05
@tomdavies14 Snap, broken for me with 75.0.3770.90

**Comment by AshwinK1989** [comment] 2019-06-24 07:34
Not working for me either.

**Comment by tourdedave** [comment] 2019-06-24 08:02
To get the fix, you need to enable `Allow access to file URLs` in the browser extension settings for Selenium IDE.

![recording](https://user-images.githubusercontent.com/457137/60001615-7df11a80-966f-11e9-84fd-08609012f908.gif)

**Comment by AshwinK1989** [comment] 2019-06-24 08:12
@tourdedave I tried the above the solution. I am able to upload the file. However, the finder does not close after uploading the file.

**Comment by tourdedave** [comment] 2019-06-24 08:25
Don't click the button, it renders a system dialog that Selenium can't interact with. You need to just `type` the filepath into the element. See [the example provided by the submitter of this issue](https://github.com/vincent-olivert-riera/test-selenium-bug/blob/master/foo.side).

**Comment by AshwinK1989** [comment] 2019-06-24 09:32
Oh. Just the way it works for Selenium Webdriver. Did the changes and it is working fine now.
Thanks @tourdedave

**Comment by tomdavies14** [comment] 2019-06-24 09:53
fine here too, thank you all
