### ISSUE TITLE
Select Frame command not working

### ISSUE THREAD

**Issue by pdxwaitlist** [SeleniumHQ/selenium-ide#537] opened 2019-01-13 22:02 UTC
## 🐛 Bug Report

I am unable to use the selectFrame command to interact with elements inside an iframe on an HTML page

## To Reproduce

Use the following Selenium IDE commands to try to click the checkbox on a Google Recaptcha v2, which uses iframes to display on a page:
    {
      "Command": "open",
      "Target": "https://www.google.com/recaptcha/api2/demo",
      "Value": ""
    },
    {
      "Command": "selectFrame",
      "Target": "index=0",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "//*[@id=\"recaptcha-anchor\"]/div[5]",
      "Value": ""
    }

## Expected behavior

Actual result: (from Selenium IDE logs)
Running 'Untitled' 
1.open on google.com/recaptcha/api2/demo... OK 
2.selectFrame on index=0... Failed: Timeout

This also happens if using other methods to try to select the frame - by ID, by other indexes, etc.

Expected result: no error when running the selectFrame command

## Environment

OS: Mac OSX 10.13.6
Selenium IDE Version:  3.4.5 
Browser: Chrome
Browser Version: 71.0.3578.98

**Comment by tourdedave** [comment] 2019-01-14 08:40
Only index based locators for `select frame` are available right now.

Unfortunately I'm unable to reproduce the issue with the use case you provided.

Can you attach your project file to the issue as a zip file?

**Comment by pdxwaitlist** [comment] 2019-01-18 04:42
I did a little more troubleshooting on the issue. Strangely, this seems to be specific to Chrome -- when I run the test in Firefox it works normally but in Chrome the `select frame` command (using an index locator) returns an error. 

I've attached a zip file with my test case, as well as screenshots of the results when I run this test case in Chrome and in Firefox. Let me know if there is any other info I can provide. Thanks!

[iframe.zip](https://github.com/SeleniumHQ/selenium-ide/files/2771634/iframe.zip)

**Comment by p2635** [comment] 2019-01-18 12:46
Windows 10
Selenium 3.4.5
Firefox 64.0.2 (64bit)
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Tested both the original test and the zip file, it works for me but I am on Windows.

**Comment by Jongkeun** [comment] 2019-02-21 08:14
@tourdedave , Are there any plans that make available to find frame by `id` or stuff ? not only index.

**Comment by corevo** [comment] 2019-02-21 09:11
We have plans on doing that, since index is very flaky, but currently it proves to be problematic with cross origin frames, we might be able to roll it out for same origin first.

**Comment by stupidnetizen** [comment] 2019-03-02 06:07
Hi All, 
I tried reproducing the issue based on the discussion above but to no avail. 
`selectFrame` command is working in both Chrome and Firefox with `index=0` as the target. I am attaching the screenshot of steps in Chrome. Also please see the text file (rename it to save as `.side` to open in the ide.)

![selenium_chrome](https://user-images.githubusercontent.com/3921089/53678020-1a3d7e80-3c87-11e9-9f98-9b93a37122c2.png)
[selenium_ide_issues.txt](https://github.com/SeleniumHQ/selenium-ide/files/2921803/selenium_ide_issues.txt)

**Comment by corevo** [comment] 2019-03-03 08:21
@pdxwaitlist your reproducer seems to work for multiple users (including myself).  
Please try upgrading Chrome and Selenium IDE, closing for now, once you have a working reproducer we will reopen this issue.

**Closed by corevo** 2019-03-03 08:21 UTC
Labels: reproducer required
