### ISSUE TITLE
selenium-side-runner: does not select item in dropdown

### ISSUE THREAD

**Issue by etvoorde** [SeleniumHQ/selenium-ide#905] opened 2019-12-06 13:23 UTC
## 🐛 Bug Report

Selenium-side-runner does **not** select the option in a dropdown box. Although it works as expected in Selenium IDE. It doesn't matter if the item is selected by label or index.

The problem does not occur for other dropdown boxes.

## To Reproduce
Unfortunately I don't know simple reproduction steps. The particular command is
Command: Select
Target: xpath=//div/label[contains(.,'Filter actions:')]/../select
Value: index=2

## Expected behavior
Selenium selects the item in the dropdown before continuing to the next step.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: macOS 10.15.1
Selenium IDE Version:  3.16.1
Selenium SIDE Runner Version:  3.16.0
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 10.16.2
Browser: Chrome
Browser Version:  78.0.3904.108

**Comment by tourdedave** [comment] 2019-12-29 07:17
If you know the command that causes this issue, then please create a simple SIDE project that reproduces the problem against a public website we can access.

**Comment by shujapathan** [comment] 2020-10-01 15:28
[dropdownIssue.zip](https://github.com/SeleniumHQ/selenium-ide/files/5313131/dropdownIssue.zip)

**Comment by shujapathan** [comment] 2020-10-01 15:28
Issue reproduced

**Comment by shujapathan** [comment] 2020-10-01 15:29
> If you know the command that causes this issue, then please create a simple SIDE project that reproduces the problem against a public website we can access.

Please find attached file for the issue
[dropdownIssue.zip](https://github.com/SeleniumHQ/selenium-ide/files/5313142/dropdownIssue.zip)

**Comment by seyedmaysamlavasani** [comment] 2020-12-21 06:00
I am encountering a similar issue - any update on this?

What is strange is that the selection does not happen on the driven browser but the side runner actually complains about the next command.

Here is a further clarification of the issue:

command 1-click on the drop down 
command 2-click on one of the items in the drop down
command 3-click on a text that shows up only after the drop down selection is complete

The side runner opens the browser (I am not running in a headless mode) and only command 1 gets executed on the browser (I see that the drop down is opened but the item is not selected).
However side runner report that it cannot run the third command (because cannot find the object).

When I run the same series of the commands in the IDE everything is running successfully.

Here is the sample side file:
[varMicrosoftEchoResult.side.gz](https://github.com/SeleniumHQ/selenium-ide/files/5722547/varMicrosoftEchoResult.side.gz)

**Comment by Bertie-Chapman** [comment] 2022-12-18 09:08
Did you get anywhere with this?

**Comment by toddtarsi** [comment] 2022-12-19 16:34
@Bertie-Chapman - I'm the sole maintainer now and I've never talked to you about this before. I'm going to assume this is resolved in v4 however, which uses a shared runtime between the IDE and the side runner. This really does wonders for consistency.

**Closed by toddtarsi** 2022-12-19 16:34 UTC
Labels: reproducer required
