### ISSUE TITLE
Moz-extension window blank on Firefox Quantum

### ISSUE THREAD

**Issue by Guiraud** [SeleniumHQ/selenium-ide#61] opened 2017-12-11 17:08 UTC
Hi, 
On a firefox quantum 57.0.1 (64-bit)
After installing the 1.0 beta, the window is blank when starting the selenium add-on.
I restarted Firefox and computer.
Any clue ?

**Comment by corevo** [comment] 2017-12-12 08:11
I can't replicate it on Firefox 57.0.2, can you send my the logs (press Command-Shift-I, or F12 on Windows)

**Comment by Guiraud** [comment] 2017-12-17 17:39
When i press Ctrl-Shift +I the content appeared. :/ I'm on 57.0.1 on linux debian stretch

**Comment by corevo** [comment] 2017-12-18 08:13
I see, I'll try to setup a VM, in the mean time, was there no error at all in that console?

**Comment by hlovdahl** [comment] 2017-12-20 00:12
I think this might have something to do with the linux firefox version. I am using ubuntu 16.0 and the same happened to me. You can resolve it by maximizing the extensions window (double-clicking on the  head bar). Then it becomes visible. There was another plugin that does the same to me.

**Comment by corevo** [comment] 2017-12-20 08:56
It's also resolved by simply right clicking on the extension window,  
It seems to me it's a bug with Firefox

**Comment by shs96c** [comment] 2018-02-19 17:55
FWIW, I see the same thing with Mac OS with Nightly Firefox. Steps to reproduce:

* Build the prod extension
* Install as a developer extension in Firefox Nightly
* Click the IDE icon

You _should_ see the blank window if you have the same issue we're seeing.

**Comment by corevo** [comment] 2018-02-20 08:36
The issue has been reported in Bugzilla 3 times, and is currently unassigned,
[here](https://bugzilla.mozilla.org/show_bug.cgi?id=1425829) [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1426405) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1416505)

**Comment by corevo** [comment] 2018-05-21 07:28
Mozilla decided to include this bug as part of FF60,  
I've found a workaround [here](https://discourse.mozilla.org/t/ff57-browser-windows-create-displays-blank-panel-detached-panel-popup/23644/5), I'll give it a shot.

**Comment by corevo** [comment] 2018-07-17 13:15
The current [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1408446) to follow.

**Comment by capoerafreak** [comment] 2018-12-17 22:10
Looks like this was closed in FF63 can anybody confirm that?

**Comment by corevo** [comment] 2019-01-09 18:45
We have a workaround in place for it, but even if it is closed, people might still use older Firefox versions, so we should keep the workaround in place, until we'll have to upgrade the minimum required version to 63, for now it is 56.

**Comment by toddtarsi** [comment] 2022-06-29 16:01
Closing this, as we're onto v4 in electron now.

**Closed by toddtarsi** 2022-06-29 16:01 UTC
Labels: confirmed
