### ISSUE TITLE
selenium-side-runner screenshot

### ISSUE THREAD

**Issue by jaysooon** [SeleniumHQ/selenium-ide#634] opened 2019-03-29 12:07 UTC
## 💬 Questions and Help

Is the side runner already had an screenshot? like taking a screenshot for the web driver (Nodejs) Thank you

**Comment by tourdedave** [comment] 2019-03-31 07:44
Duplicate of #182.

For questions and help, please see [the project's help page](https://www.seleniumhq.org/selenium-ide/help/). The issue tracker is for filing bugs and feature request.

**Closed by tourdedave** 2019-03-31 07:44 UTC
Labels: duplicate
