### ISSUE TITLE
Verify should issue a warning and not abort the test

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#464] opened 2018-10-24 12:00 UTC
It is my understanding that `verify` is a soft assert which should not abort a test - as documented:
![image](https://user-images.githubusercontent.com/498834/47428943-122f7880-d795-11e8-8f0d-d2b0b3b7eec0.png)

The IDE however treats `verify` just the same as  `assert` and aborts the test with an error:
![image](https://user-images.githubusercontent.com/498834/47428929-080d7a00-d795-11e8-91db-a11dfaa6f6cd.png)

See also:
> When a “verify” command fails, the test will continue executing and logging the failure. Mostly, the Verify command is used to check non-critical things. In such cases where we move forward even though the end result of the check value is failed.

https://www.softwaretestingmaterial.com/difference-between-assert-and-verify/

**Comment by tourdedave** [comment] 2018-10-24 12:35
That's right -- `verify` is a soft assert. All `verify` commands should respect this and continue execution of a test if unsuccessful.

When a `verify` command is unsuccessful the step will be marked with a failure indication in the log and the test will be marked as a failure as well. But it shouldn't halt the test.

Can you provide a test file that reproduces the issue?

**Comment by cawoodm** [comment] 2018-10-24 17:19
I don't know how to provide you with a test file but just run a verify statement in your test and you'll see it fails with an error.

**Comment by tourdedave** [comment] 2018-10-24 17:56
I asked for a repro case because I couldn't reproduce it earlier. But I got it now. It looks to be an issue with xpath locators. Other locator strategies appear to work fine, but I'll need to check all of them.

**Comment by tourdedave** [comment] 2018-10-24 18:04
Actually, I spoke too soon. I was running the wrong command with the wrong values (`verify` not `verify element present`). I'll look at this more tomorrow.

**Comment by tourdedave** [comment] 2018-10-25 06:15
Here's a sample project that demonstrates verify commands working.

[verify.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/2513521/verify.side.zip)

The verify commands fail, the test gets marked as a failure, but all of the commands in the test run.

We can use this as a starting point to find a repro case.

**Comment by tourdedave** [comment] 2019-05-15 08:28
@98gmarquee For `verify` commands, it won't pause. For `assert` it will.

Closing this issue due to prolonged inactivity.

**Closed by tourdedave** 2019-05-15 08:28 UTC
Labels: awaiting answer

**Comment by 98gmarquee** [comment] 2019-05-16 21:24
> 
> 
> @98gmarquee For `verify` commands, it won't pause. For `assert` commands it will.
> 
> Closing this issue due to prolonged inactivity.

Thanks. I was used to how the old ide worked as it would pause for failed "verify" commands if you had the button clicked.
