### ISSUE TITLE
how to convert selenium ide command to python in latest version?

### ISSUE THREAD

**Issue by makarun007** [SeleniumHQ/selenium-ide#211] opened 2018-05-28 06:29 UTC
in older version i click file->Export test case menu to convert my selenium ide command to java/python. 
But in newer version i doesn't know how to get?. can any one pls help me?

**Comment by corevo** [comment] 2018-05-28 06:32
Duplicate of #131

**Closed by corevo** 2018-05-28 06:32 UTC

**Comment by taufanbagusdpa** [comment] 2019-06-08 10:22
> in older version i click file->Export test case menu to convert my selenium ide command to java/python.
> But in newer version i doesn't know how to get?. can any one pls help me?

i cannot see export to python in my selenium IDE

**Comment by tourdedave** [comment] 2019-06-10 06:12
Code export for Java is currently all that's available. Python is coming next. You can track the progress of code export in #592.
