### ISSUE TITLE
Extension is injecting "prompt.js" into every page whether IDE is open or not

### ISSUE THREAD

**Issue by yozlet** [SeleniumHQ/selenium-ide#326] opened 2018-08-03 22:49 UTC
## 🐛 Bug Report

When browsing the web, the SeleniumIDE extension is injecting `assets/prompt.js` into every page I view. This happens even when the IDE is closed, and has not been opened at all during the browser session.

## To Reproduce

1. With Chrome: open Inspector, Network tab.
2. Browse to any page.
3. See the request for `prompt.js`, being made by the extension.

## Expected behavior

Surely this shouldn't be happening if the IDE isn't open?

## Environment

OS: Mac OS 10.13
Selenium IDE Version: 3.1.1
Browser: Chrome
Browser Version: 67.0.3396.99

**Comment by bobf** [comment] 2019-05-12 17:29
@yozlet Thank you for reporting - now I finally figured out why I keep seeing an error message in my console.

If it's useful for the devs, the error I was seeing was:

```
Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared
```
_Google Chrome_: `Version 73.0.3683.103 (Official Build) (64-bit)`

I didn't see any side-effects other than the console output. It went away as soon as I removed the plugin and it had previously been present on all websites (although I didn't test extensively).

**Comment by arichter83** [comment] 2019-05-16 08:19
Same here.

**Comment by vladpaln** [comment] 2019-06-25 22:49
Same error

`Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared`

Google Chrome: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by soccermatrix** [comment] 2019-08-13 12:44
This is still happening on Aug 2019

**Comment by corevo** [comment] 2019-08-13 12:49
@vladpaln I've browsed into multiple websites, and couldn't find any that reproduces this issue.

Currently it is required to inject the js into every page, or else one you open Selenium IDE, we would have to refresh all the browser pages, because of this, and the fact that we will move to electron, this issue will be fixed once moved to electron, as it will no longer affect the user's day-to-day browsing.

**Comment by williamhatch** [comment] 2019-08-19 00:56
it is still there.

**Comment by pbodnar** [comment] 2019-12-01 18:39
@corevo, can you please help me to understand the need "to inject the js into every page" when the Selenium IDE doesn't seem to run any command / test against an already opened page and it always opens a dedicated window instead? Is the Electron variant going to support running against an existing page like the other alternative tools do? Is it worth filing a new feature request for that?

**Comment by corevo** [comment] 2019-12-02 08:35
Scripts have to be injected at page load in order to Selenium IDE to be able to automate the page, although Selenium IDE opens a tab of its own to automate, there is no way (at least in Chrome, I know Firefox already has this), to dynamically differentiate tabs and their scripts.

What we did do, is that tabs that are not part of the automation, the scripts in them will "sleep", if it still creates friction you should open an issue, but currently all scripts have to be injected to all tabs, but in tabs that are not part of the test they are no-ops.

**Comment by pbodnar** [comment] 2019-12-05 18:15
@corevo , thanks for your explanation. Luckily, I haven't experienced a "friction" yet.

Regarding the second thing I wrote about, I've just simply created a new feature request - see #904.

**Comment by ricardomussolini** [comment] 2020-06-17 13:48
I'm deactivating Selenium while I'm not using the add-on. It completely solved my problems.

Pages were taking 15 seconds longer to open

passed for 2 seconds

Thank you

**Comment by bobvandevijver** [comment] 2020-08-07 07:00
Just saw this error pop up in our Sentry by somebody visiting one of our monitored sites:

```

**Comment by jdlrobson** [comment] 2020-10-23 19:08
We are rolling out error logging on Wikipedia right now and this error is one of our top errors to a level that could become problematic and we're delaying roll. Is anybody still looking into this problem or will we need to do something on our side to filter this out?

**Comment by alitorbati** [comment] 2020-10-23 20:35
@jdlrobson fwiw at my org we ended up filtering them out on our end. super noisy, and seemingly no fix coming from the source

**Comment by dustball** [comment] 2020-10-26 18:03
<img width="484" alt="Screen Shot 2020-10-26 at 1 03 24 PM" src="https://user-images.githubusercontent.com/123730/97210501-a6b98080-178b-11eb-832a-3b95690aa83a.png">

**Comment by RafiArsalan** [comment] 2022-06-27 09:43
> 

Did you filter in sentry logs ?

**Comment by toddtarsi** [comment] 2022-11-11 03:14
V4 uses a standalone binary, so this isn't an issue there.

**Closed by toddtarsi** 2022-11-11 03:14 UTC
Labels: content side effect
