### ISSUE TITLE
Alert from Firefox: Firefox running slowly due to Selenium IDE

### ISSUE THREAD

**Issue by ShanWehttam** [SeleniumHQ/selenium-ide#506] opened 2018-11-26 12:10 UTC
Firefox 63.0.3 (32-bit)
Windows 7
Selenium IDE 3.4.4

When i attempt to click a radio button on the page, a popup bar appears at the top of the page noting:  "A script in the extension "Selenium IDE" is causing firefox to slow down."  Within the popup i'm given 3 options:
"Temporarily disable extension on page", "Stop It" and "Wait".
This issue freezes the window and i'm unable to return to selenium IDE recorder without closing the window.
Only with radio buttons is this happening for me. I have not tried this in chrome as i dont need to use chrome
works fine when i run the script with webdriver Ruby bindings..

The "Select target on page" helper cannot seem to locate the radio button element in isolation, but i dont believe there is anything special about this.

input type="radio" name="ratePointForms[0].tenorType" value="O/N" id="gr-0" class="grid-radio"

Again, the page crashes when i use the "Select target on page" helper on this element

![for ide team](https://user-images.githubusercontent.com/22930688/49013247-f6443b80-f173-11e8-8b49-999a6bdbdd48.jpg)

Keep up the good work bringing IDE back to life.  I've missed it

Thanks
Matt

**Comment by corevo** [comment] 2018-11-26 12:33
Which website does this happen in?

**Comment by ShanWehttam** [comment] 2018-11-26 12:49
It occurs in an internal web page, so it's tricky to give you greater help to reproduce this at your end.
I'll see if i can reproduce it in a public facing app with radio btns, to be more help

**Comment by HSI-Ron** [comment] 2019-02-14 16:13
Firefox 64.0.2 64 bit.
Selenium IDE 3.5.6
Windows 10

I'm seeing a similar problem.  I'm new to Selenium and I'm a EE, not a software engineer, so I may be doing something wrong.

I had a few steps done, then clicked REC to add steps.  As I click survey responses, Selenium takes 2 - 10 seconds to record my clicks and eventually freezes.  

This first video clip (mp4) shows the FF script warning repeatedly being displayed.  
[selenium1.zip](https://github.com/SeleniumHQ/selenium-ide/files/2865829/selenium1.zip)
One thing that is slightly odd is that the video capture tool, Screenpresso, normally shows mouse clicks via an animated cursor.  That isn't happening while this browser is selected, but you can see it in the second clip.

In the second clip you can see I'm trying to stop recording, but clicking the Stop Recording button isn't working.
[cant stop2.zip](https://github.com/SeleniumHQ/selenium-ide/files/2865838/cant.stop2.zip)

I'll add more as I figure things out.
Ron

**Comment by tourdedave** [comment] 2019-02-14 16:24
Hey Ron,

We released a fix earlier today that addresses performance issues when
recording.

Can you try again with version 3.5.7 of the IDE?


Cheers,
Dave H

בתאריך יום ה׳, 14 בפבר׳ 2019 ב-18:13 מאת HSI-Ron <notifications@github.com>:

**Comment by HSI-Ron** [comment] 2019-02-14 16:27
Thanks Dave, I'll give the new version a try (hopefully today).

**Comment by HSI-Ron** [comment] 2019-02-14 17:24
3.5.7 appears to have fixed the problem I was having.  Thanks!

**Comment by tourdedave** [comment] 2019-02-14 17:49
Terrific! \o/

**Comment by dleigh** [comment] 2019-03-09 14:57
I'm on 3.5.8 and I have the same problem in both Firefox: 65.0.2 (64-bit) and Chrome: Version 72.0.3626.121 (Official Build) (64-bit).  Is it possible it regressed in 3.5.8?  I can't use the field selector at all.  It starts racking up CPU and gives me the option to wait or kill it.  I can click wait repeatedly but it doesn't help and finally I have to kill it.

**Comment by tourdedave** [comment] 2019-03-10 07:36
@dleigh Can you share what site you're testing against and the flow you take through it? It would help us narrow down where to look.

**Comment by halbri** [comment] 2019-05-14 11:41
Hi 
I seem to be having this same issue with the latest version of Firefox, 66.0.5 and latest version of selenium 3.7.1
The issue occurs at the same point each time i attempt this, entering textarea.  It is a local web page.
Thanks

**Comment by tourdedave** [comment] 2019-05-14 13:26
I'm going to close this issue since the OP confirmed this issue was resolved months ago.

@dleigh & @halbri Please open a new issue by using the issue template to give as much detail as possible so we can see about reproducing the performance issue.

**Closed by tourdedave** 2019-05-14 13:26 UTC
Labels: reproducer required, unconfirmed
