### ISSUE TITLE
Selenium IDE is not working on Ubuntu Linux - 18.04 with Firefox Browser

### ISSUE THREAD

**Issue by barotashish** [SeleniumHQ/selenium-ide#202] opened 2018-05-21 04:39 UTC
Setup Details :- 

OS :- Ubuntu 18.04
Browser :- Firefox 60.0 (64-bit) 
Selenium Plugin Details  :- Selenium IDE - 3.0.2.0

I am attaching the screenshot for the same. 

Can anyone guide me, how can I troubleshoot it? 

Thank you in advance. 

Best Regards,
Ashish Barot. 

![screenshot from 2018-05-21 10-07-04](https://user-images.githubusercontent.com/21197417/40290895-ee0bd7cc-5cde-11e8-8460-c1cb4fd6eb3b.png)

**Comment by corevo** [comment] 2018-05-21 07:27
Duplicate of #61

**Closed by corevo** 2018-05-21 07:27 UTC
