### ISSUE TITLE
When I open a "side" file with one already open, the old file stays.  I have to close my window and reopen one to get a new side file to appear.

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#309] opened 2018-07-18 12:36 UTC
## Meta -
OS:  Windows 10

Selenium IDE Version:  3.1.0

Selenium SIDE Runner Version:  

Node version:  

Browser:  Chrome

Browser Version:   67.0.3396.99 64 bit

## Expected Behavior -
Opening new file should change the IDE steps to the new file
## Actual Behavior -
File appears to have been open, but contents do not change, must close IDE and reopen to get new file

**Comment by Jongkeun** [comment] 2018-07-19 00:20
It looks like that when you open the same file.
Right @Kielmed?

**Comment by corevo** [comment] 2018-07-19 06:32
I can't reproduce this behavior, can you post a sample project file with the issue and steps to reproduce this?

**Comment by Kielmed** [comment] 2018-07-19 12:19
Right
________________________________

**Comment by Kielmed** [comment] 2018-07-20 12:32
I work around this by closing the Selenium Window rather than using the File Open process.

**Comment by tourdedave** [comment] 2018-11-14 10:06
This was fixed in 0f58de03acfc4a94b2b3bcab00860427114d8fbe

**Closed by tourdedave** 2018-11-14 10:06 UTC
Labels: awaiting answer
