### ISSUE TITLE
Selenium IDE

### ISSUE THREAD

**Issue by rcracer20071** [SeleniumHQ/selenium-ide#872] opened 2019-11-11 15:44 UTC
## 🐛 Bug Report ##

All previously created Selenium IDE scripts are skipping tests. When I run it with run all command button i get the below behaviour (using multiple different test files).

1st Test - Runs Correctly
2nd Test - Runs Correctly
3rd Test - Selenium Skips it (no errors)
4th Test - Runs Correctly
5th Test - Selenium Skips it (no errors)

Please note if I re-order the tests

1st Test - Runs correctly
3rd Test - Runs correctly
2nd Test - Selenium skips it (no errors)

Or if I run each test singularly they run correctly

I believe that this is related to the latest 3.15 release, this was working on Friday before the update

**Comment by tourdedave** [comment] 2019-11-11 18:22
Duplicate of #873

**Closed by tourdedave** 2019-11-11 18:22 UTC
