### ISSUE TITLE
Selenium IDE - Playback functional change to element "Target" 

### ISSUE THREAD

**Issue by NagendraKuppala** [SeleniumHQ/selenium-ide#229] opened 2018-06-11 17:40 UTC
Hello,

Is there way to force Selenium IDE to look for all the available/possible Target values for an element from the Target dropdown (ie: ID , Name, Link, CSS, XPath).

I have web application with webix, which means the elements ID's of the web page will dynamically changes every time I login to the application. 
So, that is making my test case execution to fail because by default the recorder is selecting find element by ID target as the Selenium IDE element target values preferred order is ID, Name, Link, CSS and xPath. 

Current execution scenario:
1. Recorder records a test case by clicking "Record" button.
2. Play back the test case by clicking on "Play or Play Suite or Play All" button. (Test case executes with the selected/shown target value)

Expected execution scenario: 
1. No change. (same as step-1 of current execution scenario)
2. Play back the test case by clicking on "Play or Play Suite or Play All" button. (Execute test case by looping through all the available Element Target Values like (ID, Name, Link, CSS, Xpath) before test case fail due element not found exception).

If in case the element target 'ID' changed while test case play back, loop and look for next alternative element target selector from Target dropdown 'Name' (if still not found) --loop-> 'Link' --> etc . Before sending 'Element not found' error and Test case fail. If all the alternative element targets are really not found then throw 'Element not found' error and Test case fail.

Thanks in advance.

**Comment by corevo** [comment] 2018-06-13 10:07
Duplicate of #150.  
This is a detailed explanation of the issue at hand, if you don't mind to please repost it there as well, as I will close this.  
We have plans to implement this soon.

**Closed by corevo** 2018-06-13 10:07 UTC
