### ISSUE TITLE
Created .side file with Chrome on Windows 7 and tried to run it with SIDE Runner on Red Hat Enterprise Linux 7.5, but it wouldn't work.

### ISSUE THREAD

**Issue by BlinkBolt** [SeleniumHQ/selenium-ide#287] opened 2018-07-06 22:09 UTC
## Meta -
OS:  

Windows 7 Enterprise and Red Hat Enterprise Linux 7.5

Selenium IDE Version:  

3.1.1 for Chrome (on Windows 7 Enterprise)

Selenium SIDE Runner Version:  

0.7.0 (also tried 0.5.0 and got the same error)

Node version:  

10.6.0

Browser:  
Chrome (on Windows 7 Enterprise)

Browser Version:  

Version 67.0.3396.99 (Official Build) (64-bit)

## Expected Behavior -
Expected .side file to run.  Tried it with and without a Test Suite in the .side file.  Got the same error.

## Actual Behavior -
Got this message:
error:   The project eRA Websites is of older format, open and save it again using the IDE.

## Steps to reproduce -

**On Red Hat Enterprise Linux 7.5:**
$ uname -a
Linux abydos.era.nih.gov 3.10.0-862.3.2.el7.x86_64 #1 SMP Tue May 15 18:22:15 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
$ selenium-side-runner era-websites.side
error:   The project eRA Websites is of older format, open and save it again using the IDE.

$ 

**.side.yml:**
capabilities:
  browserName: "chrome"

**era-websites.side (with Suite):**
{
  "id": "41e41cfe-1d2c-47da-af3c-d2da16fa0b39",
  "name": "eRA Websites",
  "url": "https://jira.era.nih.gov",
  "tests": [{
    "id": "269344a5-305a-457c-8c64-1f68d33dc6b8",
    "name": "jira.era.nih.gov",
    "commands": [{
      "id": "218f647b-b2dd-4680-8c72-5eae80b0dd33",
      "comment": "",
      "command": "open",
      "target": "/secure/Dashboard.jspa",
      "value": ""
    }, {
      "id": "a460d74a-2bb2-426a-a3fd-35f94694a1f0",
      "comment": "",
      "command": "type",
      "target": "id=login-form-username",
      "value": "_DELETED_"
    }, {
      "id": "f4edd481-0128-442c-bfa1-c6e4b68ce825",
      "comment": "",
      "command": "type",
      "target": "id=login-form-password",
      "value": "_DELETED_"
    }, {
      "id": "3661ccaf-219c-43db-9283-263302d5f995",
      "comment": "",
      "command": "clickAt",
      "target": "id=login",
      "value": "-943,-292"
    }, {
      "id": "66cd36cc-bc4e-4044-8be3-6be3c13e2bf9",
      "comment": "",
      "command": "clickAt",
      "target": "id=log_out",
      "value": "0,-196"
    }]
  }],
  "suites": [{
    "id": "b98fedf3-15ee-4c71-87d3-10c02669adbc",
    "name": "Default Suite",
    "parallel": false,
    "timeout": 300,
    "tests": ["269344a5-305a-457c-8c64-1f68d33dc6b8"]
  }],
  "urls": ["https://jira.era.nih.gov/"],
  "plugins": [],
  "version": "1.0"
}

**era-websites.side (without Suite):**
{
  "id": "41e41cfe-1d2c-47da-af3c-d2da16fa0b39",
  "name": "eRA Websites",
  "url": "https://jira.era.nih.gov",
  "tests": [{
    "id": "269344a5-305a-457c-8c64-1f68d33dc6b8",
    "name": "jira.era.nih.gov",
    "commands": [{
      "id": "218f647b-b2dd-4680-8c72-5eae80b0dd33",
      "comment": "",
      "command": "open",
      "target": "/secure/Dashboard.jspa",
      "value": ""
    }, {
      "id": "a460d74a-2bb2-426a-a3fd-35f94694a1f0",
      "comment": "",
      "command": "type",
      "target": "id=login-form-username",
      "value": "_DELETED_"
    }, {
      "id": "f4edd481-0128-442c-bfa1-c6e4b68ce825",
      "comment": "",
      "command": "type",
      "target": "id=login-form-password",
      "value": "_DELETED_"
    }, {
      "id": "3661ccaf-219c-43db-9283-263302d5f995",
      "comment": "",
      "command": "clickAt",
      "target": "id=login",
      "value": "-943,-292"
    }, {
      "id": "66cd36cc-bc4e-4044-8be3-6be3c13e2bf9",
      "comment": "",
      "command": "clickAt",
      "target": "id=log_out",
      "value": "0,-196"
    }]
  }],
  "suites": [],
  "urls": ["https://jira.era.nih.gov/"],
  "plugins": [],
  "version": "1.0"
}

**Comment by corevo** [comment] 2018-07-08 08:32
Duplicate of https://github.com/SeleniumHQ/selenium-ide/issues/212#issuecomment-401753630

**Closed by corevo** 2018-07-08 08:32 UTC

**Comment by BlinkBolt** [comment] 2018-07-09 01:37
Can you tell me the last combinations of versions of the Chrome for Windows IDE and SIDE Runner that will actually work together?

-------- Original message --------From: Tomer Steinfeld <notifications@github.com> Date: 7/8/18  4:33 AM  (GMT-05:00) To: SeleniumHQ/selenium-ide <selenium-ide@noreply.github.com> Cc: Beam Davis <github@beamrider.com>, Author <author@noreply.github.com> Subject: Re: [SeleniumHQ/selenium-ide] Created .side file with Chrome on
  Windows 7 and tried to run it with SIDE Runner on Red Hat Enterprise Linux
  7.5, but it wouldn't work. (#287) 
Duplicate of #212 (comment)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SeleniumHQ/selenium-ide","title":"SeleniumHQ/selenium-ide","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/SeleniumHQ/selenium-ide"}},"updates":{"snippets":[{"icon":"PERSON","message":"@corevo in #287: Duplicate of https://github.com/SeleniumHQ/selenium-ide/issues/212#issuecomment-401753630"}],"action":{"name":"View Issue","url":"https://github.com/SeleniumHQ/selenium-ide/issues/287#issuecomment-403272010"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SeleniumHQ/selenium-ide/issues/287#issuecomment-403272010",
"url": "https://github.com/SeleniumHQ/selenium-ide/issues/287#issuecomment-403272010",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [SeleniumHQ/selenium-ide] Created .side file with Chrome on Windows 7 and tried to run it with SIDE Runner on Red Hat Enterprise Linux 7.5, but it wouldn't work. (#287)",
"sections": [
{
"text": "",
"activityTitle": "**Tomer Steinfeld**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@corevo",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"SeleniumHQ/selenium-ide\",\n\"issueId\": 287,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/SeleniumHQ/selenium-ide/issues/287#issuecomment-403272010"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353916326\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by corevo** [comment] 2018-07-09 07:02
You can get the newest beta [here](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.2.0-beta.1).  
Which also explains how to get the accompanying runner.

**Comment by BlinkBolt** [comment] 2018-07-09 14:12
I downloaded an installed the beta IDE for Chrome for Windows and installed the beta SIDE Runner on Red Hat Enterprise Linux 7.5, and now I'm getting this error:

$ selenium-side-runner eRA\ Websites.side
 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'quit' of undefined

      at WebdriverEnvironment.teardown (../../../usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:32:30)
          at Generator.throw (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.218s
Ran all test suites.

$

**Comment by BlinkBolt** [comment] 2018-07-09 14:33
BTW, this is the output from installing SIDE Runner on Red Hat Enterprise Linux 7.5:

# npm install -g selenium-side-runner@beta
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
/usr/bin/selenium-side-runner -> /usr/lib/node_modules/selenium-side-runner/dist/index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/selenium-side-runner/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ selenium-side-runner@3.2.0-beta.1
updated 3 packages in 19.786s
#

**Comment by corevo** [comment] 2018-07-10 14:16
It seems your issue is the same as #289 
The optional dependencies are for macOS only, as they are optional the runner can run flawlessly without them.
