### ISSUE TITLE
open webpage in incognito window to ignore sessions

### ISSUE THREAD

**Issue by goutham2945** [SeleniumHQ/selenium-ide#1028] opened 2020-04-27 10:10 UTC
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

## Motivation

Please outline the motivation for the proposal.

## Example

Please provide an example for how this feature would be used.

**Comment by corevo** [comment] 2020-04-27 10:23
Duplicate of #914

**Closed by corevo** 2020-04-27 10:23 UTC
