### ISSUE TITLE
Use of wildcard or .contains in Selenium IDE (chrome extension)

### ISSUE THREAD

**Issue by RomanArberg** [SeleniumHQ/selenium-ide#825] opened 2019-09-25 12:02 UTC
Hi guys,

I am using blazedemo.com for training purposes and I want to verify the first word in <h1> element "Thank you for your purchase today!"  (last step in ordering process). 
Thus I want to do .contains("Thank") assertion and ignore the rest of the sentence. I've tried to use xpath in "value" field with no luck.... And as I understand wildcard is not implemented in the newest IDE. How can I solve the problem?

Best regards,
Roman

![contains_problem](https://user-images.githubusercontent.com/34095201/65599014-11065d00-df9d-11e9-893e-5e969a3041da.JPG)

**Comment by corevo** [comment] 2019-09-25 12:08
Duplicate of #141

**Closed by corevo** 2019-09-25 12:08 UTC

**Comment by 98gmarquee** [comment] 2019-09-25 14:33
Using "verify element present" use this for the target:
`//h1[starts-with(.,'Thank')]`
And clear out the value field.

Appears to work.
![2019-0925-gitHub-selide-tkt825](https://user-images.githubusercontent.com/33339926/65610829-84957380-df77-11e9-8fe9-1eab0f8886bd.jpg)
