### ISSUE TITLE
Selenium IDE v3.1.1 (Chrome) doesn't capture type command without clicking outside on google.com

### ISSUE THREAD

**Issue by tvasenin** [SeleniumHQ/selenium-ide#332] opened 2018-08-10 11:56 UTC
## 🐛 Bug Report

Selenium IDE v3.1.1 (Chrome) doesn't capture **type** command in search field on **google.com**.

On Firefox 61.0.2 (using the same Selenium IDE version) everything is OK.

## To Reproduce

- Start capture on https://google.com
- Type anything in search field and press ENTER
- Stop capture

## Expected behavior

**type** command with the search string (along with **send keys** command for ENTER key press) should be captured.

## Environment

OS: **Windows 10 1803**
Selenium IDE Version:  **3.1.1**
Browser: **Chrome**
Browser Version: **68.0.3440.106** (Official Build) (64-bit)

**Comment by corevo** [comment] 2018-08-12 07:17
Quoting from the [recording docs](https://www.seleniumhq.org/docs/02_selenium_ide.jsp#recording)
>The type command may require clicking on some other area of the web page for it to record.  

It due to the way some websites handle the typing events and the way it propagates to the IDE, by clicking outside I can confirm the command is recorded.  
That being said it is not ideal, and the experience should be more fluid.

**Comment by corevo** [comment] 2018-08-20 11:11
Fixed in 757740fd89029e7f3b9149df1a8a464fc311b768

**Closed by corevo** 2018-08-20 11:11 UTC
Labels: help wanted, record
