### ISSUE TITLE
Add multiline copy/past

### ISSUE THREAD

**Issue by adrien-bertrand** [SeleniumHQ/selenium-ide#630] opened 2019-03-25 09:21 UTC
Hi, 
if its possible to add this feature 
Thanks 

## 🚀 Feature Proposal

Allow to copy/paste some row to easily update scenarios using the same functions in different places. 

## Motivation

It's possible to do it using a code editor but i need to edit every "id" elements after.
yesterday  i had to copy 96 lines in a lot of tests.

**Comment by corevo** [comment] 2019-03-25 09:32
Duplicate of #189

**Closed by corevo** 2019-03-25 09:32 UTC

**Comment by corevo** [comment] 2019-03-25 09:33
Also if your use-case is to use the same piece of functionality in multiple places the best practice is to use the [run](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#run) command.
