### ISSUE TITLE
Can we add "smart save" like is standard in MS Windows (i.e., remember file location)

### ISSUE THREAD

**Issue by luquitia** [SeleniumHQ/selenium-ide#441] opened 2018-10-04 17:01 UTC
## 🐛 Bug Report

The new Selenium IDE, when updating an existing .side project, does not remember either its location when I want to save it. It reverts shows some Windows default location like "Downloads" (or whatever most recent/used location is).  

Can you add support to store and remember the file location, so this can be called when I click Save button?

Nice to have: Save as is VS. Save as new buttons/functions
    A. Save as is would save with current file name in same file location (overwriting previous save for existing file).
    B. Save as new would open the windows folder save dialogue (and default to current file name and location).
(but this choice is not essential; if it has only one Save button, but can just remember current file name and location, that would be very helpful on its own.)

![image](https://user-images.githubusercontent.com/40441405/46489742-33272e00-c7d4-11e8-87d6-d6504e0dfa7e.png)

As a side note, even the file name is wrong; it seems the stored file name is inherited from parent file (I had saved as new file name, but it incorrectly "remembers" the original/parent file name).

## To Reproduce

Take any existing .side script stored on your desktop C: drive > open in the new Selenium IDE plugin.
1. Save (with original file name)
--it "forgot" where you opened the file from; it just shows windows default location (as if it were brand new file)
2. navigate to desired C: location and save with new file name.
now, Save (for updated file name)
--it "remembers" wrong (previous) file name; and "forgets" location

## Expected behavior

It should remember the current file name and location on Save, which should default to most recently saved (or opened) file name and most recently saved (or opened) location. "(or opened)" applies only if file has been opened but not yet saved in current session.

## Project file reproducing this issue (highly encouraged)

This happens with Save for any .side file I test with.

## Environment

OS: Windows 10
Selenium IDE Version:  3.3.1
Browser: Firefox Quantum
Browser Version: 62.0.3

**Comment by corevo** [comment] 2018-10-04 17:11
Duplicate of #363

**Closed by corevo** 2018-10-04 17:11 UTC
