### ISSUE TITLE
Not stop anymore on assert command

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#239] opened 2018-06-14 16:13 UTC
Hi,

Is it possible to stop the test when an assert command returns false?
With Selenium IDE Firefox version 3.0.3.0

Thank you by advance.
AyaSF

**Comment by hohnan** [comment] 2018-06-14 17:38
Was just running a test today and noticed the same thing. Assert element present is performing the same as verify element present. It should end the test case on the spot.

**Comment by corevo** [comment] 2018-06-14 18:06
Duplicate of #89.  
This is a long await fix, it's already in master, and will go live in 3.1.0, sorry for the long wait.

**Closed by corevo** 2018-06-14 18:06 UTC

**Comment by AyaSF** [comment] 2018-06-14 18:17
Sorry for the duplicate issue and thank by advance for your fix.
