### ISSUE TITLE
Plugin to add a button to send to selenium grid provider

### ISSUE THREAD

**Issue by dvd900** [SeleniumHQ/selenium-ide#575] opened 2019-02-14 18:26 UTC
## Motivation

I'm a selenium tester who pays a selenium grid provider. As a part of my workflow, I want to run my tests on different operating systems and browsers through the UI. 

## Question

Is it possible to define and extend views within selenium ide with a plug-in?

**Comment by corevo** [comment] 2019-02-21 13:34
This will be included as part of the standard functionality of Selenium IDE in the future.  
Duplicate of #7

**Closed by corevo** 2019-02-21 13:34 UTC
