### ISSUE TITLE
The old test suite when imported in new selenium IDE V3.0.3 is not opening the test scripts in the order. Test scripts are visible in Ascending order. How to order test scripts in test suite as I want?

### ISSUE THREAD

**Issue by RiniTapasya** [SeleniumHQ/selenium-ide#243] opened 2018-06-15 09:57 UTC
## Meta -
OS:  
 Win7 64bit
Selenium IDE Version:  
V3.0.3
Browser:  Mozilla Firefox

Browser Version:  
60.0.2

## Steps to reproduce - Import the test suite. Then import the shown test scripts one by one. 
The dialog will close automatically and the test scripts are visible in alphabetical order.

Note : Run test suite button is disabled. So I can run only the "test scripts" one by one. Not whole test suite.

**Comment by corevo** [comment] 2018-06-15 10:08
Duplicate of #127

**Closed by corevo** 2018-06-15 10:08 UTC
