### ISSUE TITLE
Getting Crash most of the times - This extension may have been corrupted.

### ISSUE THREAD

**Issue by Rajib-Codereadr** [SeleniumHQ/selenium-ide#818] opened 2019-09-19 09:31 UTC
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment] 2019-09-19 10:01
Duplicate of #782

**Closed by corevo** 2019-09-19 10:01 UTC
