### ISSUE TITLE
side-runner v4 not working - it does not change URL or execute tests

### ISSUE THREAD

**Issue by karasma3** [SeleniumHQ/selenium-ide#1532] opened 2022-10-07 09:31 UTC
## 🐛 Bug Report

Selenium tests are not executed when run with selenium-side-runner.

Browser with the url `data:,` is shown and nothing happens.
![image](https://user-images.githubusercontent.com/17758032/194518304-a51b6aeb-c0c4-4ef5-8a15-4590d7f188eb.png)
Log of the executed selenium-side-runner
```
selenium-side-runner selenium/*.side

info: Running test TC8✔️  - Address search #6                
info: Building driver for chrome

 RUNS  node_modules/@seleniumhq/side-runner/dist/main.test.js
info: Driver has been built for chrome                       
                                                             
 RUNS  node_modules/@seleniumhq/side-runner/dist/main.test.js
 RUNS  node_modules/@seleniumhq/side-runner/dist/main.test.js
 RUNS  node_modules/@seleniumhq/side-runner/dist/main.test.js
```

I am using v4 side-runner.
@toddtarsi 
Why? Because with the version 3.17.0 i cant the same issue as in #996 
I am more than happy to give you any feedback on developing the v4. We are working on a projects where testers are creating tests using Selenium IDE and executing them. We now wanted to make the runs automatic with selenium-side-runner running in the Gitlab CD/CD pipelines. With 3.17.0 it is working, but some of the tests fail, even though they are passing in Selenium IDE.

## To Reproduce

npm i -g @seleniumhq/side-runner
selenium-side-runner *.side
It logs info about some of the test is running. For example `info: Running test TC8✔️  - Address search #6 `
It logs that driver has been built for chrome `info: Driver has been built for chrome`
It will open browser with URL: `data:,` and nothing happens.

I let it run for the whole night and it did not finish the run.

## Expected behavior

Tests are executed and results are generated.

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.
https://drive.google.com/file/d/1qfteyEuCx2W8DH0TFg_jnTHdzzsx4zTX/view?usp=sharing

## Environment

OS: Windows 10 Pro
Selenium SIDE Runner Version:  4.0.0-alpha-15
Node version: 16.14
Browser: Google Chrome
Browser Version: Chrome 105.0.5195.127 (64-bit)

**Comment by toddtarsi** [comment] 2022-10-07 12:23
@karasma3 - Can you include a reproduction side file? I use this browser, runner version, and node version without issue on my mac and in my linux CI. There are windows users as well out there not having this issue.

**Comment by karasma3** [comment] 2022-10-07 13:29
@toddtarsi is the link for the google drive not working? https://drive.google.com/file/d/1qfteyEuCx2W8DH0TFg_jnTHdzzsx4zTX/view?usp=sharing

**Comment by toddtarsi** [comment] 2022-10-07 13:31
@karasma3 - oh neat i diidn't realize this was included thanks

**Comment by karasma3** [comment] 2022-10-19 19:54
Hello @toddtarsi , do you have something why would side-runner not finish the tests? As i mentioned it prints that it is running the test, but nothing happens.

**Comment by toddtarsi** [comment] 2022-11-10 05:01
@karasma3 - Sorry this is so late in responding, I was going through a bit of a phase. Eh, maybe I still am. The side-runner has gone through about 10 or more versions since the last time this issue was discussed. Is it still occurring on the latest release?

**Comment by toddtarsi** [comment] 2022-11-10 05:07
@karasma3 - I took a look at your side file, but tbh it is really big and I kind of glazed over. If it's still occurring, please reduce it down to the minimal amount of tests and steps to make the issue happen.

**Comment by karasma3** [comment] 2022-11-10 08:20
@toddtarsi on https://www.npmjs.com/package/@seleniumhq/side-runner i can only see 4.0.0.-alpha-15 which i have problems with and on github 4.0.0-alpha-17.... can you publish it to npmjs registry?

**Comment by toddtarsi** [comment] 2022-11-10 12:34
@karasma3 - I know the issue! @seleniumhq/side-runner was causing naming conflicts because bin files don't allow that namespacing, so it was still using selenium-side-runner for the bin and v3 would overwrite it, so I eventually gave up and started using the selenium-side-runner package name again. It's up to 4.0.0-alpha.26 😄

**Comment by karasma3** [comment] 2022-11-11 09:52
okay, so now with the new version `4.0.0-alpha28` the tests run so thank you for your Guidance.

But i have one more question...
@toddtarsi does `output-directory` option still work on v4? `--output-directory=results`
Because in v3 it worked and it created .json file with test output.... now my directory is empty

**Comment by toddtarsi** [comment] 2022-11-11 12:59
@karasma3 - Not yet. I'm going to close this issue, but please open one for output-directory if thats important to your work flow.

**Closed as completed by toddtarsi** 2022-11-11 12:59 UTC
