### ISSUE TITLE
save project

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#236] opened 2018-06-14 16:04 UTC
Hi,

When using CTRL+S to saving project, Selenium always ask us the path to save.
With Selenium IDE Firefox version 3.0.3.0

Is it possible to save as the same file without asking?

Thank you by advance,
AyaSF

**Comment by corevo** [comment] 2018-06-14 18:00
Duplicate of #116

**Closed by corevo** 2018-06-14 18:00 UTC

**Comment by AyaSF** [comment] 2018-06-16 11:44
Hi,

The issue 116 is closed.
Is it possible to reopen one of those to find a solution?

Thanks a lot by advance,
AyaSF

**Comment by corevo** [comment] 2018-06-16 12:01
I'm afraid that unless you can convince both Mozilla and Chrome to change their mind, it is simply impossible.

**Comment by corevo** [comment] 2018-06-16 12:28
It's not abnormal behavior of the browser, in fact it is the correct behavior, letting Selenium IDE access your computer, will basically let any extension access your computer, including sending all your files to a distanced server.  
It is actually quite correct, and I support that, fun fact the guy who created Nodejs recently said he regretted not putting the same mechanism in Node too.

**Comment by corevo** [comment] 2018-06-16 12:30
More over if you'd really like that changed, open an issue at [Bugzilla](https://bugzilla.mozilla.org/), if they resolve it then I'd be more than happy to implement it.  
You want to ask to "Allow webextension to access the filesystem", you can link to this issue.
