### ISSUE TITLE
Chrome Extension stuck in infinite loop on site

### ISSUE THREAD

**Issue by ChadKillingsworth** [SeleniumHQ/selenium-ide#263] opened 2018-06-25 21:51 UTC
When loading a large single page app, this extension gets stuck in an infinite loop and locks up the tab. It takes progressively more and more memory. I've verified that this occurs with the Chrome extension on both Windows and Mac.

Of note: the site in question uses Web Components and Shadow DOM. I do not know if that effects the issue or not.

By pausing the script execution in the dev tools, I get the following stack trace. I can infinitely step through the top `getframeLocation` call.

```
getframeLocation (injector.js:42102)
./content/record-api.js (injector.js:42102)
__webpack_require__ (injector.js:30)
./content/prompt-injector.js (injector.js:42059)
__webpack_require__ (injector.js:30)
1 (injector.js:50730)
__webpack_require__ (injector.js:30)
(anonymous) (injector.js:73)
(anonymous) (injector.js:76)
webpackUniversalModuleDefinition (injector.js:7)
(anonymous) (injector.js:10)
```

**Comment by corevo** [comment] 2018-06-26 07:39
What might affect this is frames, can you tell me the frame structure in your app?

**Comment by ChadKillingsworth** [comment] 2018-06-26 11:49
The main page where this is happening uses [ChartJS](https://www.chartjs.org/). It draws on a canvas in an iframe.

<img width="864" alt="screen shot 2018-06-26 at 6 46 54 am" src="https://user-images.githubusercontent.com/1247639/41909551-e464e6a6-790c-11e8-9b84-acceba74774d.png">

It's not nested inside ShadowDom in this case, but is the light dom child of a custom element.

**Comment by corevo** [comment] 2018-06-26 11:52
Shadow DOM is highly unlikely to affect this, that function mostly looks for `iframes`.  
Thanks for the info, I'll try to reproduce this.

**Comment by corevo** [comment] 2018-06-26 12:04
It's not ChartJS inside an `iframe` alone, perhaps something is nested inside the `iframe`?  
Can you give me a better picture of the DOM?

**Comment by corevo** [comment] 2018-06-26 12:28
Can you remove remove the charts and confirm for me wether the issue persists?

**Comment by Cobaltikus** [comment] 2019-07-05 17:58
I am experiencing this issue as well. It seems to me a bug in Selenium due to its assumption that window.frames is automatically kept in sync when iframes are added dynamically. But this assumption is false. If the iframe is added dynamically using document.createElement("IFRAME"), then theIFrame.contentWindow.parent.frames does not contain theIFrame, thus the infinite loop is encountered. I am currently working around this with some ugly code that explicitly sets window.frames to a new array that I create. Selenium would need to add a check to this function to make sure that it found something, and if it didn't, then find it using getElementsByTagName("IFRAME") - this would fix the bug.

**Comment by corevo** [comment] 2019-07-05 18:01
Thank you for researching this problem.

**Comment by Cobaltikus** [comment] 2019-07-08 14:23
I fixed this in a PR - if approved and merged etc.

**Comment by Cobaltikus** [comment] 2019-07-08 22:37
I take it back. I closed the PR. The issue was on my side, not Selenium's. I had a rogue line of code that was clobbering window.length and window.frames is just an alias for window so it clobbers window.frames.length as well.

var i ; length = 0;

instead of

var i , length = 0;

window.frames.length should be dependable.

**Comment by tourdedave** [comment] 2019-08-29 06:44
This appears to be resolved. Closing. Let us know if there's still a problem.

**Closed** 2019-08-29 06:43 UTC
