### ISSUE TITLE
Assert command is not behaving as expected for validation text / Element in Selenium IDE

### ISSUE THREAD

**Issue by dewanganbasant21** [SeleniumHQ/selenium-ide#163] opened 2018-04-19 18:27 UTC
Record a test script using selenium IDE.

Use Validation of error message and WebElement 
 
Used both command verify Text and assert Text.

here obeserving - Assert Text command is not behaving as expected,  if expected text or element is not available during execution, actual case then it should be stop execution at same step and test case should be fail.

assert is behaving as verify command. 

after completion of test execution , giving failure.

**Comment by dewanganbasant21** [comment] 2018-04-19 18:28
configured new version .. 3.1.0 beta.

**Comment by corevo** [comment] 2018-04-20 09:50
Duplicate of #89

**Closed by corevo** 2018-04-20 09:50 UTC

**Comment by corevo** [comment] 2018-04-20 09:53
Just as a note, I'm aware, and there's a fix, but it's not merged atm
