### ISSUE TITLE
captureEntirePageScreenshot command is not available

### ISSUE THREAD

**Issue by QA1MTG** [SeleniumHQ/selenium-ide#182] opened 2018-05-03 15:00 UTC
My automation testing relies heavily on screenshot generation as a part of our testing capabilities.  Currently it's not available.  Is there an alternative or will this feature be added in?

**Comment by corevo** [comment] 2018-05-03 15:04
Taking screenshots is not a problem.
The problem is that other than downloading them we can't save them.
Much like the way when you save the project it downloads instead.
Would downloading screenshots suffice?

Cheers,
Tom

**Comment by QA1MTG** [comment] 2018-05-03 15:15
When I execute the old screenshot command, the screenshots are saved locally and then we make PDFs to distribute to our teams.  It's been a real vital part of our testing strategy, and it's helped us quickly establish visual coverage of our systems.  

If it's automatically making screenshots and downloading them, how would the mechanism work?  Would the screenshots be automatically numbered?  Would there be a limit to the number of screenshots made?

Is there a reason the old command can't be added back (just asking out of curiosity)

**Comment by corevo** [comment] 2018-05-03 15:52
No limits on any number of screenshots I was thinking a command like so
`takeScreenshot | name of screenshot | format`.  
This gives the most flexibility imo.  
  
I'll answer the curiosity in the other issue, where it's more relevant.

**Comment by QA1MTG** [comment] 2018-05-03 15:54
thanks. as long as I can access that screenshot and use it for the PDF docs when I need that would be perfect.

**Comment by corevo** [comment] 2018-06-25 07:20
We have just released a [plugin system](https://github.com/SeleniumHQ/selenium-ide/wiki/Getting-Started-with-Plugins), I can't give you an ETA, on when we'll ship something like this.  
But it is absolutely possible to use this plugin system for that.

**Comment by idefix1** [comment] 2018-06-26 15:54
Just as a pointer: The kantu ide  can [take full page screenshots](https://a9t9.com/kantu/docs/webextensions/selenium-ide/capturescreenshot) and then stores them in the browser local storage (and can [export them](https://a9t9.com/kantu/docs/webextensions/selenium-ide/localstorageexport)). 

> But it is absolutely possible to use this plugin system for that.

Not me, but maybe someone that knows more about Javascript can write a plugin ;)

**Comment by corevo** [comment] 2018-09-21 08:41
Selenium is an opensource project, and as such work on community issues is based on contributors free time.  
The project does not give timeframes on any pending ticket, if it is highly urgent, I suggest sending a pr.

**Comment by dmitrymurashenkov** [comment] 2019-01-27 16:38
I'd like to describe case we have in our company that may help shape this feature.

In our company Selenium IDE is used by manual QA testers who often have troubles adding any verification logic, even basic one. Second point is that many bugs we face are problems with html layout and can't be automatically verified easily. So we rely on screenshots.

A nice feature would be to have a "screenshots log" like Katalon Recorder for Chrome does. So you run tests and then manually go through all screenshots to check that everything looks okay. Although not fully automated, it saves a lot of time when a single test case requires filling 20 forms with 10 fields each.

Perhaps screenshot command should take an optional "comment" argument to describe expected state for manual verification like "shopping cart should have 2 products in it", so that newcomer tester can quickly check if screenshot shows correct state.

**Comment by valentfj** [comment] 2019-01-27 16:48
Great idea

**Comment by bugb** [comment] 2019-01-28 04:33
The captureEntirePageScreenshot feature will be great!

**Comment by cfdd73** [comment] 2019-04-29 15:03
+1

**Comment by digital-soul18** [comment] 2019-06-20 00:40
++++1

Would really love to see this ... I can't find it in the latest IDE

**Comment by wagnerteixeira** [comment] 2019-10-15 19:13
+1

**Comment by mortezaalizadeh** [comment] 2020-04-05 21:54
+1

**Comment by tourdedave** [comment] 2020-04-07 07:18
Appreciate the interest on getting the feature added. There's currently no ETA for adding it. If someone wants to contribute a PR to add it we will happily accept it.

**Comment by toddtarsi** [comment] 2022-11-10 05:37
Closing this, if anyone needs this on v4 they can raise a new issue.

**Closed by toddtarsi** 2022-11-10 05:37 UTC
Labels: enhancement, c-command request
