### ISSUE TITLE
I want the feature that I can record or playback on an existing opened page

### ISSUE THREAD

**Issue by YanFenGuo** [SeleniumHQ/selenium-ide#480] opened 2018-11-06 06:09 UTC
## 💥 Regression Report

On the latest 3.4 version, each time I want to record or execute a test, it is required to start a new page. I love the idea that I can run part of the test on an existing page, currently with this version I can't do this!

## Last working version

Worked up to version: Not sure

Stopped working in version: 3.4.4

## To Reproduce

Open Selenium plugin from Chrome, select record a new test, after inputing the project name, it
 is required to input a base URL to start recording, I can't record with existing pages. 

## Expected behavior

I just want to record and playback some steps on an existing pages, it works perfect before, but now with this new version, I can't do this.

## Project file reproducing this issue (highly encouraged)

My previous project file doesn't contain a URL start, I removed that on purpose, because I want the recording play on an existing page.

## Environment

OS: <MacOS>
Selenium IDE Version:  3.4.4

Browser:
Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by corevo** [comment] 2018-11-06 09:28
Duplicate of #440

**Closed by corevo** 2018-11-06 09:28 UTC
