### ISSUE TITLE
Start from here function Re-starts the script, doesn't start from here as expected

### ISSUE THREAD

**Issue by Kielmed** [SeleniumHQ/selenium-ide#339] opened 2018-08-14 11:24 UTC
## To Reproduce

Run any script and stop it, try and restart from the place using right click and the script starts from the beginninng
## Expected behavior
The script should restart from the command where the cursor is located when start from here is selected

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  <3.2.1>
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version: <Both the latest Chrome and Firefox>

**Comment by tourdedave** [comment] 2018-08-14 11:26
This is a duplicate of #337

**Closed by tourdedave** 2018-08-14 11:26 UTC
Labels: duplicate
