### ISSUE TITLE
StoreEval missing

### ISSUE THREAD

**Issue by AyaSF** [SeleniumHQ/selenium-ide#234] opened 2018-06-14 15:51 UTC
Hi,

The StoreEval command is missing in the Selenium IDE Firefox Version 3.0.3.0.

Thank you by advance for this add.
AyaSF

**Comment by corevo** [comment] 2018-06-14 17:58
Duplicate of https://github.com/SeleniumHQ/selenium-ide/issues/138#issuecomment-378153014

**Closed by corevo** 2018-06-14 17:58 UTC

**Comment by AyaSF** [comment] 2018-06-16 10:08
ok, replace it with this command :

<tr>
	<td>store</td>
	<td>javascript{ command of old storeEval }</td>
	<td>dateToday</td>
</tr>
