### ISSUE TITLE
Set focus to a newly inserted command

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#501] opened 2018-11-26 06:02 UTC
## 🚀 Feature Proposal

When a user inserts a new command to an exitsting scenario they most probably are going to edit this command immediately. So it would be wise to make the newly inserted command active and set focus to its first field ("Command")

**Comment by tourdedave** [comment] 2018-11-26 07:47
Duplicate of #365

**Closed by tourdedave** 2018-11-26 07:47 UTC
Labels: duplicate

**Comment by barancev** [comment] 2018-11-26 07:56
OMG, I forgot my own issue... Sorry :(

**Comment by tourdedave** [comment] 2018-11-26 08:34
No worries :-)

--
Cheers,
Dave H
