### ISSUE TITLE
How to Parameterise in new selenium IDE Plugin(Chrome) 

### ISSUE THREAD

**Issue by wolvriene** [SeleniumHQ/selenium-ide#1043] opened 2020-05-11 07:53 UTC
How to pass variable such as username, password and input data such as search name in selenium IDE Plugin(Chrome) ?

**Comment by corevo** [comment] 2020-05-11 08:30
Duplicate of #183

**Closed by corevo** 2020-05-11 08:30 UTC

**Comment by wolvriene** [comment] 2020-05-11 09:36
@corevo 

Could you please help me i am not able to understand, it is possible or not if it is how ?

**Comment by wolvriene** [comment] 2020-05-11 09:59
I tried by installing file-ulpoader plugin its taking ${username} as input also if i want the same functionality in CLI mode than how can we achieve it.

**Comment by corevo** [comment] 2020-05-11 10:17
I don't know what that plugin is, you'll have to ask the person who made it.

**Comment by wolvriene** [comment] 2020-05-11 10:25
@tourdedave 
Can you help me with this ?
