### ISSUE TITLE
webExtension

### ISSUE THREAD

**Issue by OrangeManDavid** [SeleniumHQ/selenium-ide#890] opened 2019-11-23 03:20 UTC
About firefox and chrome extension,How packaged and building?
When run [yarn build-firefox],it's have a error.

error:
cat: ../../.web-extension-id: No such file or directory
/bin/sh: 1: web-ext: not found

source: tag-V3

selenium-ide/packages/selenium-ide/package.json
"scripts": {
    "start": "env NODE_ENV=test webpack-dev-server --hot",
    "build": "rm -rf build && env NODE_ENV=production webpack",
    "build:dev": "webpack",
    "build-chrome": "./build.sh build ../../selenium-ide.pem 1>/dev/null && mkdir -p dist && mv build.crx dist/selenium-ide.crx && echo \"Wrote dist/selenium-ide.crx\"",
    "build-firefox": "web-ext sign -s build -a dist --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --id=$(cat ../../.web-extension-id)",
    "version": "node scripts/version.js && git add src/manifest.json",
    "prepublishOnly": "yarn build-prod",
    "watch": "yarn build:dev -w"
  },

**Comment by OrangeManDavid** [comment] 2019-11-23 04:33
I put a lot of stuff in searching an easy way to develop a Firefox extension, but I am unable to create an extension. Kindly tell me the file structure of Firefox extensions and an easy way to install the extension.

**Comment by OrangeManDavid** [comment] 2019-11-23 04:36
web-extension-id folder： What should I put in this folder? 

"build-firefox": "web-ext sign -s build -a dist --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --id=$(cat ../../.web-extension-id)"

**Comment by corevo** [comment] 2019-11-23 09:05
Duplicate of #889

**Closed** 2019-11-23 09:06 UTC
