### ISSUE TITLE
Allow stored variables to persist when stopping/starting script playback

### ISSUE THREAD

**Issue by cford-hub** [SeleniumHQ/selenium-ide#1015] opened 2020-04-17 18:20 UTC
## 🚀 Feature Proposal

A clear and concise description of what the feature is.

This was a feature in the original Selenium IDE in Firefox, and is very helpful.  It allows the variables stored throughout the script to persist, so if a script fails at a step, you do not have to re-run the entire script to continue using the previously stored variables.  The new IDE is cumbersome, as you have to start from the beginning each time. 

Please outline the motivation for the proposal.

The motivation is it's a better user experience and more efficient for the person writing the script or importing the script from the previous version of FF.  Having to start from the beginning of the script each time a step fails is extremely time consuming.

Please provide an example for how this feature would be used.

Store a product ID variable at the beginning of the script
Use this variable throughout the script in targets (ex:  click a buy button on a cart, where the target includes the product ID)
Validate something else on the page
Something else fails validation
---script writer would correct the failed validation and like to proceed with the script from that step
Click another button on the page that contains the product ID variable
---the script fails, b/c it no longer retains the product ID variable, so you have to start the script all over.

**Comment by jar452** [comment] 2020-04-27 13:54
I tried submitting this the other day.  Check out ticket 1008:
https://github.com/SeleniumHQ/selenium-ide/issues/1008

**Comment by corevo** [comment] 2020-04-27 14:04
Duplicate of #1008

Again I would start the IDE in debug mode & place a breakpoint in the command that is failing, for the same reasons that code doesn't persist memory so does the IDE, and for the same reasons editing the script is also impossible mid-run.

It is a tradeoff with other IDE capabilities, such as loops and conditions.

**Closed by corevo** 2020-04-27 14:04 UTC
