### ISSUE TITLE
Step Over Current Command Should immediately run current command

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#450] opened 2018-10-12 09:36 UTC
We need a button which works like "X". I feel like this has changed in 3.4.3 - previously when you clicked "Step" it would immediately run the current command. This was excellent for debugging because you could step, make a change, step.

Now, when you click "Step" it somehow restarts the test and you lose where you were.

As an example make a test which 1) Opens a URL and 2) Checks for text in the page.

If you click on Step 1 it will open the URL. Now, if you stop the test...
![image](https://user-images.githubusercontent.com/498834/46861107-2200a180-ce12-11e8-85ff-bb67019be467.png)
...and click on Step 2 and then say "Step" it will not continue where it left off but reset everything:
![image](https://user-images.githubusercontent.com/498834/46861123-2f1d9080-ce12-11e8-81b1-0313b7595d12.png)

Perhaps this is "by design" but it would really be useful to be able to execute just one step as you can with "X" on the keyboard.

**Comment by Yrds** [comment] 2018-10-15 17:37
Possible duplicate of #440

**Comment by cawoodm** [comment] 2018-10-24 17:58
Yes, issue 440 is certainly similarly annoying.

**Comment by corevo** [comment] 2018-11-06 09:28
Duplicate of #440

**Closed by corevo** 2018-11-06 09:28 UTC
