### ISSUE TITLE
Selenium IDE cannot select option from select menu drop-down

### ISSUE THREAD

**Issue by steevithak** [SeleniumHQ/selenium-ide#1840] opened 2024-06-13 17:23 UTC
## 🐛 Bug Report

I'm using Selenium IDE 3.17.2 with Chrome

I'm attempting to record a sequence of commands to pick an option from a select menu. The record adds a click command followed by a select command and that looks correct to me, but when played back it has no effect on the select menu, the menu remains unselected. No errors are reported and each individual command has a green "OK" beside but the select menu remains unchanged after playback.

## To Reproduce

1. Start record
2. click select menu to open
3. click desired menu option

## Expected behavior

I expect to see the option selected by the command actually selected on the menu after playback. 

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Can't attach .side file (github error: "We don't support that file type" when I tried to attach). Will make another attempt after bug report is complete.

Here's the selectmenu HTML in question

```
<select name="geosite_select" id="geosite_select" size="1" onchange="selectGeosite(this);">
  <option id="geosite_NONE" value="NONE" selected="selected">- Select -</option>
  <option id="geosite_custom" value="CUSTOM">GROUP/CUSTOM</option>
  <option id="geosite_204" value="204"> Geosite #204 </option>
  <option id="geosite_207" value="207"> Geosite #207 </option>
  <option id="geosite_208" value="208"> Geosite #208 </option>
  <option id="geosite_48" value="48"> Geosite #48-SITGVHF1 </option>
  <option id="geosite_49" value="49"> Geosite #49-SITGVHF1 </option>
  <option id="geosite_50" value="50"> Geosite #50-SITGVHF1 </option>
  <option id="geosite_205" value="205"> Geosite_ASLT_Device </option>
  <option id="geosite_206" value="206"> Geosite_Devices </option>
  <option id="geosite_201" value="201"> Geosite_VLan32_SNMP </option>
  <option id="geosite_33" value="33"> Geosite_Vlan33 </option>
  <option id="geosite_36" value="36"> Geosite_Vlan36 </option>
  <option id="geosite_37" value="37"> Geosite_Vlan37 </option>
  <option id="geosite_40" value="40"> Geosite_Vlan40 </option>
  <option id="geosite_1" value="1"> NMS-router </option>
  <option id="geosite_200" value="200"> NTP </option>
  <option id="geosite_5000" value="5000"> Radio Subnet </option>
  <option id="geosite_all" value="ALL">ALL</option>
</select>
```

Issues without a reproduction project are likely to stall.

## Environment

OS: Windows 10 
Selenium IDE Version: 3.17.2  
Selenium SIDE Runner Version: Unknown, I don't see this information in the Chrome extension or Selenium IDE itself 
Node version: Unknown, I don't see this information in the Chrome extension or Selenium IDE itself 
Browser: Chrome 125.0.6422.142 (Official Build) (64-bit)
Browser Version: 125.0.6422.142 (Official Build) (64-bit)

**Comment by steevithak** [comment] 2024-06-13 17:28
It doesn't seem possible to upload *.side files, so I'll paste in the file contents here. I've removed the URLs as they refer to internal testing servers that are not accessible from the Internet.

```
{
  "id": "01233ceb-d9a1-4881-b205-c25b94b94219",
  "version": "2.0",
  "name": "selenium-ide-trial",
  "url": "###removed###",
  "tests": [{
    "id": "5c906a11-f868-4bdb-a6f1-b4691e2938f5",
    "name": "selectmenu-choose207",
    "commands": [{
      "id": "4da8c0ab-d759-4d8b-9e9f-a70262954d15",
      "comment": "",
      "command": "open",
      "target": "/cgi-bin/security/login.cgi",
      "targets": [],
      "value": ""
    }, {
      "id": "1f5d5b8b-d707-43c3-89eb-917ea6940e31",
      "comment": "",
      "command": "setWindowSize",
      "target": "1610x927",
      "targets": [],
      "value": ""
    }, {
      "id": "205d8e8b-0031-4226-b4e1-ab5612d68f8a",
      "comment": "",
      "command": "click",
      "target": "linkText=Alarm Browser",
      "targets": [
        ["linkText=Alarm Browser", "linkText"],
        ["css=#reportingmng > li:nth-child(1) > .enabled", "css:finder"],
        ["xpath=//a[contains(text(),'Alarm Browser')]", "xpath:link"],
        ["xpath=//ul[@id='reportingmng']/li/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, '/cgi-bin/reporting/alarm_client.cgi')]", "xpath:href"],
        ["xpath=//li[6]/ul/li/a", "xpath:position"],
        ["xpath=//a[contains(.,'Alarm Browser')]", "xpath:innerText"]
      ],
      "value": ""
    }, {
      "id": "be9bccca-6e8d-4cbc-a34f-3b0faeaa35c3",
      "comment": "",
      "command": "click",
      "target": "id=geosite_select",
      "targets": [
        ["id=geosite_select", "id"],
        ["name=geosite_select", "name"],
        ["css=#geosite_select", "css:finder"],
        ["xpath=//select[@id='geosite_select']", "xpath:attributes"],
        ["xpath=//td[@id='alarm_status_area']/table/tbody/tr[3]/td/select", "xpath:idRelative"],
        ["xpath=//tr[3]/td/select", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "c90ae161-2a44-4677-a996-a287af6d7863",
      "comment": "",
      "command": "select",
      "target": "id=geosite_select",
      "targets": [],
      "value": "label=Geosite #207"
    }]
  }],
  "suites": [{
    "id": "b6075623-1f43-45f3-b759-3ffc23c061a6",
    "name": "trial-test-suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": []
  }],
  "urls": ["###removed###"],
  "plugins": []
}

```

**Comment by steevithak** [comment] 2024-06-13 19:28
Update: I think the problem may be that these pages use several AJAX calls to load data and Selenium IDE isn't waiting for that to complete before starting the test commands. I eventually found a work-around by adding Command: Pause, Target: 2000. Is there a better way to have Selenium IDE recognize when page loading is complete (including ajax initialization calls)?

**Comment by toddtarsi** [comment] 2024-06-13 19:35
@steevithak - I don't think so. That seems hard anyway. I think the better way to do this is a command like 'wait for element visible' or similar rather than 'pause'. I should also mention that v4 has built in async polling for the whole present -> visible -> interact loop.

**Comment by toddtarsi** [comment] 2024-06-29 09:17
Closing this, as it is completely resolved by design in v4. Clicks naturally poll for 5s

**Closed as completed by toddtarsi** 2024-06-29 09:17 UTC
