### ISSUE TITLE
Missing storeEval and Evaluate

### ISSUE THREAD

**Issue by purefan** [SeleniumHQ/selenium-ide#162] opened 2018-04-19 14:59 UTC
Hello,

Using the chrome extension I can't find `Evaluate` or `storeEval`. The `store` command is very useful but in a way fails to store values from javascript expressions, for example:

| Command | Target | Value |
|---------------|----------|----------|
| store | `javascript{"campaign #" + Math.floor(Math.random() * 1000)}` | random_campaign_name |

Is stored as an expression that is executed every time I call the variable:

| Command | Target | Value |
|---------------|----------|----------|
| send keys | `xpath=//*[@type="campaign_name"]` | ${random_campaign_name} |

...the input gets a new number

**Comment by corevo** [comment] 2018-04-20 09:52
Duplicate of #138

**Closed by corevo** 2018-04-20 09:52 UTC

**Comment by purefan** [comment] 2018-04-23 13:07
I see @corevo, makes sense what you posted in #138 
However, I still need a random name for my campaigns, how about adding a function or a mechanism to manipulate the internal variables? I remember `storedVars` being a way to handle these situations.

For my case, all I need is a string that has a random number in it, so a function that generated that random int for me is all I need:
- Command: `randomInt`
- Target: `my_var_name`
- Value: `0,9999`
(the value is the min,max range)

Then I could interpolate that var in a string and I would be a happy penguin :penguin:

**Comment by corevo** [comment] 2018-04-23 13:12
This is actually do-able with `eval`.  
The reason I am so harsh about it is because people might use it to manipulate the DOM.  
Which is exactly what browser vendors don't want extension to do.  
But this use-case is perfectly in line with [sandbox eval](https://developer.chrome.com/extensions/sandboxingEval), so perhaps adding a `storeSandboxEval` command, that takes a target variable, and value javascript, and executes it safely would be a good idea.  
The problem is that it won't have the same power as old `eval` since there won't be access to the AUT.

**Comment by linhdoanvn** [comment] 2018-08-22 18:25
fsdfsdfdsf

**Comment by corevo** [comment] 2018-08-26 08:29
Use `execute script` instead of `store` (e.g. `execute script | return ${x} === ${y} | result`).  
`store` can no longer preprocess javascript, also preprocessing javascript is deprecated, and the runner doesn't support it.

**Comment by paulwoode** [comment] 2019-07-19 16:46
@linhdoanvn @corevo : im trying to create a new SIDE.. I am struggle with below and will appreciate your thoughts. 

***What I want to accomplish per test run***
1.Create random service  ( this can be alpha numeric)
2.Find the service name ( look in the web page to find  <new service in step1 >separate script)
3. Do something with it ( Maybe edit the service infor)
