### ISSUE TITLE
Access jQuery window.$ within a test case

### ISSUE THREAD

**Issue by rafael-sousa** [SeleniumHQ/selenium-ide#1139] opened 2020-10-06 20:42 UTC
I've been struggling to get the jQuery ref attached to the global window object when running some test cases. It looks like the window object within the test case is not the same as the object from the tested page. Is that the correct behavior? How can I access these functions and properties within the test case and persist the changes to the tested page?

I'm running Selenium IDE v.3.17 on Chrome v85.0

**Comment by corevo** [comment] 2020-10-07 06:10
Duplicate of #527

**Closed by corevo** 2020-10-07 06:10 UTC
