### ISSUE TITLE
Selenium-side-runner run on my chrome profile from cmd

### ISSUE THREAD

**Issue by manikantayarramsetti1** [SeleniumHQ/selenium-ide#1672] opened 2023-07-10 06:52 UTC
## To Reproduce:
i trying selenium test to open in my 'Default' profile but it is opening in unsigned profile not in my chrome profile. I tried this command to open in my profile but it is not opening.
selenium-side-runner -c "goog:chromeOptions.args=[user-data-dir=/Users/manikanta/Library/Application Support/Google/Chrome/Default] browserName=chrome"  /Users/manikanta/Downloads/qA-NewTest.side

### Expected behavior:
My aim was to start Chrome with selenium-side-runner, and in profile of my selection.Ho w to achieve this in my chrome profile.

#### Environment

Selenium IDE Version: v3.17.2
Selenium SIDE Runner Version: 4.0.0-alpha.51
Node version: v18.16.1
Browser: Chrome
Browser Version: Chrome Version 114.0.5735.198 (Official Build) (arm64)

**Comment by toddtarsi** [comment] 2023-07-10 12:13
Closing as duplicate of #1319

**Closed as completed by toddtarsi** 2023-07-10 12:13 UTC
