### ISSUE TITLE
Is it possible to delete local storage in IDE or side runner?

### ISSUE THREAD

**Issue by clfordhub** [SeleniumHQ/selenium-ide#1517] opened 2022-08-22 14:18 UTC
Side runner returns error:  WebDriverError: <unknown>: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.
      (Session info: chrome=104.0.5112.101)

IDE allows the command to pass, but it doesn't seem to do any deletion.

**Comment by toddtarsi** [comment] 2022-08-22 15:14
@clfordhub - Is this the web extension or the electron app?

**Comment by clfordhub** [comment] 2022-08-22 15:24
This is for the web extension and also the side runner.   What is the electron app?  Is that external?

**Comment by toddtarsi** [comment] 2022-08-22 15:28
It's v4: https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.1
Also, this is the corresponding side-runner (v4): https://www.npmjs.com/package/@seleniumhq/side-runner


It isn't in the app stores yet because I'm trying to get funding from a committee, and its basically an allegory for purgatory and/or hell.

**Comment by toddtarsi** [comment] 2022-08-22 15:29
But I currently use it for e2e testing at my job, and the local playback and remote playback share the same runtime execution loop, so it's a lot more consistent than v3 could ever hope to be.

That said, it is still in alpha, some commands are missing that need to be added, but it might be what you're looking for.

**Comment by toddtarsi** [comment] 2022-08-22 15:30
Also, on mac (not sure about other platforms), you can open side files in it by double clicking them, and that feels pretty darn sweet.

**Comment by clfordhub** [comment] 2022-08-22 17:46
Ok, awesome.  What version does the browser extension use?   I'll try out 4.0 on my VM.  Does the new side runner work with the latest node.js?  I think right now I'm running v14, b/c side runner wasn't compatible with v16.  Is there a trick to use the IDE portion?  I keep hitting play, but nothing executes in v4.

**Comment by toddtarsi** [comment] 2022-08-22 18:01
I think the browser extension uses privileged JS to emulate playback, and the old side runner uses v3 of the selenium-webdriver API. It's mostly consistent, but falls apart a bit around other privileged stuff like execution boundaries and alerts and stuff.

**Comment by toddtarsi** [comment] 2022-08-22 18:05
@clfordhub - I believe I run my tests using the v4 side-runner on Node 16, but I haven't tested later than that (sorry). I think v14 and v16 should both be fine.

Sharts! I would really like it if the play portion just worked in the IDE. It should just work. It's very hermetic (electron + paired chromedriver version running selenium-webdriver latest). Are you hitting a public facing site? We don't have telemetry or crash data wired up yet unfortunately, but if its public, maybe you can send me the side file and I could try testing it out later tonight?

**Comment by clfordhub** [comment] 2022-08-22 18:34
So, I'm initially trying to hit this site https://login.microsoftonline.com/common/oauth2/logout b/c the site I'm testing is private and uses MS authentication.  I created the suite originally in v2 via the import option and just opened it in your alpha version.  It opens fine, but doesn't run. I modified the file to use v3, b/c that was the version that displayed in the file when I created a blank test in v4, so I'm wondering if there is something not compatible in my v2 suite.

**Comment by toddtarsi** [comment] 2022-08-22 18:41
@clfordhub - Great investigation! Okay, so not so easy to repro unfortunately. Let's make sure of the basics first:

1. Does you project load okay in the IDE?
2. Are you able to navigate to your test and does it look okay?
3. Are you doing a lot of frame-switching? Frame-switching should work fine, but my buddy whose helped me a ton (thanks again @coinzdude) noticed he had some issues around frame selection on sites with heavier async frame loading.

**Comment by clfordhub** [comment] 2022-08-22 19:07
1. Yes
2. Yes
3. No

The window that does the playback doesn't seem to attempt to load the page.  Is this compatible with https endpoints? Can you try a new script with just this command?

Open | https://login.microsoftonline.com/common/oauth2/logout

Here is a screenshot for me when I click play.  The playback window is doesn't open the site in the config section.  I've also pasted the side file content below.

https://user-images.githubusercontent.com/111758490/185999103-2b6e828d-33f6-4e50-90a8-3a7911c12aff.png

{
  "id": "76efe167-deee-48c7-92d0-03e54dd6f8ce",
  "version": "3.0",
  "name": "New Project",
  "url": "https://login.microsoftonline.com/common/oauth2/logout",
  "urls": [
    "https://login.microsoftonline.com/common/oauth2/logout"
  ],
  "plugins": [],
  "suites": [
    {
      "id": "e8243364-ff98-45e2-8a2d-84e94de16177",
      "name": "New Suite",
      "parallel": false,
      "persistSession": false,
      "tests": [
        "d7914596-45d2-4d62-be4c-45523cd7f647"
      ],
      "timeout": 30000
    }
  ],
  "tests": [
    {
      "id": "d7914596-45d2-4d62-be4c-45523cd7f647",
      "name": "Logout",
      "commands": [
        {
          "id": "83ed6672-e59e-4ce3-8fdb-81f3a42f6f42",
          "command": "open",
          "target": "/",
          "value": ""
        }
      ]
    }
  ],
  "snapshot": {
    "dependencies": {},
    "tests": [],
    "jest": {
      "extraGlobals": []
    }
  }
}

**Comment by toddtarsi** [comment] 2022-08-22 19:30
@clfordhub - Ah! I think I see it. So, if you go to the "Config" tab, you'll see the below image. Basically, if you change your URL to this, it should work:

https://login.microsoftonline.com/

It's basically combining your '/' and your URL to get https://login.microsoftonline.com/common/oauth2/logout as your entry point

<img width="699" alt="Screen Shot 2022-08-22 at 2 29 05 PM" src="https://user-images.githubusercontent.com/4707505/186003001-5d24313a-578c-4660-8384-aa17d2afb60c.png">

**Comment by clfordhub** [comment] 2022-08-22 20:34
I tried that, but got the same result.  Would you be will to do a screenshare with me.  I'm sure we can figure in out in 10 minutes.

**Comment by toddtarsi** [comment] 2022-08-22 21:10
I'm busy right now, but should be available later tonight in roughly 5 hours.

I did try this and got the page to load btw.

Updated side file:

```
{
  "id": "76efe167-deee-48c7-92d0-03e54dd6f8ce",
  "version": "3.0",
  "name": "New Project",
  "url": "https://login.microsoftonline.com/",
  "urls": [
    "https://login.microsoftonline.com/common/oauth2/logout"
  ],
  "plugins": [],
  "suites": [
    {
      "id": "e8243364-ff98-45e2-8a2d-84e94de16177",
      "name": "New Suite",
      "parallel": false,
      "persistSession": false,
      "tests": [
        "d7914596-45d2-4d62-be4c-45523cd7f647"
      ],
      "timeout": 30000
    }
  ],
  "tests": [
    {
      "id": "d7914596-45d2-4d62-be4c-45523cd7f647",
      "name": "Logout",
      "commands": [
        {
          "id": "83ed6672-e59e-4ce3-8fdb-81f3a42f6f42",
          "command": "open",
          "target": "/",
          "value": ""
        }
      ]
    }
  ],
  "snapshot": {
    "dependencies": {},
    "tests": [],
    "jest": {
      "extraGlobals": []
    }
  }
}
```

**Comment by clfordhub** [comment] 2022-08-22 21:33
That'd be great if you are still free.  I'm CST time zone, so I'll get back on here and we can connect.

**Comment by toddtarsi** [comment] 2022-08-23 03:22
@clfordhub - Hey, I'm sorry this is late. I was putting my toddler down and I passed out first, but I woke up just now if you want to meet real quick. If not, we can screen share tomorrow but I have to keep it really minimal if its in my nine to five region.

**Comment by toddtarsi** [comment] 2022-08-23 03:24
@clfordhub - Also, if you use slack, feel free to message me on Slack directly. My username is the same as my username here. 🙂

**Comment by toddtarsi** [comment] 2022-08-23 03:27
@clfordhub - Oh shoot I forgot, here's a link to the Seleniumhq channel on Slack:

https://seleniumhq.slack.com/ssb/redirect

**Comment by clfordhub** [comment] 2022-08-23 14:32
@toddtarsi  No worries.  I think I just missed you last night, as I got tired too.  :)  I don't have a slack account.  Do you use Skype?

**Comment by toddtarsi** [comment] 2022-08-23 14:33
@clfordhub - I do very rarely. I think my name there should be the same.

**Comment by toddtarsi** [comment] 2022-08-23 14:34
@clfordhub - If you send me a DM on the selenium slack channel, I will respond to it either the same or next day, very synchronously. If you send me a DM on skype, maybe once a year I'll respond. I don't have it installed

**Comment by clfordhub** [comment] 2022-08-23 15:12
@toddtarsi Can you send me an invite the slack channel.  It won't let me in with my google account for some reason.

**Comment by toddtarsi** [comment] 2022-08-23 15:16
@clfordhub - Try following the link in here under the chat room section:

https://www.selenium.dev/support/

Call me paranoid, but I don't like asking for emails in public forums

**Comment by toddtarsi** [comment] 2022-08-25 14:31
@clfordhub - I'm closing this issue because there isn't really an issue in the localStorage delete commands. Please raise issues around IDE problems specific to your OS or run commands failing in the side-runner. If you can provide a reproducing side file as well, that will greatly accelerate my bughunt. Thanks!

**Closed as completed by toddtarsi** 2022-08-25 14:31 UTC
