### ISSUE TITLE
IDE clicking links opening 2 tabs

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#344] opened 2018-08-14 19:53 UTC
@modnar1226 commented on [Tue Aug 14 2018](https://github.com/SeleniumHQ/selenium/issues/6282)

## Meta -
OS:  Windows 10

Selenium Version:  3.2 IDE

Browser:  Firefox

Browser Version:  61.0.2 (64-bit)

## Expected Behavior -
External Links to open one page, blank commands or commands with just comments continue test
## Actual Behavior -
External Links to open 2 pages , blank commands or commands with just comments fail test
## Steps to reproduce -

example commands:

{
      "id": "8b361480-6900-499b-9528-b4a96dc8100a",
      "comment": "",
      "command": "clickAt",
      "target": "css=#dataTable1 > tbody > tr.child > td > div > div:nth-child(2) > em > em > strong:nth-child(7) > strong > p > a",
      "targets": [],
      "value": ""
    }

this is the link it opens: 
href="http://docquery.fec.gov/cgi-bin/fecimg/?201606109017556842"

this command set as follows will cause a failure where previously it wouldn't.
 {
      "id": "645bcd21-32c1-4624-8dbe-8c4877cef97f",
      "comment": "Tests top of page stuff",
      "command": "",
      "target": "",
      "targets": [],
      "value": ""
    }

**Comment by corevo** [comment] 2018-08-15 05:17
@modnar1226 please provide a reproducible project file, if possible.

**Comment by corevo** [comment] 2018-08-15 05:17
The comments are duplicate of #340

**Comment by modnar1226** [comment] 2018-08-15 12:19
@corevo this is my first time submitting a bug here. The site I'm testing has restricted access. I don't what else i can give that you could use to reproduce with out access.

**Comment by modnar1226** [comment] 2018-08-15 12:53
Using yahoo as a search engine. They open their links in a new tab. 
This is short and concise demo of the issue
OS: Windows 10

Selenium Version: 3.2 IDE

Browser: Firefox

Browser Version: 61.0.2 (64-bit)
{
  "id": "72023107-bba5-4891-a8cd-23efe724d0ec",
  "name": "Untitled Project",
  "url": "",
  "tests": [{
    "id": "b45dc8c1-fc7c-466e-b19f-e4e89866c7f9",
    "name": "Untitled",
    "commands": [{
      "id": "b0f207a5-6ebe-4a94-ac88-c594c4417fb7",
      "comment": "",
      "command": "open",
      "target": "https://www.yahoo.com",
      "targets": [],
      "value": ""
    }, {
      "id": "9e15b2c1-a15f-43d2-a903-c0db263b7761",
      "comment": "",
      "command": "type",
      "target": "css=#uh-search-box",
      "targets": [],
      "value": "all stars"
    }, {
      "id": "7fdd2f5f-0e2f-44f2-a0e4-f349e35d1d6d",
      "comment": "",
      "command": "clickAt",
      "target": "css=#uh-search-button",
      "targets": [
        ["id=lst-ib", "id"],
        ["name=q", "name"],
        ["css=#lst-ib", "css"],
        ["xpath=//input[@id='lst-ib']", "xpath:attributes"],
        ["xpath=//div[@id='gs_lc0']/input", "xpath:idRelative"],
        ["xpath=//div[2]/div/input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "be362d05-c31e-4246-b4d0-c64197fb84e5",
      "comment": "",
      "command": "clickAt",
      "target": "css=#yui_3_10_0_1_1534337406999_410",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "1a92b4fc-ee8a-42ad-a3fd-40ec173726ba",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["b45dc8c1-fc7c-466e-b19f-e4e89866c7f9"]
  }],
  "urls": [],
  "plugins": [],
  "version": "1.0"
}

**Comment by corevo** [comment] 2018-08-15 13:19
Thanks for the info

**Comment by modnar1226** [comment] 2018-08-24 13:33
Is there any info on the fix for this by chance?

**Comment by corevo** [comment] 2018-09-17 16:03
This bug originates from `bot.userAgent.FIREFOX_EXTENSION` being `false` in the new extension, I will patch it in the extension (for the meantime), but a fix for it will have to propagate to Selenium's atoms, which I will get to at a later date.

**Comment by tourdedave** [comment] 2018-11-14 10:02
@corevo Any update on the fix landing upstream?

**Comment by corevo** [comment] 2019-02-07 11:40
Fixed in https://github.com/SeleniumHQ/selenium/commit/30a715841462cd3856492e5d631926de22d4b46d

**Closed by corevo** 2019-02-07 11:40 UTC
