### ISSUE TITLE
Rememember the path of the previously saved file

### ISSUE THREAD

**Issue by frague59** [SeleniumHQ/selenium-ide#378] opened 2018-08-31 09:23 UTC
## 🚀 Feature Proposal

When saving a test file, SeIDE does not remember the location of the current file

## Motivation

Would be nice to not to have to re-set the full path of the file on each save

## Example

Allow incremental file saving on test creation...

**Comment by corevo** [comment] 2018-09-02 08:30
Duplicate of #363

**Closed by corevo** 2018-09-02 08:30 UTC
