### ISSUE TITLE
New Selenium IDE UI does not allow user to copy/paste/delete multiple lines.

### ISSUE THREAD

**Issue by ianhe1** [SeleniumHQ/selenium-ide#950] opened 2020-02-10 23:25 UTC
## 🐛 Bug Report

The old Selenium IDE allows user to select multiple lines and operate on the selected lines. But the new Selenium IDE does not allow user to do that.

As an user I created the test cases in new Selenium IDE UI. When I need to delete or copy multiple lines in the test case, I cannot select more than one lines. I have to delet or copy one line at a time. 

## To Reproduce
1. Create a test case with multiple lines
2. Try to select 2 or more lines to copy or delete them
Now I cannot select multiple lines.

## Expected behavior
I am expecting to be able to select multiple lines and copy or delete them at the same time.

## Project file reproducing this issue (highly encouraged)
This is easy to reproduce and no need to provide a project.

## Environment

OS:  Windows 10 
Selenium IDE Version:  3.0.3 
Browser:
Browser Version: Chrome 79.0.3945.130 (Official Build) (64-bit)

**Comment by jar452** [comment] 2020-04-09 18:55
This is my number 1 need and would allow me to create scripts exponentially faster.

**Comment by corevo** [comment] 2020-04-09 20:44
Duplicate of #189

**Closed by corevo** 2020-04-09 20:44 UTC
