### ISSUE TITLE
Unable to export. Cannot read property of undefined

### ISSUE THREAD

**Issue by adrianafdz** [SeleniumHQ/selenium-ide#1256] opened 2021-07-19 18:37 UTC
## 🐛 Bug Report

I want to export a test suite, but I get the following error. I've seen other similar issues where the error indicates on what test, but not in this case so I can't find where it's coming from.

![image](https://user-images.githubusercontent.com/68704785/126209750-2a7d691e-b8c0-45b7-abd4-a2836ea95dce.png)

## To Reproduce

I have 3 tests in a test suite, then I try to export it. 
The three tests are basically the same as this, only the target on the first two commands changes.

![image](https://user-images.githubusercontent.com/68704785/126209812-67c00eec-b58c-4b47-b8c6-3fcd193dfe2a.png)

## Environment

OS: Windows 10 Enterprise 20H2
Selenium IDE Version:  3.17.0

Browser: Google Chrome
Browser Version: Versión 91.0.4472.164 (Build oficial) (64 bits)

**Comment by toddtarsi** [comment] 2021-07-28 04:34
@adrianafdz - What format are you exporting to? I am on Mac, so I likely won't get the same bugs, but knowing this info may help me winnow things down a bit.

**Comment by adrianafdz** [comment] 2021-07-28 14:47
@toddtarsi I wanted to export it to Python, but I get the same error with all of the languages available.

**Comment by toddtarsi** [comment] 2021-07-28 15:01
@adrianafdz - Interesting. Thanks for providing the granular info. I'll run some tests tonight using your script.

**Comment by toddtarsi** [comment] 2021-07-28 15:03
@adrianafdz - We just merged a related fix [here](https://github.com/SeleniumHQ/selenium-ide/pull/1042), so 🤞 the issue is already resolved

**Comment by toddtarsi** [comment] 2021-12-15 19:13
@adrianafdz - I'm closing this, it should be resolved on latest. Please feel free to re-open if this isn't the case. Thanks!

**Closed as completed** 2021-12-15 19:13 UTC
