### ISSUE TITLE
I want to enable communication between an external application and Selenium-IDE.

### ISSUE THREAD

**Issue by divz1010** [SeleniumHQ/selenium-ide#812] opened 2019-09-14 16:42 UTC
### Please note that this issue tracker is not a help form and this issue will be closed.
 I want to communicate selenium ide from my application and get all the inputs and store in my database please let me know how to do it

**Comment by corevo** [comment] 2019-09-15 06:54
Duplicate of #810

**Closed by corevo** 2019-09-15 06:54 UTC
