### ISSUE TITLE
How to take / capture screen shots in Selenium IDE???

### ISSUE THREAD

**Issue by naveenht** [SeleniumHQ/selenium-ide#1009] opened 2020-04-10 15:22 UTC
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by corevo** [comment] 2020-04-12 06:26
Duplicate of #182

**Closed by corevo** 2020-04-12 06:26 UTC
