### ISSUE TITLE
Rollup library equivalent feature/function for custom functions within Selenium IDE

### ISSUE THREAD

**Issue by scottspence** [SeleniumHQ/selenium-ide#1148] opened 2020-10-16 00:24 UTC
## 🚀 Feature Proposal

This was a version in a previous version of Selenium IDE (firefox-only version). Basically a library of custom functions that could perform repeatable actions, using variables passed in the function. Perhaps there is a way to use libraries within other areas of Selenium or Selenium IDE? Please let me know if there is.

## Motivation

This allows frequently used sets of functions during testing to be managed in one place, when there is a change only one routine needs to be updated, and all tests can immediately benefit from the change. 

## Example

I have attached a sample that includes a portion of a rollup that I have used previously. 

[rollup-public.txt](https://github.com/SeleniumHQ/selenium-ide/files/5388497/rollup-public.txt)

**Comment by corevo** [comment] 2020-10-16 08:51
Duplicate of #586

**Closed by corevo** 2020-10-16 08:51 UTC
